TZ = Asia/Tokyo
#LANG = ja_JP.UTF-8
LANG = en_US.UTF-8

DOCKER_CMD = docker
### Compose v1
DOCKER_COMPOSE_CMD = docker-compose
### Compose v2
#DOCKER_COMPOSE_CMD = docker compose

#GFDOCKER_PROXY_HOST = 192.168.0.1
#GFDOCKER_PROXY_PORT = 8080
GFDOCKER_PROXY_HOST =
GFDOCKER_PROXY_PORT =
GFDOCKER_NO_PROXY = localhost,127.0.0.1
GFDOCKER_NUM_JOBS = 8

# number of containers
#GFDOCKER_NUM_GFMDS >= 1
#GFDOCKER_NUM_GFSDS >= 1
#GFDOCKER_NUM_CLIENTS >= 1
GFDOCKER_NUM_GFMDS = 3
GFDOCKER_NUM_GFSDS = 4
GFDOCKER_NUM_CLIENTS = 2

# number of local/global accounts
GFDOCKER_NUM_USERS = 4

# requirements:
#GFDOCKER_IP_VERSION: syntax: 4 or 6
#GFDOCKER_SUBNET: syntax: ${ip_address}/${prefix}
#GFDOCKER_START_HOST_ADDR: syntax: intager
GFDOCKER_IP_VERSION = 4
#GFDOCKER_SUBNET = 10.2.3.0/24
GFDOCKER_SUBNET = 192.168.224.0/24
GFDOCKER_START_HOST_ADDR = 11

# syntax: [A-Za-z0-9]([A-Za-z0-9]|-|_)*
GFDOCKER_HOSTNAME_PREFIX_GFMD = gfmd
GFDOCKER_HOSTNAME_PREFIX_GFSD = gfsd
GFDOCKER_HOSTNAME_PREFIX_CLIENT = client

#GFDOCKER_HOSTNAME_SUFFIX =
#GFDOCKER_HOSTNAME_SUFFIX = .example.com
GFDOCKER_HOSTNAME_SUFFIX = .test

# qemu-user-static is used if not empty
GFDOCKER_PLATFORM =
#GFDOCKER_PLATFORM = linux/arm64
#GFDOCKER_PLATFORM = linux/arm/v7
#GFDOCKER_PLATFORM = linux/amd64
#GFDOCKER_PLATFORM = linux/386
#GFDOCKER_PLATFORM = linux/ppc64le

# syntax: sharedsecret, gsi or gsi_auth
GFDOCKER_AUTH_TYPE = gsi_auth

# GFDOCKER_GFMD_JOURNAL_DIR = /var/gfarm-metadata/journal/
GFDOCKER_GFMD_JOURNAL_DIR = /dev/shm/gfarm-metadata/journal/

# --no-cache for docker build (0: disable, 1: enable)
GFDOCKER_NO_CACHE = 0
SUDO = sudo

# using port numbers of host OS
GFDOCKER_HOSTPORT_S3_HTTP = 18080
GFDOCKER_HOSTPORT_S3_HTTPS = 18443

# gfarm-s3 users
GFDOCKER_GFARMS3_USERS = user1:user1:K4XcKzocrUhrnCAKrx2Z user2:user2:qzjjOwLjeWptTFUZVThs
GFDOCKER_GFARMS3_SECRET_USER1 = xNMOFbCLhu+FKz1VmIDgHwPUQad0h1arCpdJAiN1oih1gNUx
GFDOCKER_GFARMS3_SECRET_USER2 = DzZv57R8wBIuVZdtAkE1uK1HoebLPMzKM6obA4IDqOhaLIBf

# front web proxy server for gfarm-s3 (apache or nginx)
#GFDOCKER_GFARMS3_FRONT_WEBSERVER=apache
GFDOCKER_GFARMS3_FRONT_WEBSERVER=nginx

GFDOCKER_GFARMS3_MYPROXY_SERVER =
GFDOCKER_GFARMS3_SHARED_DIR = /share

GFDOCKER_GFARMS3_CACHE_BASEDIR = /mnt/cache
GFDOCKER_GFARMS3_CACHE_SIZE = 1024
GFDOCKER_GFARMS3_WSGI_HOMEDIR = /home/wsgi
GFDOCKER_GFARMS3_WSGI_USER = wsgi
GFDOCKER_GFARMS3_WSGI_GROUP = wsgi
GFDOCKER_GFARMS3_WSGI_ADDR = 127.0.0.1:8000
GFDOCKER_GFARMS3_ROUTER_HOMEDIR = /home/wsgi
GFDOCKER_GFARMS3_ROUTER_ADDR = 127.0.0.1:8001

