# $Id: Makefile 2533 2006-03-31 10:50:56Z takuya $

top_builddir = ../../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

datadir=$(default_datadir)/gfarm/gfperf-web

DATA = $(srcdir)/config.php \
       $(srcdir)/config_view.php \
       $(srcdir)/gnuplot.php \
       $(srcdir)/graph_draw.php \
       $(srcdir)/graph_page.php \
       $(srcdir)/index.php \
       $(srcdir)/view_error.php \
       $(srcdir)/view_result.php

include $(top_srcdir)/makes/data.mk
