#!/bin/sh

PATH=/usr/bin:/bin:/usr/ccs/bin:/opt/SUNWspro/bin:/usr/local/bin:/usr/ucb
export PATH

version=1.0.3.1
subpkgs='client devel doc fsnode gfptool server gfront'
prefix=/usr/grid

srcdir=`pwd`
work=$srcdir/..
buildroot=$work/buildroot-$$

make=/usr/local/bin/make
tar=/usr/local/bin/tar
with_prefix=--prefix=$prefix
with_globus=--with-globus=/usr/grid
# XXX "unresolved symbol __eprintf" happens without --with-globus-shared.
with_globus="$with_globus --with-globus-shared"
# XXX --with-mpi needs OPTFLAGS=-O with gcc (an error happens at gfs_hook_mpi).
# XXX currently, MPICH isn't installed on the build-host.
# XXX tar warns missing `gfwc', because it isn't built without --with-mpi.
with_mpi= # --with-mpi=/usr/local/mpich

vendorcc_pkg=/usr/users/soda/install/SunOS-5.8-SUWspro-6.2
with_vendorcc_openldap=--with-openldap=$vendorcc_pkg/openldap-2.1.17
with_vendorcc_openssl=--with-openssl=$vendorcc_pkg/openssl-0.9.7c
# XXX only gcc32 flavor is installed on the build-host.
with_vendorcc_globus_flavor=--with-globus-flavor=gcc32

gcc_pkg=/usr/users/soda/install/SunOS-5.8-gcc-3.3
#with_gcc_openldap=--with-openldap=$gcc_pkg/openldap-2.1.17
# XXX need to update
with_gcc_openldap=--with-openldap=/usr/users/soda/install/SunOS-5.8-gcc-2.95.2/openldap-2.1.17
with_gcc_openssl=--with-openssl=$gcc_pkg/openssl-0.9.7c
with_gcc_globus_flavor=--with-globus-flavor=gcc32

case `whoami` in
root)	;; # OK
*)	echo "root privilege is needed to invoke this script" >&2
	exit 1;;
esac

for pkg in gfarm gfarm-gsi
do
	for cc in vendorcc gcc
	do
		case ${pkg}-${cc} in
		gfarm-vendorcc)
			./configure $with_prefix \
				$with_vendorcc_openldap \
				$with_vendorcc_openssl;;
		gfarm-gsi-vendorcc)
			./configure $with_prefix \
				$with_vendorcc_openldap \
				$with_vendorcc_openssl \
				$with_globus $with_vendorcc_globus_flavor;;
		gfarm-gcc)
			CC=gcc ./configure $with_prefix \
				$with_gcc_openldap \
				$with_gcc_openssl;;
		gfarm-gsi-gcc)
			CC=gcc ./configure $with_prefix \
				$with_gcc_openldap \
				$with_gcc_openssl \
				$with_globus $with_gcc_globus_flavor;;
		esac
		$make

		rm -rf $buildroot
		mkdir -p $buildroot $buildroot$prefix $buildroot/etc
		$make prefix=$buildroot$prefix install
		mkdir -p $buildroot/etc/rc3.d
		cp package/solaris/gfmd $buildroot/etc/rc3.d/S98gfmd
		cp package/solaris/gfsd $buildroot/etc/rc3.d/S99gfsd
		ln $buildroot/etc/rc3.d/S98gfmd $buildroot/etc/rc3.d/K98gfmd
		ln $buildroot/etc/rc3.d/S99gfsd $buildroot/etc/rc3.d/K97gfsd
		chmod +x $buildroot/etc/rc3.d/*
		cp doc/conf/gfarm.conf $buildroot/etc/gfarm.conf.sample
		mkdir -p $buildroot/etc/gfarm-ldap
		cp doc/conf/gfarm.schema $buildroot/etc/gfarm-ldap/
		$make distclean

		( cd $buildroot &&
		  for s in $subpkgs
		  do
			$tar zcf $work/${pkg}-${s}-${cc}-${version}.tar.gz \
				`cat $srcdir/package/solaris/gfarm-${s}.files`
		  done
		)
		rm -rf $buildroot
	done
done

# $Id$
