#!/bin/sh

PATH=/usr/bin:/bin:/usr/ccs/bin:/opt/SUNWspro/bin:/usr/local/bin:/usr/ucb
export PATH

version=1.0b5
subpkgs='client devel doc fsnode gfptool server gfront'

srcdir=`pwd`
work=$srcdir/..
buildroot=$work/buildroot-$$

prefix=--prefix=/usr/grid
make=/usr/local/bin/make
tar=/usr/local/bin/tar
with_globus=--with-globus=/usr/grid
# XXX	"unresolved symbol __eprintf" happens without --with-globus-shared
globus_extra_config=--with-globus-shared
# XXX	--with-mpi needs OPTFLAGS=-O with gcc
#	otherwise gfs_hook_mpi causes error
# XXX	tar reports missing `gfwc' without --with-mpi
with_mpi= # --with-mpi=/usr/local/mpich

vendorcc_pkg=/usr/users/soda/install/SunOS-5.8-SUWspro-6.2
with_vendorcc_openldap=--with-openldap=$vendorcc_pkg/openldap-2.1.17
with_vendorcc_openssl=--with-openssl=$vendorcc_pkg/openssl-0.9.7b
with_vendorcc_globus_flavor=--with-globus-flavor=gcc32

gcc_pkg=/usr/users/soda/install/SunOS-5.8-gcc-2.95.2
with_gcc_openldap=--with-openldap=$gcc_pkg/openldap-2.1.17
with_gcc_openssl=--with-openssl=$gcc_pkg/openssl-0.9.7b
with_gcc_globus_flavor=--with-globus-flavor=gcc32

case `whoami` in
root)	;; # OK
*)	echo "root privilege is needed to invoke this script" >&2
	exit 1;;
esac

for pkg in gfarm gfarm-gsi
do
	for cc in vendorcc gcc
	do
		case ${pkg}-${cc} in
		gfarm-vendorcc)
			./configure $prefix \
				$with_vendorcc_openldap \
				$with_vendorcc_openssl
			;;
		gfarm-gsi-vendorcc)
			./configure $prefix \
				$with_vendorcc_openldap \
				$with_vendorcc_openssl \
				$with_globus $with_vendorcc_globus_flavor \
				$globus_extra_config
			;;
		gfarm-gcc)
			CC=gcc ./configure $prefix \
				$with_gcc_openldap \
				$with_gcc_openssl 
			;;
		gfarm-gsi-gcc)
			CC=gcc ./configure $prefix \
				$with_gcc_openldap \
				$with_gcc_openssl \
				$with_globus $with_gcc_globus_flavor \
				$globus_extra_config
			;;
		esac
		$make

		rm -rf $buildroot
		mkdir -p $buildroot $buildroot/usr/grid $buildroot/etc
		$make prefix=$buildroot/usr/grid install
		mkdir -p $buildroot/etc/rc3.d
		cp package/solaris/gfmd $buildroot/etc/rc3.d/S98gfmd
		cp package/solaris/gfsd $buildroot/etc/rc3.d/S99gfsd
		ln $buildroot/etc/rc3.d/S98gfmd $buildroot/etc/rc3.d/K98gfmd
		ln $buildroot/etc/rc3.d/S99gfsd $buildroot/etc/rc3.d/K97gfsd
		chmod +x $buildroot/etc/rc3.d/*
		cp doc/conf/gfarm.conf $buildroot/etc/gfarm.conf.sample
		mkdir -p $buildroot/etc/gfarm-ldap
		cp doc/conf/gfarm.schema $buildroot/etc/gfarm-ldap/
		$make distclean

		( cd $buildroot &&
		  for s in $subpkgs
		  do
			$tar zcf $work/${pkg}-${s}-${cc}-${version}.tar.gz \
				`cat $srcdir/package/solaris/gfarm-${s}.files`
		  done
		)
		rm -rf $buildroot
	done
done
