top_builddir = ../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

includedir=$(default_includedir)/gfarm
exec_includedir=$(default_exec_includedir)/gfarm

EXEC_INCS= gfarm_config.h
INCS=	gfarm.h error.h gfarm_misc.h gfarm_stringlist.h \
	host_info.h user_info.h group_info.h \
	gfs.h gfs_glob.h

#	gfs_hook.h

include $(top_srcdir)/makes/include.mk
