'\" t
.\"     Title: gfarm_attr
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 31 Mar 2014
.\"    Manual: Gfarm_attr
.\"    Source: Gfarm_attr
.\"  Language: English
.\"
.TH "GFARM_ATTR" "5" "31 Mar 2014" "Gfarm_attr" "Gfarm_attr"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfarm_attr \- Gfarm拡張属性
.SH "DESCRIPTION"
.PP
Gfarmの各ファイルやディレクトリは，拡張属性を複数持つことができます．拡 張属性は，名前に対する値のペアです．
.SH "拡張属性の名前空間"
.PP
"gfarm\&."と"gfarm_root\&."で始まる名前の拡張属性はGfarmが特別に扱いま す．"user\&."で始まる名前の拡張属性はユーザが自由に値を格納できます． XML拡張属性は名前も自由に指定してXMLを格納できます．
.PP
誰でも"gfarm\&.*"の拡張属性を取得できます．所有者，またはgfarmrootグルー プに所属するユーザだけが"gfarm\&.*"の拡張属性を変更できます．
.PP
gfarmrootグループに所属するユーザ、または"gfarm_root\&.user"に記述された ユーザ、または"gfarm_root\&.group"に記述されたグループが、"gfarm_root\&.*" 拡張属性を取得と変更できます。
.PP
ファイルまたはディレクトリのパーミッションによって"user\&.*"拡張属性を取 得と変更できます．
.PP
XML拡張属性は，ファイルまたはディレクトリのパーミッションによって読み書 きできます．
.PP
シンボリックリンクは拡張属性を持つことができません．
.SH "GFARM 拡張属性"
.PP
以下はGfarmのシステムが使用する拡張属性名です．
.PP
\fIgfarm\&.ncopy\fR
.RS 4
自動ファイル複製作成数を格納します． 詳細は gfncopy コマンドのマニュアルを参照してください．
.RE
.PP
\fIgfarm\&.replicainfo\fR
.RS 4
ホストグループごとの自動ファイル複製作成数を格納します． 詳細は gfncopy コマンドのマニュアルを参照してください．
.RE
.PP
\fIgfarm\&.acl_access\fR
.RS 4
ACL(アクセスコントロールリスト)を格納します．
.RE
.PP
\fIgfarm\&.acl_default\fR
.RS 4
デフォルトACLを格納します．ディレクトリだけがこの拡張属性を利用します．
.RE
.PP
\fIgfarm_root\&.user\fR
.RS 4
このファイルやディレクトリに特権を与えるユーザ名のリストを格納します． 名前は改行 (\en) で区切られます．この拡張属性がディレクトリに付いている 場合，新規作成された子エントリにもこの拡張属性がコピーされます．
.RE
.PP
\fIgfarm_root\&.group\fR
.RS 4
このファイルやディレクトリに特権を与えるグループ名のリストを格納しま す．名前は改行 (\en) で区切られます．この拡張属性がディレクトリに付いて いる場合，新規作成された子エントリにもこの拡張属性がコピーされます．
.RE
.SH "SECURITY NOTES"
.PP
任意のディレクトリやファイルの gfarm_root\&.{user,group} 拡張属性に，信頼 していないユーザを登録している場合，\-o suid,allow_other オプションを指 定して root 権限でマウントしている gfarm2fs には (\-o ro オプションまた は \-o default_permissions オプションを付けていたとしても) セキュリティ・ ホールがあります．このため，gfarm2fs の \-o suid,allow_other オプション と gfarm_root\&.{user,group} 拡張属性の両方を同時に利用すべきではありませ ん．
.SH "SEE ALSO"
.PP

\fBgfxattr\fR(1),
\fBgfgetfacl\fR(1),
\fBgfsetfacl\fR(1),
\fBgfncopy\fR(1)
