'\" t
.\"     Title: gfservice.conf
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 8 Mar 2013
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFSERVICE\&.CONF" "5" "8 Mar 2013" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfservice.conf \- gfservice の設定ファイル
.SH "DESCRIPTION"
.PP

\fBgfservice\fR
は、設定をファイルから読み込みます。 (\fBgfservice\-agent\fR
は設定ファイルを読みません。)
.PP
設定ファイルはそれ自体が、Bourne シェルスクリプトになっています。 ファイルは、\fBgfservice\fR
によって
\fIスクリプトとして評価されます。\fR
以下に、設定ファイルの記述例を示します。
.sp
.if n \{\
.RS 4
.\}
.nf
	# gfmd サーバー
	gfmd1=db1\&.example\&.com
	gfmd2=db2\&.example\&.com
.fi
.if n \{\
.RE
.\}
.PP
Bourne シェルと同様に、「#」で始まる行や空行は無視されます。 それ以外の行では、シェル変数を宣言します。 この例では、変数
\fIgfmd1\fR
を
\fIdb1\&.example\&.com\fR
という値にセットし、 変数
\fIgfmd2\fR
には
\fIdb12\&.example\&.com\fR
という値をそれぞれセット しています。 「=」の前後に空白文字を置くことはできないので、注意して下さい。
.PP
変数
\fIgfmd1\fR
と
\fIgfmd2\fR
は「ホスト ID」として使用します。
\fBgfservice\fR
では、ホストを指定する際にホスト名ではなく、 ホスト IDを使用します。
.sp
.if n \{\
.RS 4
.\}
.nf
	\fBgfservice \fR\fB\fIstart\-gfmd\fR\fR\fB \fR\fB\fIgfmd2\fR\fR
.fi
.if n \{\
.RE
.\}
.PP
上記のコマンドを実行すると、\fBgfservice\fR
はサーバー
\fIgfmd2\fR
、つまり metadb2\&.example\&.com 上の gfmd を起動します。 ホスト ID の末尾の数は 1 から、連続して割り当てなくてはなりません。
.PP
gfsd サーバーとクライアントホストを指定するには、ホスト ID 「gfs\fIn\fR」と「client\fIn\fR」 をそれぞれ使用します。
.sp
.if n \{\
.RS 4
.\}
.nf
	# gfsd サーバー
	gfsd1=fs1\&.example\&.com

	# クライアント
	client1=pc1\&.example\&.com
	client2=pc2\&.example\&.com
	client3=pc2\&.example\&.com
.fi
.if n \{\
.RE
.\}
.PP
ホスト ID 変数に加え、\fBgfservice\fR
はホスト ID に関連する 変数をいくつか認識します。
.sp
.if n \{\
.RS 4
.\}
.nf
	# gfmd1 に関する設定
	gfmd1_CONFIG_GFARM_OPTIONS="\-X \-A $LOGNAME"
	gfmd1_SSH="ssh \-i $HOME/\&.ssh/id_rsa_gfservice"
	gfmd1_SUDO=/usr/local/bin/sudo
.fi
.if n \{\
.RE
.\}
.PP
この例で示しているように、空白文字を含む値をセットするには、引用符を使用 します。
\fI$VARNAME\fR
は、シェル変数もしくは環境変数
\fIVARNAME\fR
の値に展開されます。
.SH "VARIABLES ABOUT GFMD"
.PP
変数「gfmd\fIn\fR」(gfmd1, gfmd2, \&.\&.\&.) は、gfmd サーバーを定義するために用います。 名前が「gfmd\fIn\fR_」で始まる変数 (たとえば
\fIgfmd1_SSH\fR) は、対応する 「gfmd\fIn\fR」サーバーの設定パラメタをセットするため に用います。
\fBgfservice\fR
が現在のところ認識する変数は、以下の通りです。
.PP
\fIgfmd\fR\fI\fIn\fR\fR
.RS 4
gfmd サーバーを登録します。 変数の値は、サーバーホストのホスト名 (もしくは IP アドレス) を表します。
\fBgfservice\fR
は、この値を SSH 接続先ホストとしてしか 使用しないので注意して下さい。 Gfarm システム内で使用されるホスト名を指定するには、代わりに
\fIgfmd\fR\fI\fIn\fR\fR\fI_CONFIG_GFARM_OPTOINS\fR
という変数の中で、\fB\-h\fR
オプションを使用して下さい。
.sp
.if n \{\
.RS 4
.\}
.nf
	gfmd1=md1\-ctl\&.example\&.org
	gfmd1_CONFIG_GFARM_OPTIONS="\-h md1\&.example\&.org"
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_GFBINDIR\fR
.RS 4
gfmd サーバー上で
\fBgfservice\-agent\fR
コマンドが インストールされているディレクトリへのパスを指定します。 この変数が宣言されていると
\fBgfservice\fR
は、 「\fB\fI$gfmd\fR\fI\fIn\fR\fR\fI_GFBINDIR\fR\fR\fB/gfservice\-agent\fR」を実行します。 宣言されていない場合は、「\fBgfservice\-agent\fR」を実行します。
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_CONFIG_GFARM_OPTIONS\fR
.RS 4

\fBconfig\-gfarm\fR
コマンドのオプションを指定します。 デフォルト値は、空文字列 (オプションなし) です。
\fBgfservice\fR
は
\fBconfig\-gfarm\fR
サブコマンド およびその他多くのサブコマンドを実行する際に、この変数を参照します。
\fBconfig\-gfarm\fR
が完了した後であっても、この変数の宣言を 削除したり、編集したりはしないで下さい。
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_PRIVATE_MODE\fR
.RS 4
リモートホスト上の gfmd をプライベートモードで動作させる場合は、この 変数に「true」をセットします。
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_AUTH_TYPE\fR
.RS 4
認証タイプ ("sharedsecret", "gsi", "gsi_auth" のいずれか) を指定します。 この変数が定義されていない場合は、gfmd1 上で
\fBconfig\-gfarm\fR
を実行したときの
\fIAUTH_TYPE\fR
の値が採用されます。 (変数
\fIgfmd1_CONFIG_GFARM_OPTIONS\fR
の値によって、この ときの
\fIAUTH_TYPE\fR
の値は変わるので、注意して下さい。)
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_CLUSTER_NAME\fR
.RS 4
gfmd サーバのクラスタ名を指定します。 デフォルトは「」(空文字列) で、これはこのサーバがデフォルトのクラスタに 属することを意味します。
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_SSH\fR
.RS 4
SSH クライアントコマンドのパスおよびオプションを指定します。
\fBgfservice\fR
が gfmd サーバーに接続するために SSH クライアントコマンドを実行する際、この変数が利用されます。 デフォルトは「ssh」です。
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_SUDO\fR
.RS 4
Sudo コマンドのパスおよびオプションを指定します。
\fBgfservice\fR
が SSH を介して gfmd サーバー上で Sudo コマンドを実行する際、この変数が利用されます。 デフォルトは「sudo」です。
.RE
.SH "VARIABLES ABOUT GFSD"
.PP
変数「gfsd\fIn\fR」(gfsd1, gfsd2, \&.\&.\&.) は、gfsd サーバーを定義するために用います。 名前が「gfsd\fIn\fR_」で始まる変数 (たとえば
\fIgfsd1_SSH\fR) は、対応する 「gfsd\fIn\fR」サーバーの設定パラメタをセットするため に用います。
\fBgfservice\fR
が現在のところ認識する変数は、以下の通りです。
.PP
\fIgfsd\fR\fI\fIn\fR\fR
.RS 4
gfsd サーバーを登録します。 変数の値は、サーバーホストのホスト名 (もしくは IP アドレス) を表します。
\fBgfservice\fR
は、この値を SSH 接続先ホストとしてしか 使用しないので注意して下さい。 Gfarm システム内で使用されるホスト名を指定するには、代わりに
\fIgfsd\fR\fI\fIn\fR\fR\fI_CONFIG_GFSD_OPTOINS\fR
という変数の中で、\fB\-h\fR
オプションを使用して下さい。
.sp
.if n \{\
.RS 4
.\}
.nf
	gfsd1=fs2\-ctl\&.example\&.org
	gfsd1_CONFIG_GFSD_OPTIONS="\-h fs2\&.example\&.org"
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fIgfsd\fR\fI\fIn\fR\fR\fI_GFBINDIR\fR
.RS 4
gfsd サーバー上で
\fBgfservice\-agent\fR
コマンドが インストールされているディレクトリへのパスを指定します。 この変数が宣言されていると
\fBgfservice\fR
は、 「\fB\fI$gfsd\fR\fI\fIn\fR\fR\fI_GFBINDIR\fR\fR\fB/gfservice\-agent\fR」を実行します。 宣言されていない場合は、「\fBgfservice\-agent\fR」を実行します。
.RE
.PP
\fIgfsd\fR\fI\fIn\fR\fR\fI_CONFIG_GFSD_OPTIONS\fR
.RS 4

\fBconfig\-gfsd\fR
コマンドのオプションを指定します。 デフォルト値は、空文字列 (オプションなし) です。
\fBgfservice\fR
は
\fBconfig\-gfsd\fR
サブコマンド およびその他多くのサブコマンドを実行する際に、この変数を参照します。
\fBconfig\-gfsd\fR
が完了した後であっても、この変数の宣言を 削除したり、編集したりはしないで下さい。
.RE
.PP
\fIgfsd\fR\fI\fIn\fR\fR\fI_PRIVATE_MODE\fR
.RS 4
リモートホスト上の gfsd をプライベートモードで動作させる場合は、この 変数に「true」をセットします。
.RE
.PP
\fIgfsd\fR\fI\fIn\fR\fR\fI_AUTH_TYPE\fR
.RS 4
認証タイプ ("sharedsecret", "gsi", "gsi_auth" のいずれか) を指定します。 この変数が定義されていない場合は、gfmd1 上で
\fBconfig\-gfarm\fR
を実行したときの
\fIAUTH_TYPE\fR
の値が採用されます。 (変数
\fIgfmd1_CONFIG_GFARM_OPTIONS\fR
の値によって、この ときの
\fIAUTH_TYPE\fR
の値は変わるので、注意して下さい。)
.RE
.PP
\fIgfsd\fR\fI\fIn\fR\fR\fI_SSH\fR
.RS 4
SSH クライアントコマンドのパスおよびオプションを指定します。
\fBgfservice\fR
が gfsd サーバーに接続するために SSH クライアントコマンド実行する際、この変数が利用されます。 デフォルトは「ssh」です。
.RE
.PP
\fIgfsd\fR\fI\fIn\fR\fR\fI_SUDO\fR
.RS 4
Sudo コマンドのパスおよびオプションを指定します。
\fBgfservice\fR
が SSH を介して gfsd サーバー上で Sudo コマンドを実行する際、この変数が利用されます。 デフォルトは「sudo」です。
.RE
.SH "VARIABLES ABOUT CLIENT"
.PP
変数「client\fIn\fR」(client1, client2, \&.\&.\&.) は、 client サーバーを定義するために用います。 名前が「client\fIn\fR_」で始まる変数 (たとえば
\fIclient1_SSH\fR) は、対応する 「client\fIn\fR」サーバーの設定パラメタをセットする ために用います。
\fBgfservice\fR
が現在のところ認識する変数は、以下の通りです。
.PP
\fIclient\fR\fI\fIn\fR\fR
.RS 4
クライアントホストを登録します。 変数の値は、クライアントホストのホスト名 (もしくは IP アドレス) を 表します。
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_GFBINDIR\fR
.RS 4
クライアントホスト上で
\fBgfservice\-agent\fR
コマンドが インストールされているディレクトリへのパスを指定します。 この変数が宣言されていると
\fBgfservice\fR
は、 「\fB\fI$client\fR\fI\fIn\fR\fR\fI_GFBINDIR\fR\fR\fB/gfservice\-agent\fR」を実行します。 宣言されていない場合は、「\fBgfservice\-agent\fR」を実行します。
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_MOUNT_GFARM2FS\fR
.RS 4

\fBmount\&.gfarm2fs\fR
コマンドのパスおよび オプションを指定します。
\fBgfservice\fR
がクライアントホスト上で
\fBmount\&.gfarm2fs\fR
コマンドを実行してファイルシステムを マウントする際、この変数が利用されます。 デフォルトは「%%BINDIR%%/mount\&.gfarm2fs」です。
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_UMOUNT_GFARM2FS\fR
.RS 4

\fBumount\&.gfarm2fs\fR
コマンドのパスおよび オプションを指定します。
\fBgfservice\fR
がクライアントホスト上で
\fBumount\&.gfarm2fs\fR
コマンドを実行してファイルシステムを アンマウントする際、この変数が利用されます。 デフォルトは「%%BINDIR%%/umount\&.gfarm2fs」です。
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_SSH\fR
.RS 4
SSH クライアントコマンドのパスおよびオプションを指定します。
\fBgfservice\fR
がクライアントホストに接続するために SSH クライアントコマンド実行する際、この変数が利用されます。 デフォルトは「ssh」です。
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_SUDO\fR
.RS 4
Sudo コマンドのパスおよびオプションを指定します。
\fBgfservice\fR
が SSH を介してクライアントホスト上で Sudo コマンドを実行する際、この変数が利用されます。 デフォルトは「sudo」です。
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_GFARM_CONF\fR
.RS 4
gfarm2\&.confファイルのパスを絶対パスで指定します。 この値が設定されていない場合、\fBgfservice\fRはgfmd1の gfarm2\&.confファイルのパスと同じパスを使用します(gfarm2\&.confファイルの パスは「gfmd1_CONFIG_GFARM_OPTIONS」シェル変数の値を基に決定されます)。
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_PRIVATE_MODE\fR
.RS 4
この変数に「true」をセットすると、\fBgfservice\fR
が サブコマンド
\fBconfig\-client\fR
を実行する際、クライアント ホスト側の処理は root 権限を持たずに行います。
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_AUTH_TYPE\fR
.RS 4
認証タイプ ("sharedsecret", "gsi", "gsi_auth" のいずれか) を指定します。 この変数が定義されていない場合は、gfmd1 上で
\fBconfig\-gfarm\fR
を実行したときの
\fIAUTH_TYPE\fR
の値が採用されます。 (変数
\fIgfmd1_CONFIG_GFARM_OPTIONS\fR
の値によって、この ときの
\fIAUTH_TYPE\fR
の値は変わるので、注意して下さい。)
.RE
