# $Id$

top_builddir = ../../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

datadir=$(default_htmldir)/pic

DATA = $(srcdir)/Gfarm_logo_tate_color.svg

include $(top_srcdir)/makes/data.mk
