# $Id$

top_builddir = ../../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

htmldir=$(default_htmldir)/pic

HTML =	gfarm-logo.gif

include $(top_srcdir)/makes/html.mk
