'\" t
.\"     Title: gfarm2.conf
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 27 Aug 2015
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFARM2\&.CONF" "5" "27 Aug 2015" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfarm2.conf \- Gfarm configuration file
.SH "DESCRIPTION"
.PP
gfarm2\&.conf is a text file that contains a Gfarm configuration\&. Gfarm server processes gfmd and gfsd refer to %%SYSCONFDIR%%/gfmd\&.conf and %%SYSCONFDIR%%/gfarm2\&.conf, respectively, by default\&. Since this configuration file is only read at startup, it is necessary to restart servers when the contents of the configuration file are updated\&.
.PP
Application programs, such as gfls and gfhost, refer to both %%SYSCONFDIR%%/gfarm2\&.conf, and a file specified by an environment variable, GFARM_CONFIG_FILE\&. If both configuration files exist, the file specified by the environment variable, GFARM_CONFIG_FILE, is read first\&. Both files have the same grammar\&. If the environment variable GFARM_CONFIG_FILE doesn\*(Aqt exist, ~/\&.gfarm2rc in a user\*(Aqs home directory is used instead\&.
.PP
Each line of gfarm2\&.conf consists of one statement\&. When the line ends with the character ``\e\*(Aq\*(Aq, the line continues for the next line\&. A word beginning with ``#\*(Aq\*(Aq causes that word and all remaining characters on that line to be ignored\&.
.SH "HOST_SPECIFICATION"
.PP
\fIHost_specification\fR
has the following forms\&.
.PP
\fIIII\&.JJJ\&.KKK\&.LLL\fR
.RS 4
Specifies an IP address with four octets from 0 to 255, separated by "\&."\&.
.RE
.PP
\fIIII\&.JJJ\&.KKK\&.LLL\fR/\fIMM\fR
.RS 4
Specifies a network address with an IP address and a netmask from 0 to 31 separated by "/"\&.
.RE
.PP
\fIdomain\&.name\fR
.RS 4
Specifies a host name\&.
.RE
.PP
\fI\&.domain\&.name\fR
.RS 4
Specifies all hosts which belong to the domain\&.name\&.
.RE
.PP
\fI*\fR
.RS 4
Specifies all hosts\&.
.RE
.SH "STATEMENT"
.PP
The following statements are supported\&.
.PP
spool \fIdirectory\fR
.RS 4
The
spool
statement specifies a spool directory for a Gfarm filesystem on this filesystem node\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	spool /var/spool/gfarm
.fi
.if n \{\
.RE
.\}
.RE
.PP
spool_server_listen_address \fIIP\-address\fR
.RS 4
The
spool_server_listen_address
statement specifies the IP address at which the gfsd accepts TCP and UDP requests\&. The default address is all IP addresses of the host\&. This option is useful when one wants to invoke multiple gfsd to provide multiple spool directories on the host\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	spool_server_listen_address 192\&.168\&.121\&.1
.fi
.if n \{\
.RE
.\}
.RE
.PP
spool_server_listen_backlog \fInumber\fR
.RS 4
This statement specifies the second parameter of the
\fBlisten\fR(2)
system call that gfsd invokes\&. The default value is SOMAXCONN (typically 128, but depends on the OS) on OSes which define this symbol in <sys/socket\&.h>, or 5 if it\*(Aqs undefined\&.
.sp
On an environment which has many gfarm clients, it\*(Aqs recommened to increase this value after increasing system limit\&.
.sp
This parameter is only available in gfarm2\&.conf, and ignored in gfmd\&.conf\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	spool_server_listen_backlog 128
.fi
.if n \{\
.RE
.\}
.RE
.PP
spool_server_cred_type \fIcred_type\fR
.RS 4
This statement specifies the type of credential used by gfsd for GSI authentication\&. This is ignored when you are using
sharedsecret
authentication\&.
.sp
If this statement isn\*(Aqt used on the server side, the server uses a host certificate, if the server is invoked with root privileges\&. Or, if the server is invoked as a non\-privileged user, the server uses the user\*(Aqs certificate\&.
.sp
If this statement isn\*(Aqt used on the client side, the client assumes that the server that the client is going to connect is using a host certificate of the server host\&. Thus, if the server is not invoked with root privileges, but invoked with user privileges where the user is the same as the user who invoked the client, the client side needs to specify the following one line\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	spool_server_cred_type self
.fi
.if n \{\
.RE
.\}
.sp
The possible types of
\fIcred_type\fR
are ``self\*(Aq\*(Aq, ``host\*(Aq\*(Aq, ``user\*(Aq\*(Aq and ``mechanism\-specific\*(Aq\*(Aq\&. And those are used with the
spool_server_cred_service
and
spool_server_cred_name
statements as follows:
.PP
self
.RS 4
This keyword specifies that the certificate that the user currently has is used\&. You must not use either the
spool_server_cred_service
or
spool_server_cred_name
statement, if you are using this type\&.
.RE
.PP
host
.RS 4
This keyword specifies that a host certificate or a service certificate is used\&. To choose a service certificate, the name of the service may be specified by the
spool_server_cred_service
statement\&. If ``host\*(Aq\*(Aq is specified as the service name, a host certificate in the file ``/etc/grid\-security/hostcert\&.pem\*(Aq\*(Aq will be used\&. If any server name other than ``host\*(Aq\*(Aq is specified, a service certificate in the file ``/etc/grid\-security/SERVICE/SERVICEcert\&.pem\*(Aq\*(Aq will be used\&. If the service name is omitted, ``host\*(Aq\*(Aq will be used as the service name by default\&. Only the Common Name field of a certificate will be used to check the server\*(Aqs identity for both a host certificate and a service certificate\&. And the Common Name field must be in the ``CN=SERVERNAME/HOSTNAME\*(Aq\*(Aq format\&. Also, the hostname must match the canonical name configured by the
\fBgfhost\fR
command exactly\&. Alias hostnames are not allowed\&.
.sp
This feature corresponds to the GSS_C_NT_HOSTBASED_SERVICE feature in GSSAPI (RFC2743/RFC2744)\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	spool_server_cred_type host
	spool_server_cred_service host
.fi
.if n \{\
.RE
.\}
.RE
.PP
user
.RS 4
This keyword specifies that a user certificate is used\&. The account name of the user may be specified by the
spool_server_cred_name
statement\&. If the account name is omitted, the user who invoked the command will be used by default\&. You must not specify a service name using the
spool_server_cred_service
statement, if you are using a user certificate\&.
.sp
To map from the account name to a Distinguished Name of a certificate, file ``/etc/grid\-security/grid\-mapfile\*(Aq\*(Aq is used\&. Thus, if there isn\*(Aqt such a file, or if the user isn\*(Aqt specified in this file, this feature cannot be used\&.
.sp
This feature corresponds to the GSS_C_NT_USER_NAME feature in GSSAPI (RFC2743/RFC2744)\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	spool_server_cred_type user
	spool_server_cred_name guest
.fi
.if n \{\
.RE
.\}
.RE
.PP
mechanism\-specific
.RS 4
This keyword specifies that
spool_server_cred_name
is treated as a raw X\&.509 Distinguished Name serving as a server\*(Aqs certificate\&. You must not specify a service name using a
spool_server_cred_service
statement, if you are using this type\&.
.sp
This feature corresponds to a case where GSS_C_NO_OID is specified as a Name Type in GSSAPI (RFC2743/RFC2744)\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	spool_server_cred_type mechanism\-specific
	spool_server_cred_name "/O=Grid/O=Globus/OU=example\&.com/CN=John Smith"
.fi
.if n \{\
.RE
.\}
.RE
.RE
.PP
spool_server_cred_service \fIcred_service\fR
.RS 4
This statement specifies the service name of a service certificate used by gfsd for GSI authentication, when ``host\*(Aq\*(Aq is specified in
spool_server_cred_type
statement\&. This is ignored when you are using
sharedsecret
authentication\&. Please read the description of the
spool_server_cred_type
statement for details\&.
.RE
.PP
spool_server_cred_name \fIcred_name\fR
.RS 4
This statement specifies the setting of a certificate used by gfsd for GSI authentication\&. What this setting means depends on the type specified in the
spool_server_cred_type
statement\&. This is ignored when you are using
sharedsecret
authentication\&. Please read the description of the
spool_server_cred_type
statement for details\&.
.RE
.PP
spool_check_level \fIlevel\fR
.RS 4
This statement enables the consistency check of files stored in the spool directory at start\-up of gfsd\&. The
\fIlevel\fR
name corresponds how many \-c command\-line options are specified to gfsd, i\&.e\&. the level "display" means the \-c option, "delete" means the \-cc option, and "lost_found" means the \-ccc option, which is the default\&. For detail about the \-c option, refer to the manual page of gfsd(8)\&. The level "disable" disables the consistency check\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	spool_check_level disable
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_server_host \fIhostname\fR
.RS 4
The
metadb_server_host
statement specifies the host name on which gfmd is running\&.
.sp
This statement cannot be omitted\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_server_host ldap\&.example\&.com
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_server_port \fIport\fR
.RS 4
The
metadb_server_port
statement specifies the tcp port number the gfmd is listening on\&. The default port number is 601\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_server_port 601
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_server_cred_type \fIcred_type\fR
.RS 4
This statement specifies the type of credential used by gfmd for GSI authentication\&. This is ignored when you are using
sharedsecret
authentication\&. Please read the description of the
spool_server_cred_type
statement on the configuration of this statement\&.
.RE
.PP
metadb_server_cred_service \fIcred_service\fR
.RS 4
This statement specifies the service name of a service certificate used by gfmd for GSI authentication, when ``host\*(Aq\*(Aq is specified in
metadb_server_cred_type
statement\&. This is ignored when you are using
sharedsecret
authentication\&. Please read the description of the
spool_server_cred_type
statement on the configuration of this statement\&.
.RE
.PP
metadb_server_cred_name \fIcred_name\fR
.RS 4
This statement specifies the setting of a certificate used by gfmd for GSI authentication\&. What this setting means depends on the type specified in the
metadb_server_cred_type
statement\&. This is ignored when you are using
sharedsecret
authentication\&. Please read the description of the
spool_server_cred_type
statement on the configuration of this statement\&.
.RE
.PP
metadb_server_listen_backlog \fInumber\fR
.RS 4
This statement specifies the second parameter of the
\fBlisten\fR(2)
system call that gfmd invokes\&. The default value is SOMAXCONN (typically 128, but depends on the OS) on OSes which define this symbol in <sys/socket\&.h>, or 5 if it\*(Aqs undefined\&.
.sp
This parameter is only available in gfmd\&.conf, and ignored in gfarm2\&.conf\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_server_listen_backlog 128
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_server_max_descriptors \fInumber\fR
.RS 4
This directive specifies the number of file descriptor limit for the gfmd metadata server process\&. If not specified, the default limit is min(OS\*(Aqs hard limit, 131072)\&. You may have to increase this value on a larger configuration, or decrease on a smaller configuration\&. See Gfarm FAQ to see how to calculate this value\&.
.sp
This parameter is only available in gfmd\&.conf, and ignored in gfarm2\&.conf\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_server_max_descriptors 262144
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_server_stack_size \fIbytes\fR
.RS 4
This directive specifies the size of each thread in the gfmd metadata server process\&. If not specified, the default size of the OS is used\&. This parameter is used to cut down the size of virtual memory space used by gfmd\&.
.sp
For example, the default stack size on CentOS 5/i386 is 10MB, thus, you can decrease the size of the virtual memory space of gfmd to 1/40, by specifying 256KB as this parameter\&.
.sp
This parameter is only available in gfmd\&.conf, and ignored in gfarm2\&.conf\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_server_stack_size 262144
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_server_thread_pool_size \fIsize\fR
.RS 4
This directive specifies the maximum number of threads in a thread pool in the gfmd\&. It is effective to specify around the number of CPU cores of the metadata server node\&. Default is 16\&.
.sp
This parameter is only available in gfmd\&.conf, and ignored in gfarm2\&.conf\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_server_thread_pool_size 16
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_server_job_queue_length \fIlength\fR
.RS 4
This directive specifies the length of job queue in the gfmd\&. It is effective to specify around the maximum number of clients that access the Gfarm file system at the same time\&. Default is 16000\&.
.sp
This parameter is only available in gfmd\&.conf, and ignored in gfarm2\&.conf\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_server_job_queue_length 160
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_server_heartbeat_interval \fIseconds\fR
.RS 4
This directive specifies the interval of heartbeat in seconds for gfmd to check availability of each gfsd\&. Default is 180 seconds\&.
.sp
Until gfarm\-2\&.3\&.0, this parameter was only available in gfmd\&.conf, and ignored in gfarm2\&.conf\&. But since gfarm\-2\&.4\&.0, gfsd also uses this parameter to detect whether gfmd is down or not, this parameter has to be specified in both gfarm2\&.conf and gfmd\&.conf\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_server_heartbeat_interval 180
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_server_dbq_size \fIsize\fR
.RS 4
This directive specifies the queue length of metadata updates for a backend database in gfmd\&. Longer queue length may avoid slow down due to waiting backend database updates in case of frequent metadata operations\&. Default is 65536\&.
.sp
This parameter is only available in gfmd\&.conf, and ignored in gfarm2\&.conf\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_server_dbq_size 65536
.fi
.if n \{\
.RE
.\}
.RE
.PP
ldap_server_host \fIhostname\fR
.RS 4
The
ldap_server_host
statement specifies the host name on which an LDAP server is running\&. This statement is required when the LDAP server is used for a backend database of gfmd\&. This statement is used in gfmd\&.conf not gfarm2\&.conf\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	ldap_server_host ldap\&.example\&.com
.fi
.if n \{\
.RE
.\}
.RE
.PP
ldap_server_port \fIport\fR
.RS 4
The
ldap_server_port
statement specifies the tcp port number of the LDAP server\&.
.sp
This statement cannot be omitted if
ldap_server_host
is specified\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	ldap_server_port 602
.fi
.if n \{\
.RE
.\}
.RE
.PP
ldap_base_dn \fILDAP_base_distinguished_name\fR
.RS 4
The
ldap_base_dn
statement specifies the base\-distinguished name of the LDAP database\&.
.sp
This statement cannot be omitted if
ldap_server_host
is specified\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	ldap_base_dn "dc=example, dc=com"
.fi
.if n \{\
.RE
.\}
.RE
.PP
ldap_bind_dn \fILDAP_bind_distinguished_name\fR
.RS 4
The
ldap_bind_dn
statement specifies the distinguished name for the bind operation which is used for authentication to the LDAP database\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	ldap_bind_dn "cn=gfarmuser, dc=example, dc=com"
.fi
.if n \{\
.RE
.\}
.RE
.PP
ldap_bind_password \fIpassword\fR
.RS 4
The
ldap_bind_password
statement specifies the password for the bind operation which is used for authentication to the LDAP database\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	ldap_bind_password "secret\-ldap\-password"
.fi
.if n \{\
.RE
.\}
.RE
.PP
postgresql_server_host \fIhostname\fR
.RS 4
The
postgresql_server_host
statement specifies the host name on which a PostgreSQL server is running\&. This statement is required when the PostgreSQL server is used for a backend database of gfmd\&. This statement is used in gfmd\&.conf not gfarm2\&.conf\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	postgresql_server_host postgresql\&.example\&.com
.fi
.if n \{\
.RE
.\}
.RE
.PP
postgresql_server_port \fIport\fR
.RS 4
The
postgresql_server_port
statement specifies the tcp port number of the PostgreSQL server\&.
.sp
This statement cannot be omitted if
postgresql_server_host
is specified\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	postgresql_server_port 602
.fi
.if n \{\
.RE
.\}
.RE
.PP
postgresql_dbname \fIdbname\fR
.RS 4
The
postgresql_dbname
statement specifies the database name of the PostgreSQL database\&.
.sp
This statement cannot be omitted if
postgresql_server_host
is specified\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	postgresql_dbname gfarm
.fi
.if n \{\
.RE
.\}
.RE
.PP
postgresql_user \fIuser\fR
.RS 4
The
postgresql_user
statement specifies the username used to connect the PostgreSQL database\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	postgresql_user gfarm
.fi
.if n \{\
.RE
.\}
.RE
.PP
postgresql_password \fIpassword\fR
.RS 4
The
postgresql_password
statement specifies the password used to connect the PostgreSQL database\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	postgresql_password gfarm
.fi
.if n \{\
.RE
.\}
.RE
.PP
postgresql_conninfo \fIconnection_info\fR
.RS 4
The
postgresql_conninfo
statement specifies the connection option used to connect the PostgreSQL database\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	postgresql_conninfo "sslmode=require connect_timeout=30"
.fi
.if n \{\
.RE
.\}
.RE
.PP
auth \fIvalidity\fR \fImethod\fR \fIHost_specification\fR
.RS 4
This statement specifies the authentication method when communicating with the host(s) specified by the third argument\&.
.sp
The first argument should be either the
enable
or
disable
keyword\&. The second argument,
\fIauth method\fR, should be the
gsi,
gsi_auth, or
sharedsecret
keyword\&. The third argument specifies the host(s) by using
\fIHost specification\fR\&.
.sp
The
auth
statement may be specified any number of times\&. For each authentication method, it becomes a candidate when the first entry whose host_specification matches the target host has the
enable
keyword\&. When there is no corresponding entry, or when the first corresponding entry has the
disable
keyword, the authentication method does not become a candidate\&.
.sp
This process takes place on both client and server sides\&. Candidates for authentication method on both sides will be tried\&.
.sp
The order of statements with different authentication methods is not relevant\&. When there are several candidates for the authentication method for the host, the order of the authentication trial is
sharedsecret,
gsi_auth, and then
gsi\&.
.sp
The GSI methods are available if and only if the \-\-with\-globus option is specified at configuration\&. When the methods are not available, an
auth
statement with
gsi
or
gsi_auth
will be ignored\&.
.sp
This statement cannot be omitted\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	auth disable sharedsecret 192\&.168\&.0\&.100
	auth disable sharedsecret 192\&.168\&.0\&.101
	auth enable sharedsecret 192\&.168\&.0\&.0/24
	auth enable gsi_auth 10\&.0\&.0\&.0/8
	auth enable gsi *
.fi
.if n \{\
.RE
.\}
.sp
In this example, all hosts which belong to the network address 192\&.168\&.0\&.0/24, except for two hosts, 192\&.168\&.0\&.100 and 192\&.168\&.0\&.101, will be tested for authenticated by both
sharedsecret
and
gsi; all hosts which belong to the network address 10\&.0\&.0\&.0/8 will be tested for authentication by both
gsi_auth
and
gsi; and all other hosts will be authenticated by
gsi\&. Note that two hosts, 192\&.168\&.0\&.100 and 192\&.168\&.0\&.101, will be tested for authentication by gsi only\&.
.RE
.PP
sockopt \fIoption\fR\fI[=\fR\fIvalue\fR\fI] [\fR\fILISTENER\fR\fI | \fR\fI\fIHost_specification\fR\fR\fI]\fR
.RS 4
The
sockopt
parameter specifies the socket option
\fIoption\fR
via the setsockopt(2) system call\&.
.sp
When
LISTENER
(all capital letters) is specified by the second argument, the socket option is applied to any socket on the server side (accepting side)\&.
.sp
When the host_specification is specified by the second argument, the socket option is applied to sockets that connect to the specified host(s)\&. If the second argument is "*", the socket option is applied to any hosts on the client side (connecting side)\&.
.sp
If the second argument is omitted, the socket option is applied to every socket\&.
.sp
The following socket options can be specified\&.
.sp
debug\&. The
\fBSO_DEBUG\fR
socket option is specified\&. A
\fIvalue\fR
is not necessary\&.
.sp
keepalive\&. The
\fBSO_KEEPALIVE\fR
socket option is specified\&. A
\fIvalue\fR
is not necessary\&.
.sp
sndbuf\&. The
\fBSO_SNDBUF\fR
socket option is specified with a
\fIvalue\fR\&.
.sp
rcvbuf\&. The
\fBSO_RCVBUF\fR
socket option is specified with a
\fIvalue\fR\&.
.sp
tcp_nodelay\&. The
\fBTCP_NODELAY\fR
socket option is specified\&. A
\fIvalue\fR
is not necessary\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	sockopt tcp_nodelay 192\&.168\&.0\&.0/24
	sockopt sndbuf=1048576 10\&.0\&.0\&.0/8
	sockopt sndbuf=1048576 LISTENER
	sockopt rcvbuf=1048576 10\&.0\&.0\&.0/8
	sockopt rcvbuf=1048576 LISTENER
.fi
.if n \{\
.RE
.\}
.RE
.PP
known_network \fIHost_specification\fR
.RS 4
The
known_network
statement specifies a network address for file system nodes\&. It is used to group file system nodes at file systen node scheduling\&. File system nodes that are not specified in this directive are assumed to be in an IPv4 class C network\&.
.sp
Multiple networks can be specified as follows\&.
.sp
.if n \{\
.RS 4
.\}
.nf
	known_network 192\&.168\&.0\&.0/25
	known_network 192\&.168\&.0\&.128/25
.fi
.if n \{\
.RE
.\}
.RE
.PP
network_receive_timeout \fIseconds\fR
.RS 4
The
network_receive_timeout
directive specifies the time, in seconds, to wait for data reception via network\&. The default value is 60 seconds\&. This directive is effective in both gfarm2\&.conf and gfmd\&.conf\&.
.sp
When a Gfarm application program receives no data from a gfsd filesystem server during the timeout period, it aborts the communication with the server, and then it tries to communicate with another server to continue the operation\&.
.sp
When a gfmd metadata server receives no data from a gfsd filesystem server during the timeout period, it aborts the communication with the gfsd server and gfmd considers the gfsd server is down\&.
.RE
.PP
admin_user \fIuser\fR
.RS 4
This directive specifies an administrator user name, which is specified in gfmd\&.conf\&.
.RE
.PP
admin_user_gsi_dn \fIuser_gsi_dn\fR
.RS 4
This directive specifies a subject DN of an administrator, which is specified in gfmd\&.conf\&.
.RE
.PP
local_user_map \fIuser\-map\-file\fR [\fIhostname\fR:[\fIport\fR]]
.RS 4
This directive specifies a file name
\fIuser\-map\-file\fR
for mapping local user names to global user names\&. This map file is used only for sharedsecret authentication\&. When this file is not specified, a global user name is assumed to be same as the local user name\&.
.sp
\fIuser\-map\-file\fR
is needed when you have to use the sharedsecret authentication method in the case where you have different unix account names on different filesystem nodes\&. In such a case, the
\fIuser\-map\-file\fR
on each filesystem node should have an entry from each local user name to a unique global user name\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	local_user_map /etc/gfarm/gfarm\-usermap
.fi
.if n \{\
.RE
.\}
.sp
Each line of the
\fIuser\-map\-file\fR
consists of two fields separated by spaces; the first field is a global user name, and the second field is a local user name\&.
.sp
Example of the user mapping file:
.sp
.if n \{\
.RS 4
.\}
.nf
	foobar foo
	quux baz
.fi
.if n \{\
.RE
.\}
.sp
According to the first line of this mapping file, a global user name, "foobar", is mapped to a local user name, "foo", on this node\&.
.sp
When hostname/port of the meta data server is specified, user mapping files different in each server are applied\&. When the port is omitted, default port (601) is used\&. local_user_map can be specified two or more times\&. When the same definitions of local user name exist, the first definition is selected\&.
.sp
Example of multiple user mapping file:
.sp
.if n \{\
.RS 4
.\}
.nf
	local_user_map /etc/gfarm/gfarm\-usermap1\-1
	local_user_map /etc/gfarm/gfarm\-usermap1\-2
	local_user_map /etc/gfarm/gfarm\-usermap2\-1 server2
	local_user_map /etc/gfarm/gfarm\-usermap2\-2 server2
.fi
.if n \{\
.RE
.\}
.sp
In this example, when connecting to server2, it applies in order of gfarm\-usermap2\-1 and gfarm\-usermap2\-2\&. When connecting to excluding server2, it applies in order of gfarm\-usermap1\-1 and gfarm\-usermap1\-2\&.
.RE
.PP
local_group_map \fIgroup\-map\-file\fR [\fIhostname\fR:[\fIport\fR]]
.RS 4
This directive specifies a file name
\fIgroup\-map\-file\fR
for mapping global group names to local group names\&. This map file is used by legacy clients that use local group id such as gfarm2fs and gfarm dsi for Globus GridFTP to display mapped local groups\&. When this file is not specified, a local group name is assumed to be same as the global group name\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	local_group_map /etc/gfarm/gfarm\-groupmap
.fi
.if n \{\
.RE
.\}
.sp
Each line of the
\fIgroup\-map\-file\fR
consists of two fields separated by spaces; the first field is a global group name, and the second field is a local group name\&.
.sp
When hostname/port of the meta data server is specified, group mapping files different in each server are applied\&. The specification method is similar to local_user_map\&.
.RE
.PP
schedule_cache_timeout \fIseconds\fR
.RS 4
This directive specifies the time (in seconds) until the cache used for filesystem node scheduling expires\&. The cache holds information on each filesystem node, e\&.g\&. load average, disk free space, and whether authentication succeeds or not\&. The default time is 600 seconds, i\&.e\&. ten minutes\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	schedule_cache_timeout 60
.fi
.if n \{\
.RE
.\}
.RE
.PP
schedule_concurrency \fInumber\fR
.RS 4
This directive specifies the number how many filesystem nodes will be searched concurrently at filesystem scheduling\&. If this parameter is increased, the scheduling will finish quicker, but the load to filesystem nodes will increase\&. The default number is 10 nodes\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	schedule_concurrency 10
.fi
.if n \{\
.RE
.\}
.RE
.PP
schedule_concurrency_per_net \fInumber\fR
.RS 4
This directive specifies the number how many filesystem nodes will be used in same network at measuring network latency for each network of filesystem nodes\&. It may be better to increase this parameter, if many filesystem nodes are stopping, or many filesystem nodes are under higher load\&. If this parameter is increased, it\*(Aqs recommened to increase schedule_concurrency parameter too\&. The default number is 3\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	schedule_concurrency_per_net 3
.fi
.if n \{\
.RE
.\}
.RE
.PP
schedule_idle_load_thresh \fIload\-average\fR
.RS 4
This directive specifies the threshold of CPU load average to be considered idle\&. The file system nodes whose CPU load average is equal to or below the specified CPU load average are to be scheduled at first\&. The default load average is 0\&.1\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	schedule_idle_load_thresh 0\&.1
.fi
.if n \{\
.RE
.\}
.RE
.PP
schedule_busy_load_thresh \fIload\-average\fR
.RS 4
This directive specifies the threshold of CPU load average to be considered busy\&. The file system nodes whose CPU load average is above the specified CPU load average are to be scheduled lastly\&. The default load average is 0\&.5\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	schedule_busy_load_thresh 0\&.5
.fi
.if n \{\
.RE
.\}
.RE
.PP
schedule_virtual_load \fIload\-average\fR
.RS 4
This directive specifies the virtual CPU load average\&. The virtual CPU load is added when the host is scheduled to avoid scheduling the same host multiple times\&. The default load average is 0\&.3\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	schedule_virtual_load 0\&.3
.fi
.if n \{\
.RE
.\}
.RE
.PP
schedule_candidates_ratio \fIratio\fR
.RS 4
This parameter specifies the threshold ratio of number of filesystem nodes from number of scheduling nodes, to decide to discontinue to search more filesystem nodes which load averages are less or equal to the schedule_busy_load_thresh parameter\&. If this parameter is increased, the accuracy of scheduling will be increased, but scheduling process will become slower\&. The default ratio is 4\&.0\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	schedule_candidates_ratio 4\&.0
.fi
.if n \{\
.RE
.\}
.RE
.PP
schedule_rtt_thresh_diff \fImicroseconds\fR
.RS 4
This parameter specifies the threshold time of network latency which divides the domains of scheduling priority\&. If a network latency difference from nearer network is larger than this value, the network\*(Aqs scheduling priority is lowered\&. There is a similar parameter schedule_rtt_thresh_ratio, and the scheduling priority is lowered if the network latency exceeds one of the parameters\&. The default is 1000 microseconds\&. i\&.e\&. 1 millisecond\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	schedule_rtt_thresh_diff 1000
.fi
.if n \{\
.RE
.\}
.RE
.PP
schedule_rtt_thresh_ratio \fIratio\fR
.RS 4
This parameter specifies the threshold ratio of network latency which divides the domains of scheduling priority\&. If a network latency is larger than this ratio from nearer network, the network\*(Aqs scheduling priority is lowered\&. There is a similar parameter schedule_rtt_thresh_diff, and the scheduling priority is lowered if the network latency exceeds one of the parameters\&. The default ratio is 4\&.0\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	schedule_rtt_thresh_ratio 4\&.0
.fi
.if n \{\
.RE
.\}
.RE
.PP
schedule_rtt_thresh \fIratio\fR
.RS 4
This directive is just an alias of the schedule_rtt_thresh_ratio directive since gfarm\-2\&.5\&.8\&. Please use that directive instead\&. This directive remains for compatibility with older versions\&. The default ratio is 4\&.0\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	schedule_rtt_thresh 4\&.0
.fi
.if n \{\
.RE
.\}
.RE
.PP
write_local_priority \fIvalidity\fR
.RS 4
Gfarm nearly always chooses localhost, when it selects a filesystem node to write a file\&. By specifyng the
disable
keyword in this directive, Gfarm handles localhost the same as other filesystem nodes\&.
The default is
enable\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	write_local_priority disable
.fi
.if n \{\
.RE
.\}
.RE
.PP
write_target_domain \fIdomain\fR
.RS 4
Gfarm tries to choose a filesystem node in the domain specified by this directive, when it selects a node to write a file\&. If there is no suitable node for writing in this domain, or if this directive is not specified, the filesystem node will be chosen from among all nodes\&.
Note that if you specify this directive more than once, only the first one will be used and the others are ignored\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	write_target_domain example\&.org
.fi
.if n \{\
.RE
.\}
.RE
.PP
minimum_free_disk_space \fIbytes\fR
.RS 4
This directive specifies free disk space (in bytes) which is required on filesystem nodes\&. The Gfarm scheduler excludes filesystem nodes which have less free space than this parameter, when it schedules nodes for jobs which may write files\&. The free space value may have a suffix like ``k\*(Aq\*(Aq (kilo bytes), ``M\*(Aq\*(Aq (mega bytes), ``G\*(Aq\*(Aq (giga bytes) and ``T\*(Aq\*(Aq (tera bytes)\&. The default size is 128M bytes\&.
.sp
This directive has to be specified in both gfarm2\&.conf and gfmd\&.conf\&. After restarting the gfmd and the Gfarm client, it is effective\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	minimum_free_disk_space 1G
.fi
.if n \{\
.RE
.\}
.RE
.PP
gfs_proto_fhremove_request_window \fInumber\fR
.RS 4
This directive specifies maximum number of outstanding replica removal requests from gfmd to gfsd\&. The default is 50\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	gfs_proto_fhremove_request_window 50
.fi
.if n \{\
.RE
.\}
.RE
.PP
gfs_proto_replication_request_window \fInumber\fR
.RS 4
This directive specifies maximum number of outstanding gfmd\-initiated replication requests from gfmd to destination\-side gfsd\&. The default is 20\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	gfs_proto_replication_request_window 20
.fi
.if n \{\
.RE
.\}
.RE
.PP
simultaneous_replication_receivers \fInumber\fR
.RS 4
This directive is just an alias of the gfs_proto_replication_request_window directive since gfarm\-2\&.6\&. Please use that directive instead\&. This directive remains for compatibility with older versions\&. The default is 20\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	simultaneous_replication_receivers 20
.fi
.if n \{\
.RE
.\}
.RE
.PP
outstanding_file_replication_limit \fInumber\fR
.RS 4
This directive specifies maximum number of outstanding gfmd\-initiated replication requests in whole system\&. This exists to prevent memory shortage of gfmd\&. The default is 4194304 and this value corresponds to approximately 512MB memory\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	outstanding_file_replication_limit 4194304
.fi
.if n \{\
.RE
.\}
.RE
.PP
gfsd_connection_cache \fInumber\fR
.RS 4
This directive specifies maximum number of cached gfsd connections\&. The default is 16\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	gfsd_connection_cache 32
.fi
.if n \{\
.RE
.\}
.RE
.PP
xmlattr_size_limit \fIbytes\fR
.RS 4
This directive specifies maximum size of XML extended attributes\&. The default is 786432, and numbers greater than 983040 are not allowed\&.
.sp
This parameter is only available in gfmd\&.conf, and ignored in gfarm2\&.conf\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	xmlattr_size_limit 786432
.fi
.if n \{\
.RE
.\}
.RE
.PP
xattr_size_limit \fIbytes\fR
.RS 4
This directive specifies maximum size of extended attributes\&. The default is 65536, and numbers greater than 983040 are not allowed\&.
.sp
This parameter is only available in gfmd\&.conf, and ignored in gfarm2\&.conf\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	xattr_size_limit 65536
.fi
.if n \{\
.RE
.\}
.RE
.PP
attr_cache_limit \fInumber\fR
.RS 4
This directive specifies maximum number of cached attributes in gfarm library\&. The default is 40000\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	attr_cache_limit 100000
.fi
.if n \{\
.RE
.\}
.RE
.PP
attr_cache_timeout \fImilliseconds\fR
.RS 4
This directive specifies maximum time until cached attributes expire in milliseconds\&. The default is 1000, i\&.e\&. 1 second\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	attr_cache_timeout 3600000
.fi
.if n \{\
.RE
.\}
.RE
.PP
page_cache_timeout \fImilliseconds\fR
.RS 4
This directive specifies maximum time until cached pages expire in milliseconds only related to linux kernel driver\&. The default is 1000, i\&.e\&. 1 second\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
        page_cache_timeout 3600000
.fi
.if n \{\
.RE
.\}
.RE
.PP
log_level \fIpriority_level\fR
.RS 4
This directive specifies a level of log priority\&. The log output, which priority is inferior to this level, will not be sent to syslog or standard error\&. The priority levels are "emerg", "alert", "crit", "err", "warning", "notice", "info" and "debug" in highest first order\&. The default level is "info"\&. It\*(Aqs not recommended to specify a level higher or equal to "crit"\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	log_level debug
.fi
.if n \{\
.RE
.\}
.RE
.PP
log_message_verbose_level \fIlevel\fR
.RS 4
This directive specifies how verbose the log message is\&. The default value is 0, which outputs the log message id\&. The level 1 additionally outputs the file name and the line of source code\&. The level 2 additionally outputs the function name\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	log_message_verbose_level 1
.fi
.if n \{\
.RE
.\}
.RE
.PP
log_auth_verbose \fIvalidity\fR
.RS 4
When "enable" is specified, verbose messages about authentication are logged\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	log_auth_verbose enable
.fi
.if n \{\
.RE
.\}
.RE
.PP
file_trace \fIvalidity\fR
.RS 4
When "enable" is specified, an audit log feature for file creation, modification and removal is enabled\&.
.sp
This directive is available in both gfarm2\&.conf and gfmd\&.conf\&.
.sp
Here is an example:
.sp
.if n \{\
.RS 4
.\}
.nf
	file_trace enable
.fi
.if n \{\
.RE
.\}
.RE
.PP
fatal_action \fIaction_name\fR
.RS 4
This parameter specifies the behavior at a fatal error\&. The default action is
\fIbacktrace_and_abort\fR\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	fatal_action backtrace_and_abort
.fi
.if n \{\
.RE
.\}
.sp
The following actions are supported:
.PP
backtrace_and_abort
.RS 4
Print a backtrace, and then call
\fBabort\fR(3)
\&.
.RE
.PP
backtrace_and_exit
.RS 4
Print a backtrace, and then call
\fBexit\fR(3)
\&.
.RE
.PP
abort
.RS 4
Call
\fBabort\fR(3)
\&.
.RE
.PP
exit
.RS 4
Call
\fBexit\fR(3)
\&.
.RE
.RE
.PP
debug_command \fIcommand_line\fR
.RS 4
When a Gfarm application program crashes (received SIGSEGV, SIGBUG, etc\&.), a debug command specified in this directive is executed\&. For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	debug_command env DISPLAY=:0\&.0 xterm \-e gdb %e %p
.fi
.if n \{\
.RE
.\}
.sp
"%e" and "%p" are expanded to an actual program name and a process ID, respectively\&. If you\*(Aqd like to use "%" character itself in the command line, type "%%"\&.
.sp
This directive is available in both gfarm2\&.conf and gfmd\&.conf\&. If this directive is omitted, no debug command is executed\&.
.RE
.PP
no_file_system_node_timeout \fIseconds\fR
.RS 4
If there is no file system node available, Gfarm client library periodically tries to find a file system node\&. This directive specifies the timeout to try in seconds\&. The default is 30 seconds\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	no_file_system_node_timeout 30
.fi
.if n \{\
.RE
.\}
.RE
.PP
gfmd_reconnection_timeout \fIseconds\fR
.RS 4
If the connection to the metadata server is disconnected, Gfarm client library periodically tries to reconnect\&. This directive specifies the timeout to try in seconds\&. The default is 30 seconds\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	gfmd_reconnection_timeout 30
.fi
.if n \{\
.RE
.\}
.RE
.PP
atime \fItype\fR
.RS 4
When "disable" is specified, atime (access time) is not updated\&. When "relative" is specified, atime is only updated if the previous atime is earlier than the current mtime (modify time) or ctime (change time), or if the previous atime is more than 1 day old\&. When "strict" is specified, atime is always updated\&. The default setting is "relative"\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	atime disable
.fi
.if n \{\
.RE
.\}
.RE
.PP
client_file_bufsize \fIbytes\fR
.RS 4
This directive specifies the file buffer size in bytes used in the Gfarm client library (libgfarm)\&. The default size is 1048568 bytes (= 1MiB \- 8B)\&. The file buffer size should be less than the default value not for deterioration of remote access performance for version 2\&.5\&.0 or earlier\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	client_file_bufsize 65536
.fi
.if n \{\
.RE
.\}
.RE
.PP
client_parallel_copy \fInum\-of\-parallel\fR
.RS 4
This directive specifies the number of parallel for
\fBgfprep\fR
and
\fBgfpcopy\fR
to work in parallel\&. When this number is not specified, the default number of parallel is 4\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	client_palallel_copy 10
.fi
.if n \{\
.RE
.\}
.RE
.PP
client_parallel_max \fInum\-of\-parallel\fR
.RS 4
This directive specifies the maximum number of parallel for
\fBgfprep\fR
and
\fBgfpcopy\fR
to work in parallel\&. When this number is not specified, the default maximum number of parallel is 16\&.
.sp
For example,
.sp
.if n \{\
.RS 4
.\}
.nf
	client_palallel_max 8
.fi
.if n \{\
.RE
.\}
.RE
.PP
profile \fIvalidity\fR
.RS 4
When "enable" is specified, Gfarm outputs the profile information\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	profile enable
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_server_list \fIgfmd\-hostname[:port]\fR \fI\&.\&.\&.\fR
.RS 4
This parameter specifies connection destinations of redundant metadata servers delimited by space\&. If port is not specified, port will be 601 which is the default value\&.
.sp
This parameter is only available in gfarm2\&.conf, and ignored in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_server_list mds1 mds2:701
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_replication \fIvalidity\fR
.RS 4
When "enable" is specified, the redundant metadata feature is enabled\&. The default value is disable\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_replication enable
.fi
.if n \{\
.RE
.\}
.RE
.PP
synchronous_replication_timeout \fIseconds\fR
.RS 4
This parameter specifies timeout for executing synchronous replication in seconds\&. If the timeout period passed, the connection to the slave gfmd where replicates to will disconnect\&. The replication process in the master gfmd for the disconnected slave gfmd stops until the slave gfmd connects\&. The default is 10\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	synchronous_replication_timeout 30
.fi
.if n \{\
.RE
.\}
.RE
.PP
synchronous_journaling \fIvalidity\fR
.RS 4
When "enable" is specified, fdatasync is called after update information is saved to the journal file\&. The timing of calling fdatasync is after writing the records from transaction\-begin to transaction\-end in one transaction\&. The default is "enable"\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	synchronous_journaling disable
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_server_force_slave \fIvalidity\fR
.RS 4
When "enable" is specified, even if the gfmd is set to default master, it run as slave gfmd forcedly\&. The default is "disable"\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_server_force_slave enable
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_server_slave_listen \fIvalidity\fR
.RS 4
When "enable" is specified, even if the gfmd is set to slave, it receives requests from clients\&. The default is "disable"\&.
.sp
NOTE: Please do not set this directive for ordinary use, because this feature is only for development\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_server_slave_listen enable
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_server_slave_max_size \fInumber\fR
.RS 4
This parameter specifies the maximum number of slave gfmds\&. The default is "32"\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_server_slave_max_size 40
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_journal_dir \fIdirectory\fR
.RS 4
This parameter specifies the directory for the journal file\&. The value of this parameter is specified at config\-gfarm execution \&. When this parameter is not specified, the gfmd does not start\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_journal_dir /var/gfarm\-metadata/journal
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_journal_max_size \fIfile_size\fR
.RS 4
This parameter specifies the max size of the journal file in bytes\&. Beware that the larger the size is, the longer it takes time for the gfmd to complete starting\&. The default is 33554432 (32 MBytes)\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_journal_max_size 8388608
.fi
.if n \{\
.RE
.\}
.RE
.PP
metadb_journal_recvq_size \fIsize\fR
.RS 4
This parameter specifies the maximum number of on\-memory records of the journal data that the slave gfmd receives from the master gfmd\&. If it reaches this value, the slave gfmd gives up and exits, because the gfmd thinks that it\*(Aqs too slow to apply the journal data to the backend database\&. The default value is 100000\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	metadb_journal_recvq_size 100000
.fi
.if n \{\
.RE
.\}
.RE
.PP
replica_check \fIvalidity\fR
.RS 4
When "enable" is specified, the replica_check system in gfmd can check and fix the number and placement of file replicas automatically\&. The replica_check works only when necessary\&. The default value is "enable"\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	replica_check disable
.fi
.if n \{\
.RE
.\}
.RE
.PP
replica_check_host_down_thresh \fIseconds\fR
.RS 4
If a gfsd is down, the replica_check assumes that the gfsd is not down until the specified seconds\&. This is useful to maintain a gfsd\&. The default value is 10800 seconds (3 hours)\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	replica_check_host_down_thresh 3600
.fi
.if n \{\
.RE
.\}
.RE
.PP
replica_check_sleep_time \fInanoseconds\fR
.RS 4
If this value is increased, the replica_check works more slowly only when the gfmd is busy\&. When the gfmd is not busy, the replica_check works at full speed\&. This directive specifies the nanoseconds to sleep in the replica_check\&. The default value is 100000 nanoseconds (0\&.1 millisecond)\&. The maximum value is 1000000000 nanoseconds (1 second)\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	replica_check_sleep_time 0
.fi
.if n \{\
.RE
.\}
.RE
.PP
replica_check_minimum_interval \fIseconds\fR
.RS 4
This directive specifies the minimum interval in seconds, for the replica_check to work\&. The default value is 10 seconds, i\&.e\&. the replica_check can work up to one time every 10 seconds\&.
.sp
This parameter is only available in gfmd\&.conf\&.
.sp
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
	replica_check_minimum_interval 5
.fi
.if n \{\
.RE
.\}
.RE
.SH "GRAMMAR"
.PP
This is a grammar of gfarm2\&.conf described by the BNF notation\&.
.PP
<statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<spool_statement> |
	<spool_server_listen_address_statement> |
	<spool_server_listen_backlog_statement> |
	<spool_server_cred_type_statement> |
	<spool_server_cred_service_statement> |
	<spool_server_cred_name_statement> |
	<spool_check_level_statement> |
	<metadb_server_host_statement> |
	<metadb_server_port_statement> |
	<metadb_server_cred_type_statement> |
	<metadb_server_cred_service_statement> |
	<metadb_server_cred_name_statement> |
	<metadb_server_listen_backlog_statement> |
	<metadb_server_max_descriptors_statement> |
	<metadb_server_stack_size_statement> |
	<metadb_server_thread_pool_size_statement> |
	<metadb_server_job_queue_length_statement> |
	<metadb_server_heartbeat_interval_statement> |
	<metadb_server_dbq_size_statement> |
	<ldap_server_host_statement> |
	<ldap_server_port_statement> |
	<ldap_base_dn_statement> |
	<ldap_bind_dn_statement> |
	<ldap_bind_password_statement> |
	<postgresql_server_host_statement> |
	<postgresql_server_port_statement> |
	<postgresql_dbname_statement> |
	<postgresql_user_statement> |
	<postgresql_password_statement> |
	<postgresql_conninfo_statement> |
	<auth_statement> |

	<sockopt_statement> |



	<known_network_statement> |
	<network_receive_timeout_statement> |
	<admin_user_statement> |
	<admin_user_gsi_dn_statement> |
	<local_user_map_statement> |
	<local_group_map_statement> |
	<schedule_cache_timeout_statement> |
	<schedule_concurrency_statement> |
	<schedule_concurrency_per_net_statement> |
	<schedule_idle_load_thresh_statement> |
	<schedule_busy_load_thresh_statement> |
	<schedule_virtual_load_statement> |
	<schedule_candidates_ratio_statement> |
	<schedule_rtt_thresh_diff_statement> |
	<schedule_rtt_thresh_ratio_statement> |
	<schedule_rtt_thresh_statement> |
	<write_local_priority_statement> |
	<write_target_domain_statement> |
	<minimum_free_disk_space_statement> |
	<gfs_proto_fhremove_request_window_statement> |
	<gfs_proto_replication_request_window_statement> |
	<simultaneous_replication_receivers_statement> |
	<outstanding_file_replication_limit_statement> |
	<gfsd_connection_cache_statement> |
	<xmlattr_size_limit_statement> |
	<xattr_size_limit_statement> |
	<attr_cache_limit_statement> |
	<attr_cache_timeout_statement> |
	<page_cache_timeout_statement> |
	<log_level_statement> |
	<log_message_verbose_level_statement> |
	<log_auth_verbose_statement> |
	<file_trace_statement> |
	<fatal_action_statement> |
	<debug_command_statement> |

	<atime_statement> |
	<client_file_bufsize_statement> |
	<client_parallel_copy_statement> |
	<profile_statement> |
	<metadb_server_list_statement> |
	<metadb_replication_statement> |
	<synchronous_replication_timeout_statement> |
	<synchronous_journaling_statement> |
	<metadb_server_force_slave_statement> |
	<metadb_server_slave_listen_statement> |
	<metadb_server_slave_max_size_statement> |
	<metadb_journal_dir_statement> |
	<metadb_journal_max_size_statement> |
	<metadb_journal_recvq_size_statement> |
	<replica_check_statement> |
	<replica_check_host_down_thresh_statement> |
	<replica_check_sleep_time_statement> |
	<replica_check_minimum_interval_statement>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<spool_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"spool" <pathname>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<spool_server_listen_address_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"spool_server_listen_address" <ipv4_address>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<spool_server_listen_backlog_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"spool_server_listen_backlog" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<spool_server_cred_type_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"spool_server_cred_type" <cred_type>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<spool_server_cred_service_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"spool_server_cred_service" <cred_service>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<spool_server_cred_name_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"spool_server_cred_name" <cred_name>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<spool_check_level_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"spool_check_level" <spck_level>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_host_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_host" <hostname>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_port_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_port" <portnumber>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_cred_type_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_cred_type" <cred_type>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_cred_service_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_cred_service" <cred_service>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_cred_name_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_cred_name" <cred_name>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_listen_backlog_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_listen_backlog" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_max_descriptors_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_max_descriptors" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_stack_size_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_stack_size" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_thread_pool_size_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_thread_pool_size" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_job_queue_length_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_job_queue_length" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_heartbeat_interval_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_heartbeat_interval" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_dbq_size_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_dbq_size" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<ldap_server_host_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"ldap_server_host" <hostname>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<ldap_server_port_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"ldap_server_port" <portnumber>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<ldap_base_dn_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"ldap_base_dn" <string>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<ldap_bind_dn_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"ldap_bind_dn" <string>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<ldap_bind_password_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"ldap_bind_password" <string>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<postgresql_server_host_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"postgresql_server_host" <hostname>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<postgresql_server_port_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"postgresql_server_port" <portnumber>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<postgresql_dbname_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"postgresql_dbname" <string>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<postgresql_user_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"postgresql_user" <string>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<postgresql_password_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"postgresql_password" <string>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<postgresql_conninfo_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"postgresql_conninfo" <string>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<auth_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"auth" <validity> <auth_method> <hostspec>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<auth_command> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"enable" | "disable"
.fi
.if n \{\
.RE
.\}
.RE
.PP
<auth_method> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"gsi" | "gsi_auth" | "sharedsecret"
.fi
.if n \{\
.RE
.\}
.RE
.PP
<sockopt_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"sockopt" <socket_option>[=<number>] [""LISTENER" | <hostspec>]
.fi
.if n \{\
.RE
.\}
.RE
.PP
<socket_option> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"debug" | "keepalive" | "sndbuf" | "rcvbuf" |
	"tcp_nodelay"
.fi
.if n \{\
.RE
.\}
.RE
.PP
<known_network_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"known_network" <hostspec>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<network_receive_timeout_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"network_receive_timeout" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<admin_user_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"admin_user" <string>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<admin_user_gsi_dn_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"admin_user_gsi_dn" <string>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<local_user_map_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"local_user_map" <local_user_and_group_map_spec>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<local_group_map_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"local_group_map" <local_user_and_group_map_spec>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<local_user_and_group_map_spec> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<pathname> |
		<pathname> <hostname>|
		<pathname> <hostname> ":" <portnumber>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<schedule_cache_timeout_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"schedule_cache_timeout" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<schedule_concurrency_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"schedule_concurrency" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<schedule_concurrency_per_net_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"schedule_concurrency_per_net" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<schedule_idle_load_thresh_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"schedule_idle_load_thresh" <load>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<schedule_busy_load_thresh_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"schedule_busy_load_thresh" <load>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<schedule_virtual_load_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"schedule_virtual_load" <load>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<schedule_candidates_ratio_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"schedule_candidates_ratio" <floating_point_number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<schedule_rtt_thresh_diff_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"schedule_rtt_thresh_diff" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<schedule_rtt_thresh_ratio_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"schedule_rtt_thresh_ratio" <floating_point_number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<schedule_rtt_thresh_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"schedule_rtt_thresh" <floating_point_number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<write_local_priority_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"write_local_priority" <validity>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<write_target_domain_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"write_target_domain" <string>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<minimum_free_disk_space_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"minimum_free_disk_space" <size>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<gfs_proto_fhremove_request_window_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"gfs_proto_fhremove_request_window" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<gfs_proto_replication_request_window_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"gfs_proto_replication_request_window" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<simultaneous_replication_receivers_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"simultaneous_replication_receivers" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<outstanding_file_replication_limit_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"outstanding_file_replication_limit" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<gfsd_connection_cache_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"gfsd_connection_cache" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<xmlattr_size_limit_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"xmlattr_size_limit" <size>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<xattr_size_limit_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"xattr_size_limit" <size>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<attr_cache_limit_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"attr_cache_limit" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<attr_cache_timeout_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"attr_cache_timeout" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<page_cache_timeout_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"page_cache_timeout" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<log_level_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"log_level" <log_priority>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<log_message_verbose_level_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"log_message_verbose_level" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<log_auth_verbose_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"log_auth_verbose" <validity>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<file_trace_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"file_trace" <validity>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<fatal_action_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"fatal_action" <fatal_action_name>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<debug_command_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"debug_command" <string_list>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<no_file_system_node_timeout_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"no_file_system_node_timeout" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<gfmd_reconnection_timeout_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"gfmd_reconnection_timeout" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<atime_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"atime" <atime_type>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<client_file_bufsize_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"client_file_bufsize" <size>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<client_parallel_copy_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"client_parallel_copy" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<profile_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"profile" <validity>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_list_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_list" <metadb_server_list_spec>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_list_spec> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<hostname_port_spec> |
	<hostname_port_spec> <metadb_server_list_spec>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_replication_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_replication" <validity>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<synchronous_replication_timeout_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"synchronous_replication_timeout" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<synchronous_journaling_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"synchronous_journaling" <validity>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_force_slave_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_force_slave" <validity>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_slave_listen_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_slave_listen" <validity>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_server_slave_max_size_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_server_slave_max_size" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_journal_dir_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_journal_dir" <pathname>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_journal_max_size_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_journal_max_size" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<metadb_journal_recvq_size_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"metadb_journal_recvq_size" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<replica_check_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"replica_check" <validity>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<replica_check_host_down_thresh_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"replica_check_host_down_thresh" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<replica_check_sleep_time_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"replica_check_sleep_time" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<replica_check_minimum_interval_statement> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"replica_check_minimum_interval" <number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<string_list> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<string> |
	<string> <string_list>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<hostspec> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<ipv4_address> | <ipv4_address> "/" <address_mask> |
	<hostname> | "\&." <domain_name> | "*"
.fi
.if n \{\
.RE
.\}
.RE
.PP
<pathname> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<pathname_character> <pathname_character>*
.fi
.if n \{\
.RE
.\}
.RE
.PP
<pathname_character> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<hostname_character> | "," | "/" | "_"
.fi
.if n \{\
.RE
.\}
.RE
.PP
<hostname_port_spec> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<hostname>|
	<hostname> ":" <portnumber>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<hostname> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<hostname_character> <hostname_character>*
.fi
.if n \{\
.RE
.\}
.RE
.PP
<hostname_character> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<alphabet> | <digit> | "\-" | "\&."
.fi
.if n \{\
.RE
.\}
.RE
.PP
<portnumber> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<number>
.fi
.if n \{\
.RE
.\}
.RE
.PP
<size> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<number> [ "k" | "M" | "G" | "T" ]
.fi
.if n \{\
.RE
.\}
.RE
.PP
<number> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<digit> [<digit>*]
.fi
.if n \{\
.RE
.\}
.RE
.PP
<digit> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
.fi
.if n \{\
.RE
.\}
.RE
.PP
<string> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
""" <double_quoted_character>* """
.fi
.if n \{\
.RE
.\}
.RE
.PP
<double_quoted_character> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
<any_character_except_backslash_and_double_quotation> |
	"\e\e" | "\e""
.fi
.if n \{\
.RE
.\}
.RE
.PP
<validity> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"enable" | "disable"
.fi
.if n \{\
.RE
.\}
.RE
.PP
<spck_level> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"disable" | "display" | "delete" | "lost_found"
.fi
.if n \{\
.RE
.\}
.RE
.PP
<atime_type> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"disable" | "relative" | "strict"
.fi
.if n \{\
.RE
.\}
.RE
.PP
<log_priority> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"emerg" | "alert" | "crit" | "err" | "warning" |
	"notice" | "info" | "debug"
.fi
.if n \{\
.RE
.\}
.RE
.PP
<fatal_action_name> ::=
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
"backtrace_and_abort" | "backtrace_and_exit" |
	"abort" | "exit"
.fi
.if n \{\
.RE
.\}
.RE
.SH "EXAMPLES"
.PP
The following is an example of gfarm2\&.conf to use sharedsecret authentication\&.
.sp
.if n \{\
.RS 4
.\}
.nf
metadb_server_host metadb\&.example\&.org
metadb_server_port 601
auth enable sharedsecret *
sockopt keepalive
.fi
.if n \{\
.RE
.\}
.PP
The following is an example of gfmd\&.conf to use PostgreSQL to store the metadata, and to allow access from filesystem nodes and clients at IP address 192\&.168\&.0\&.0/24, via sharedsecret authentication\&.
.sp
.if n \{\
.RS 4
.\}
.nf
metadb_server_host metadb\&.example\&.org
metadb_server_port 601
postgresql_server_host metadb\&.example\&.org
postgresql_server_port 5432
postgresql_dbname gfarm
postgresql_user gfarm
postgresql_password "secret\-postgresql\-password"
auth enable sharedsecret 192\&.168\&.0\&.0/24
admin_user john
sockopt keepalive
.fi
.if n \{\
.RE
.\}
.PP
The following is an example of gfmd\&.conf to use LDAP to store the metadata, and to allow access from filesystem nodes and clients at any IP address, via GSI authentication\&.
.sp
.if n \{\
.RS 4
.\}
.nf
metadb_server_host metadb\&.example\&.com
metadb_server_port 601
ldap_server_host metadb\&.example\&.com
ldap_server_port 602
ldap_base_dn "dc=example, dc=com"
ldap_bind_dn "cn=gfarmuser, dc=example, dc=com"
ldap_bind_password "secret\-ldap\-password"
auth enable gsi *
spool_server_cred_type host
spool_server_cred_service gfsd
admin_user john
admin_user_gsi_dn "/C=JP/ST=Tokyo/L=Chuo\-ku/O=Example, Inc\&./OU=Example Division/CN=John Doe"
sockopt keepalive
.fi
.if n \{\
.RE
.\}
.SH "FILES"
.PP
%%SYSCONFDIR%%/gfarm2\&.conf
.RS 4
.RE
.PP
$HOME/\&.gfarm2rc
.RS 4
.RE
.SH "SEE ALSO"
.PP
\fBgfmd\fR(8),
\fBgfsd\fR(8),
\fBsetsockopt\fR(2)
