'\" t
.\"     Title: gfarm_attr
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 1 Apr 2011
.\"    Manual: Gfarm_attr
.\"    Source: Gfarm_attr
.\"  Language: English
.\"
.TH "GFARM_ATTR" "5" "1 Apr 2011" "Gfarm_attr" "Gfarm_attr"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfarm_attr \- Gfarm Extended Attributes
.SH "DESCRIPTION"
.PP
Every files and directories in Gfarm filesystem can have extended attributes\&. Extended attributes are name:value pairs\&.
.SH "EXTENDED ATTRIBUTE NAMESPACES"
.PP
The extended attributes which have "gfarm\&." or "gfarm_root\&." prefix name are specially treated in Gfarm filesystem\&. General Gfarm users can freely use the extended attributes which have "user\&." prefix name\&. XML extended attributes can have any names\&.
.PP
Everyone can get the "gfarm\&.*" extended attributes\&. Owner or gfarmroot group can modify the "gfarm\&.*" extended attributes\&.
.PP
The users in gfarmroot group or the users in "gfarm_root\&.uesr" of the entry or the groups in "gfarm_root\&.group" of the entry can get/modify the "gfarm_root\&.*" extended attributes\&.
.PP
The "user\&.*" extended attributes can be gotten/modified on the entry (file or directory) permission\&.
.PP
Symbolic links cannot have any extended attributes\&.
.SH "GFARM EXTENDED ATTRIBUTES"
.PP
The following is a list of the extended attribute names used in Gfarm filesystem\&.
.PP
\fIgfarm\&.ncopy\fR
.RS 4
This is the number of file replicas to be created automatically in gfmd\&.
.RE
.PP
\fIgfarm\&.acl_access\fR
.RS 4
This is Access ACL (Access Control List)\&.
.RE
.PP
\fIgfarm\&.acl_default\fR
.RS 4
This is Default ACL\&. Only directories can have/use this extended attribute\&.
.RE
.PP
\fIgfarm_root\&.user\fR
.RS 4
This is the list of user names who can have the privilege for the entry (file or directory)\&. The names are separated by a new line (\en)\&. This extended attribute is copied to a new entry (file or directory) from the parent directory (when the parent directory has this extended attribute)\&.
.RE
.PP
\fIgfarm_root\&.group\fR
.RS 4
This is the list of group names who can have the privilege for the entry (file or directory)\&. The names are separated by a new line (\en)\&. This extended attribute is copied to a new entry (file or directory) from the parent directory (when the parent directory has this extended attribute)\&.
.RE
.SH "SECURITY NOTES"
.PP
When untrusted users are registered in the gfarm_root\&.{user,group} extended attributes of any files or directories, a Security Hole exists on the mount point of gfarm2fs with "\-o suid,allow_other" option executed by root (even if either "\-o ro" option or "\-o default_permissions" option is also specified)\&. Therefore both "\-o suid,allow_other" option and gfarm_root\&.{user,group} extended attributes should not be used\&.
.SH "SEE ALSO"
.PP

\fBgfxattr\fR(1),
\fBgfgetfacl\fR(1),
\fBgfsetfacl\fR(1)
