'\" t
.\"     Title: gfservice.conf
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 6 Jun 2013
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFSERVICE\&.CONF" "5" "6 Jun 2013" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfservice.conf \- configuration file of gfservice
.SH "DESCRIPTION"
.PP

\fBgfservice\fR
reads configuration data from the file\&. (\fBgfservice\-agent\fR
doesn\*(Aqt read a configuration file\&.)
.PP
The configuration file itself is a Bourne\-shell script\&. It is
\fIevaluated as a script\fR
by
\fBgfservice\fR\&. Here is an example of the configuration file:
.sp
.if n \{\
.RS 4
.\}
.nf
	# gfmd entries\&.
	gfmd1=db1\&.example\&.com
	gfmd2=db2\&.example\&.com
.fi
.if n \{\
.RE
.\}
.PP
Same as Bourne\-shell script, lines beginning with \*(Aq#\*(Aq and empty lines are ignored\&. The other lines declare shell variables\&. In this example, the variable
\fIgfmd1\fR
is set to
\fIdb1\&.example\&.com\fR
and
\fIgfmd2\fR
to
\fIdb12\&.example\&.com\fR
respectively\&. Whitespaces
\fImust not\fR
be inserted around \*(Aq=\*(Aq\&.
.PP
The variables named
\fIgfmd1\fR
and
\fIgfmd2\fR
are used as "host\-id"\&. To specify a remote host,
\fBgfservice\fR
uses host\-id instead of hostname:
.sp
.if n \{\
.RS 4
.\}
.nf
	\fBgfservice \fR\fB\fIstart\-gfmd\fR\fR\fB \fR\fB\fIgfmd2\fR\fR
.fi
.if n \{\
.RE
.\}
.PP
Executing the command,
\fBgfservice\fR
starts gfmd on
\fIgfmd2\fR
server, metadb2\&.example\&.com\&. Note that the numbers at the tails of host\-ids must be beginning with 1 and must be assigned successively\&.
.PP
For specifying gfsd servers and client hosts, use host\-ids "gfs\fIn\fR" and "client\fIn\fR" respectively:
.sp
.if n \{\
.RS 4
.\}
.nf
	# gfsd entries\&.
	gfsd1=fs1\&.example\&.com

	# client entries
	client1=pc1\&.example\&.com
	client2=pc2\&.example\&.com
	client3=pc2\&.example\&.com
.fi
.if n \{\
.RE
.\}
.PP
In addition with host\-id variables,
\fBgfservice\fR
recognizes some variables related to host\-id\&.
.sp
.if n \{\
.RS 4
.\}
.nf
	# Configuration about gfmd1\&.
	gfmd1_CONFIG_GFARM_OPTIONS="\-X \-A $LOGNAME"
	gfmd1_SSH="ssh \-i $HOME/\&.ssh/id_rsa_gfservice"
	gfmd1_SUDO=/usr/local/bin/sudo
.fi
.if n \{\
.RE
.\}
.PP
As shown in this example, a value containing whitespaces can be set by quotation marks\&.
\fI$VARNAME\fR
is expanded to the value of the shell or environment variable
\fIVARNAME\fR\&.
.SH "VARIABLES ABOUT GFMD"
.PP
Variables named "gfmd\fIn\fR" (gfmd1, gfmd2, \&.\&.\&.) define gfmd servers\&. Variable names beginning with "gfmd\fIn\fR_" such as
\fIgfmd1_SSH\fR
set configuration parameters of the corresponding "gfmd\fIn\fR" server\&.
\fBgfservice\fR
currently the following variables:
.PP
\fIgfmd\fR\fI\fIn\fR\fR
.RS 4
Register a gfmd server\&. Its value represents a hostname (or an IP address) of the server\&. Note that
\fBgfservice\fR
uses the values for destination hosts of SSH connections only\&. To specify host names used in the Gfarm system, use
\fB\-h\fR
option in
\fIgfmd\fR\fI\fIn\fR\fR\fI_CONFIG_GFARM_OPTOINS\fR
variable instead:
.sp
.if n \{\
.RS 4
.\}
.nf
	gfmd1=md1\-ctl\&.example\&.org
	gfmd1_CONFIG_GFARM_OPTIONS="\-h md1\&.example\&.org"
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_GFBINDIR\fR
.RS 4
Specify a path to a directory where
\fBgfservice\-agent\fR
command is installed on the gfmd server\&. If the variable is declared,
\fBgfservice\fR
executes
\fB"\fR\fB\fI$gfmd\fR\fI\fIn\fR\fR\fI_GFBINDIR\fR\fR\fB/gfservice\-agent"\fR\&. Otherwise it executes
\fB"gfservice\-agent"\fR\&.
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_CONFIG_GFARM_OPTIONS\fR
.RS 4
Specify options of
\fBconfig\-gfarm\fR
command\&. The default value is empty (no option)\&.
\fBgfservice\fR
refers this variable to perform
\fBconfig\-gfarm\fR
and many other sub\-commands\&. Do not delete or edit the declaration even after
\fBconfig\-gfarm\fR
has been complete\&.
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_PRIVATE_MODE\fR
.RS 4
Set this variable to "true" if gfmd on the remote host is configured in private mode\&.
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_AUTH_TYPE\fR
.RS 4
Specify authentication type ("sharedsecret", "gsi" or "gsi_auth")\&. If the variable is not declared, its value is chosen from
\fIAUTH_TYPE\fR
value output by
\fBconfig\-gfarm \-T\fR
command executed on gfmd1\&. (Note that the value
\fIAUTH_TYPE\fR
above is affected by the variable
\fIgfmd1_CONFIG_GFARM_OPTIONS\fR\&.)
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_CLUSTER_NAME\fR
.RS 4
Specify a cluster name of the gfmd server\&. The default value is "" (empty) which means the server belongs to the default cluster\&.
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_SSH\fR
.RS 4
Specify a path to an SSH client command and its options\&. The variable is used when
\fBgfservice\fR
executes an SSH client command to connect with the gfsd server\&. The default value is "ssh"\&.
.RE
.PP
\fIgfmd\fR\fI\fIn\fR\fR\fI_SUDO\fR
.RS 4
Specify a path to a Sudo command and options\&. The variable is used when
\fBgfservice\fR
executes a Sudo command on the gfsd server via SSH\&. The default value is "sudo"\&.
.RE
.SH "VARIABLES ABOUT GFSD"
.PP
Variables named "gfsd\fIn\fR" (gfsd1, gfsd2, \&.\&.\&.) define gfsd servers\&. Variable names beginning with "gfsd\fIn\fR_" such as
\fIgfsd1_SSH\fR
set configuration parameters of the corresponding "gfsd\fIn\fR" server\&.
\fBgfservice\fR
currently recognizes the following variables:
.PP
\fIgfsd\fR\fI\fIn\fR\fR
.RS 4
Register a gfsd server\&. Its value represents a hostname (or an IP address) of the server\&. Note that
\fBgfservice\fR
uses the values for destination hosts of SSH connections only\&. To specify host names used in the Gfarm system, use
\fB\-h\fR
option in
\fIgfsd\fR\fI\fIn\fR\fR\fI_CONFIG_GFSD_OPTOINS\fR
variable instead:
.sp
.if n \{\
.RS 4
.\}
.nf
	gfsd1=fs2\-ctl\&.example\&.org
	gfsd1_CONFIG_GFSD_OPTIONS="\-h fs2\&.example\&.org"
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fIgfsd\fR\fI\fIn\fR\fR\fI_GFBINDIR\fR
.RS 4
Specify a path to a directory where
\fBgfservice\-agent\fR
command is installed on the gfsd server\&. If the variable is declared,
\fBgfservice\fR
executes
\fB"\fR\fB\fI$gfsd\fR\fI\fIn\fR\fR\fI_GFBINDIR\fR\fR\fB/gfservice\-agent"\fR\&. Otherwise it executes
\fB"gfservice\-agent"\fR\&.
.RE
.PP
\fIgfsd\fR\fI\fIn\fR\fR\fI_CONFIG_GFSD_OPTIONS\fR
.RS 4
Specify options of
\fBconfig\-gfsd\fR
command\&. The default value is empty (no option)\&.
\fBgfservice\fR
refers this variable to perform
\fBconfig\-gfsd\fR
and many other sub\-commands\&. Do not delete or edit the declaration even after
\fBconfig\-gfsd\fR
has been complete\&.
.RE
.PP
\fIgfsd\fR\fI\fIn\fR\fR\fI_PRIVATE_MODE\fR
.RS 4
Set this variable to "true" if gfsd on the remote host is configured in private mode\&.
.RE
.PP
\fIgfsd\fR\fI\fIn\fR\fR\fI_AUTH_TYPE\fR
.RS 4
Specify authentication type ("sharedsecret", "gsi" or "gsi_auth")\&. If the variable is not declared, its value is chosen from
\fIAUTH_TYPE\fR
value output by
\fBconfig\-gfarm \-T\fR
command executed on gfmd1\&. (Note that the value
\fIAUTH_TYPE\fR
above is affected by the variable
\fIgfmd1_CONFIG_GFARM_OPTIONS\fR\&.)
.RE
.PP
\fIgfsd\fR\fI\fIn\fR\fR\fI_SSH\fR
.RS 4
Specify a path to an SSH client command and its options\&. The variable is used when
\fBgfservice\fR
executes an SSH client command to connect with the gfsd server\&. The default value is "ssh"\&.
.RE
.PP
\fIgfsd\fR\fI\fIn\fR\fR\fI_SUDO\fR
.RS 4
Specify a path to a Sudo command and options\&. The variable is used when
\fBgfservice\fR
executes a Sudo command on the gfsd server via SSH\&. The default value is "sudo"\&.
.RE
.SH "VARIABLES ABOUT CLIENT"
.PP
Variables named "client\fIn\fR" (client1, client2, \&.\&.\&.) define client hosts\&. Their values are hostnames (or IP addresses)\&. Variable names beginning with "client\fIn\fR_" such as
\fIclient1_SUDO\fR
set configuration parameters of the corresponding "client\fIn\fR" host\&.
\fBgfservice\fR
currently recognizes the following variables:
.PP
\fIclient\fR\fI\fIn\fR\fR
.RS 4
Register a client host\&. Its value represents a hostname (or an IP address) of the host\&.
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_GFBINDIR\fR
.RS 4
Specify a path to a directory where
\fBgfservice\-agent\fR
command is installed on the client host\&. If the variable is declared,
\fBgfservice\fR
executes
\fB"\fR\fB\fI$client\fR\fI\fIn\fR\fR\fI_GFBINDIR\fR\fR\fB/gfservice\-agent"\fR\&. Otherwise it executes
\fB"gfservice\-agent"\fR\&.
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_MOUNT_GFARM2FS\fR
.RS 4
Specify a path to
\fBmount\&.gfarm2fs\fR
command and its options\&. The variable is used when
\fBgfservice\fR
executes
\fBmount\&.gfarm2fs\fR
command to mount a file system\&. The default value is "%%BINDIR%%/mount\&.gfarm2fs"\&.
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_UMOUNT_GFARM2FS\fR
.RS 4
Specify a path to
\fBumount\&.gfarm2fs\fR
command and its options\&. The variable is used when
\fBgfservice\fR
executes
\fBumount\&.gfarm2fs\fR
command to unmount a file system\&. The default value is "%%BINDIR%%/umount\&.gfarm2fs"\&.
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_SSH\fR
.RS 4
Specify a path to an SSH client command and its options\&. The variable is used when
\fBgfservice\fR
executes an SSH client command to connect with the client host\&. The default value is "ssh"\&.
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_SUDO\fR
.RS 4
Specify a path to a Sudo command and options\&. The variable is used when
\fBgfservice\fR
executes a Sudo command on the client host via SSH\&. The default value is "sudo"\&.
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_GFARM_CONF\fR
.RS 4
Specify a gfarm2\&.conf file in absolute path\&. If a value is not set,
\fBgfservice\fR
uses a same path as the path of gfarm2\&.conf in gfmd1(determined from the \*(Aqgfmd1_CONFIG_GFARM_OPTIONS\*(Aq shell variable)\&.
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_PRIVATE_MODE\fR
.RS 4
If this variable is set to "true",
\fBgfservice\fR
processes the sub\-command
\fBconfig\-client\fR
without root privilege\&.
.RE
.PP
\fIclient\fR\fI\fIn\fR\fR\fI_AUTH_TYPE\fR
.RS 4
Specify authentication type ("sharedsecret", "gsi" or "gsi_auth")\&. If the variable is not declared, its value is chosen from
\fIAUTH_TYPE\fR
value output by
\fBconfig\-gfarm \-T\fR
command executed on gfmd1\&. (Note that the value
\fIAUTH_TYPE\fR
above is affected by the variable
\fIgfmd1_CONFIG_GFARM_OPTIONS\fR\&.)
.RE
