top_builddir = ../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

###
### variables
###

CFLAGS = -I$(top_srcdir)/include

CATALOG_FILES = gfarm.cat

EXTRA_CLEAN_TARGETS = $(CATALOG_FILES)

LOCALE = ja_JP.UTF-8

include $(top_srcdir)/makes/catalog.mk
