top_objdir = ../../../..
top_srcdir = $(top_objdir)
srcdir = .

include $(top_srcdir)/makes/var.mk

SUBDIRS = man1 man3 man5 man8

htmldir=$(default_htmldir)/en/ref
HTML = index.html

include $(top_srcdir)/makes/subdir.mk
include $(top_srcdir)/makes/html.mk
