top_builddir = ../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

datadir=$(default_datadir)/gfarm/systest/testcases

DATA =	$(srcdir)/failover_by_stop \
	$(srcdir)/failover_by_kill \
	$(srcdir)/failover_by_reboot \
	$(srcdir)/configuration

include $(top_srcdir)/makes/data.mk
