# $Id: Makefile 2533 2006-03-31 10:50:56Z takuya $

top_builddir = ../../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

CFLAGS = 
LDLIBS = 

PROGRAM = gfperf-wrapper.sh
OBJS = 

all: $(PROGRAM)

include $(top_srcdir)/makes/prog.mk
