top_builddir = ../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

datadir=$(default_datadir)/gfarm/systest/parameters

DATA =	$(srcdir)/failover \
	$(srcdir)/configuration

include $(top_srcdir)/makes/data.mk
