.TH gfmd 8 "1 May 2002"
.SH NAME

gfmd(8) \- GfarmメタDB・デーモン

.SH SYNOPSIS

.B gfmd
[
.I オプション
]

.SH DESCRIPTION

gfmd は、Gfarm ライブラリと協調して動作し、Gfarm 並列ファイルシステ
ムのメタデータへのアクセスを提供するデーモンプログラムです。
gfmd は Gfarm のメタDBサーバー・ホスト上で、 
あらかじめ立ち上げておく必要があります。

.SH OPTIONS

.TP
.B \-d
.br
デバッグオプションです。デーモンとしてではなく、フォアグラウンド・
プロセスとして立ち上がります。
.TP
.B \-p ポート番号
.br
gfmd が利用する TCP のポート番号を指定します。
.br
省略した場合には 601 番を使用します。
この場合、gfmd の起動はルート権限で行なう必要があります。
ただし、動作するユーザー権限は任意のもので構いません。
.TP
.B \-s syslogファシリティ
.br
gfmd がエラー報告に用いる syslog のファシリティを指定します。省略
した場合には、local0 を使用します。
.TP
.B \-u ユーザー名
.br
ルート権限で gfmd が起動された際に、動作するユーザー権限を root 
以外に変更する場合に指定します。
.TP
.B \-?
.br
引数オプションを表示します。

.\" .SH SEE ALSO
.\" .BR gfmd.conf (5)
