'\" t
.\"     Title: gfmd
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 14 Feb 2008
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFMD" "8" "14 Feb 2008" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfmd \- GfarmメタDB・デーモン
.SH "SYNOPSIS"
.HP \w'\fBgfmd\fR\ 'u
\fBgfmd\fR [\fIオプション\fR]
.SH "DESCRIPTION"
.PP
gfmdは、Gfarmライブラリと協調して動作し、Gfarmファイルシステ ムのメタデータへのアクセスを提供するデーモンプログラムです。 gfmdはGfarmのメタDBサーバー・ホスト上で、 あらかじめ立ち上げておく必要があります。
.PP
gfmdはユーザ権限で動作させることも可能ですが、この場合他のユーザはこ のgfmdを利用することができません。 詳細はSETUP\&.private\&.jaを参照してください。
.PP
gfmdを利用するためには， クライアントノードの~/\&.gfarm2rcあるいは%%SYSCONFDIR%%/gfarm2\&.confの metadb_server_hostで利用したいgfmdのホスト名， metadb_server_portでポート番号を指定する必要がありま す．
.SH "OPTIONS"
.PP
\fB\-L\fR \fIログレベル\fR
.RS 4
このオプションで指定したレベル以上の優先度のログを出力します。 指定できる値はgfarm2\&.conf(5)のlog_levelの項を参照してください。
.RE
.PP
\fB\-P\fR \fIPIDファイル\fR
.RS 4
gfmdのprocess IDを、指定したファイルに記録します。
.RE
.PP
\fB\-d\fR
.RS 4
デバッグオプションです。デーモンとしてではなく、フォアグラウンド・ プロセスとして立ち上がります。
.sp
このオプションを指定し、かつ\fB\-L\fRオプションを指定しなかった 場合、ログレベルはdebugとなります。
.RE
.PP
\fB\-f\fR \fI設定ファイル\fR
.RS 4
起動時に読み込む設定ファイルを指定します．
.RE
.PP
\fB\-p\fR \fIポート番号\fR
.RS 4
gfmdが利用するTCPのポート番号を指定します。
.RE
.PP
\fB\-s\fR \fIsyslogファシリティ\fR
.RS 4
gfmdがエラー報告に用いるsyslogのファシリティを指定します。省略 した場合には、local0を使用します。
.RE
.PP
\fB\-v\fR
.RS 4
認証処理に関するログを詳しく出力します。 GSI認証の問題を解決する場合に有用なオプションです。
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します。
.RE
.SH "FILES"
.PP
%%SYSCONFDIR%%/gfmd\&.conf
.RS 4
gfmdが参照する設定ファイルです。
.RE
.SH "SEE ALSO"
.PP

\fBgfarm2.conf\fR(5)
