'\" t
.\"     Title: gfsd
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 5 March 2016
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFSD" "8" "5 March 2016" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfsd \- Gfarmファイルシステム・デーモン
.SH "SYNOPSIS"
.HP \w'\fBgfsd\fR\ 'u
\fBgfsd\fR [\fIオプション\fR]
.SH "DESCRIPTION"
.PP
gfsdは、Gfarmライブラリと協調して動作し、Gfarmファイルシステ ムを実現するデーモンプログラムです。 gfsdはファイルシステムノードの全ホスト上で、 root権限であらかじめ立ち上げておく必要があります。
.PP
gfsdが提供するのは、ファイルの実体へのアクセスです。 gfsd が利用するポート番号は、gfmd が管理するメタデータから取得します。
.PP
gfsdはユーザ権限で動作させることも可能ですが，この場合他のユーザはこ のgfsdを利用することができません。 詳細はSETUP\&.private\&.jaを参照してください。
.SH "OPTIONS"
.PP
\fB\-L\fR \fIログレベル\fR
.RS 4
このオプションで指定したレベル以上の優先度のログを出力します。 指定できる値はgfarm2\&.conf(5)のlog_levelの項を参照してください。
.RE
.PP
\fB\-P\fR \fIPIDファイル\fR
.RS 4
gfsdのprocess IDを、指定したファイルに記録します。
.RE
.PP
\fB\-c\fR
.RS 4
起動時に、スプールディレクトリの検査を行います。ファイルシステムノード のホスト名が変わったときに利用すると、正しく格納されているファイルをメ タデータサーバに登録することができます。
.sp
\fB\-c\fRオプションを2回指定すると(または
\fB\-cc\fRオプション)、メタデータサーバに登録されていない無効 なファイルを消去することができます。
.sp
\fB\-c\fRオプションを3回指定すると(または
\fB\-ccc\fRオプション)、メタデータサーバに登録されていない無 効なファイルをGfarmファイルシステムのlost+foundディクトリに移動すること ができます。さらに、ファイルシステムノード上に存在しないファイルを指し ている、無効なメタデータを削除します。標準でこの動作です。
.RE
.PP
\fB\-d\fR
.RS 4
デバッグオプションです。デーモンとしてではなく、フォアグラウンド・ プロセスとして立ち上がります。
.sp
このオプションを指定し、かつ\fB\-L\fRオプションを指定しなかった 場合、ログレベルはdebugとなります。
.RE
.PP
\fB\-f\fR \fI設定ファイル\fR
.RS 4
起動時に読み込む設定ファイルを指定します。
.RE
.PP
\fB\-h\fR \fIホスト名\fR
.RS 4
自ホストのカノニカルなホスト名を指定します．
.RE
.PP
\fB\-l\fR \fIIPアドレス\fR
.RS 4
gfsdがTCPおよびUDPの要求を受け付けるIPアドレスを指定します。 オプション省略時は、そのホストの全てのIPアドレスで受け付けます。 このオプションは、一つのノードで複数のスプールを提供する場合に、 それぞれのスプールごとに、別々のIPアドレスを使ってgfsdを起動する ために用います。
.RE
.PP
\fB\-r\fR \fIスプール・ディレクトリ\fR
.RS 4
gfsdが、ファイルの実体を保持するディレクトリ名を指定します。 このオプションを複数回（最大5回まで）指定することにより複数のディレクトリを指定可能です。
.RE
.PP
\fB\-s\fR \fIsyslogファシリティ\fR
.RS 4
gfsdがエラー報告に用いるsyslogのファシリティを指定します。省略 した場合には、local0を使用します。
.RE
.PP
\fB\-v\fR
.RS 4
認証処理に関するログを詳しく出力します。 GSI認証の問題を解決する場合に有用なオプションです。
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します。
.RE
.SH "FILES"
.PP
%%SYSCONFDIR%%/gfarm2\&.conf
.RS 4
gfsdが参照する設定ファイルです。
.RE
.SH "SEE ALSO"
.PP
\fBgfarm2.conf\fR(5)
