top_builddir = ../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

datadir=$(default_datadir)/gfarm/systest/scenarios

DATA =	$(srcdir)/gfarm_v2

include $(top_srcdir)/makes/data.mk
