top_builddir = ../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

datadir=$(default_datadir)/gfarm/systest/scenarios/gfarm_v2

DATA =	$(srcdir)/configuration $(srcdir)/failover

include $(top_srcdir)/makes/data.mk
