#!/bin/sh

PROG=`basename $0`

usage() {
	exec >&2
	echo "Usage: $PROG [ -v ] FILE   - display NCOPY of FILE [or parent directory]"
	echo "       $PROG -s NCOPY FILE - set NCOPY of FILE"
	echo "       $PROG -r FILE       - remove NCOPY of FILE"
	echo "       $PROG -c FILE       - display number of replicas of FILE"
	echo "       $PROG -w FILE       - wait until replicas are created"
	exit 2
}

getxattr() {
    attr=$1
    p=$2
    v=`(getfattr -n $attr $p) 2>/dev/null | sed -n s/$attr'="\(.*\)"/\1/p'`
    [ X"$v" = X ] && v=$p
    echo $v
}

realpath() {
    getxattr gfarm2fs.path $1
}

realurl() {
    getxattr gfarm2fs.url $1
}

MODE=GET
VERBOSE=false
case $1 in
-s)
	shift
	NCOPY=`echo $1 | tr -cd '[:digit:]'`
	[ X"$NCOPY" = X ] && usage
	shift
	MODE=SET
	;;
-c)
	shift
	MODE=COUNT
	;;
-r)
	shift
	MODE=REMOVE
	;;
-w)
	shift
	MODE=WAIT
	;;
-v)
	shift
	VERBOSE=true
	;;
-*)
	usage
	;;
esac

[ X"$1" = X ] && usage
FILE=`realpath $1`
URL=`realurl $1`

case $MODE in
SET)
	printf '%s' $NCOPY | gfxattr -s $URL gfarm.ncopy
	;;
GET)
	f=$FILE
	u=$URL
	out=`gfxattr -g $u gfarm.ncopy 2>&1`
	rv=$?
	while [ $rv -ne 0 -a "$out" = "no such object" ]; do
		[ $f = "." -o $f = "/" ] && break
		$VERBOSE && echo >&2 $u: $out
		f=`dirname $f 2>&1`
		u=`gfpath -d $u 2>&1`
		[ $? -ne 0 ] && break
		out=`gfxattr -g $u gfarm.ncopy 2>&1`
		rv=$?
	done
	if [ $rv -ne 0 ]; then
		$VERBOSE && printf '%s' >&2 "$u: "
		echo >&2 $out
	else
		$VERBOSE && printf '%s' "$u: "
		echo $out
	fi
	exit $rv
	;;
REMOVE)
	gfxattr -r $URL gfarm.ncopy
	;;
COUNT)
	out=`gfwhere $URL`
	[ $? -eq 0 ] && echo $out | wc -w
	;;
WAIT)
	if gftest -f $URL; then
		ncopy=`gfncopy $URL`
		count=`gfstat -c $URL`
		while [ $count -lt $ncopy ]; do
			sleep 1
			count=`gfstat -c $URL`
		done
	fi
	;;
esac
