top_builddir = ../../../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

LIBRARY = libsysdep.la
LIBRARY_RESULT = # do not install

SRCS = dummy.c
OBJS = dummy.lo

all:	$(LIBRARY)

include $(top_srcdir)/makes/lib.mk
