.Id $Id$
.TH gfarm_strings_free_deeply 3 "1 May 2002"

.SH NAME

gfarm_strings_free_deeply \- free an array of strings

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B void
.br
.BI "gfarm_strings_free_deeply(int " n ,
.BI "char **" strings );

.SH DESCRIPTION

\fBgfarm_string_free_deeply()\fP frees the memory space of an array of
strings \fIstrings\fP with the size \fIn\fP.  This also frees every
string in the array.
