.Id $Id$
.TH gfarm_url_hosts_schedule 3 "1 May 2002"

.SH NAME

gfarm_url_hosts_schedule \- schedule filesystem nodes using file-affinity scheduling

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B "char *"
.br
.BI "gfarm_url_hosts_schedule(char *" gfarm_url ,
.BI "char *" option ,
.in +.5i
.BI "int *" nhostsp ,
.BI "char ***" hostsp );
.in

.SH DESCRIPTION

The \fBgfarm_url_hosts_schedule()\fP function schedules filesystem
nodes using file-affinity scheduling with a Gfarm file
\fIgfarm_url\fP, and returns an array of filesystem hostnames
\fIhostsp\fP and the number of scheduled hosts \fInhostsp\fP.  The
returned array of hostnames \fIhostsp\fP should be free'ed with
gfarm_strings_free_deeply(3).

.SH "RETURN VALUES"

.TP
.SB NULL
.br
The function terminated successfully.
.TP
.SB GFARM_ERR_NO_MEMORY
.br
Insufficient memory was available.
.TP
Others
.br
An error except the above occurred.  The reason is shown by its
pointed strings.

.SH NOTES

The argument
.I option
is reserved to specify options for scheduling, although it is not used
in the current implementation.
