.Id $Id$
.TH gfs_pio_seek 3 "1 May 2002"

.SH NAME

gfs_pio_seek \- reposition a stream

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B "char *"
.BI "gfs_pio_seek(GFS_File " gf ,
.BI "file_offset_t " offset ,
.in +.5i
.BI "int " whence ,
.BI "file_offset_t *" result );
.in

.SH DESCRIPTION

The \fBgfs_pio_seek()\fP function sets the file position indicator for
the file \fIgf\fP.  The new position, measured in bytes, is obtained
by adding \fIoffset\fP bytes to the position specified by
\fIwhence\fP.  If \fIwhence\fP is set to 0, 1, or 2, the offset is
relative to the start of the file, the current position indicator, or
end-of-file, respectively.  When \fIresult\fP is not NULL, the new
position returns to the address pointed by \fIresult\fP.

.SH "RETURN VALUES"

.TP
.SB NULL
.br
The function terminated successfully.
.TP
.SB GFARM_ERR_NO_MEMORY
.br
Insufficient memory was available.
.TP
Others
.br
An error except the above occurred.  The reason is shown by its
pointed strings.

.SH "SEE ALSO"
.BR gfs_pio_create (3),
.BR gfs_pio_open (3)
