.Id $Id$
.TH gfs_readdir 3 "1 May 2002"

.SH NAME

gfs_readdir \- read directory entry

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B "char *"
.br
.BI "gfs_readdir(GFS_Dir " dir ,
.BI "char **" entryp );

.SH DESCRIPTION

NOT SUPPORTED YET.

The \fBgfs_readdir()\fP function reads a directory entry from
\fIdir\fP, and returns the pointer of the entry to the address pointed
to by \fIentryp\fP.  The buffer pointed to by \fIentryp\fP is
destroyed when calling succeeding gfs_readdir() or gfs_closedir() with
the same argument \fIdir\fP.

.SH "RETURN VALUES"

.TP
.SB NULL
.br
The function terminated successfully.
.TP
Others
.br
An error except the above occurred.  The reason is shown by its
pointed strings.

.SH "SEE ALSO"
.BR gfs_closedir (3),
.BR gfs_opendir (3),
.BR gfs_readdir (3)
