'\" t
.\"     Title: gfs_stat_free
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 24 Jun 2019
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFS_STAT_FREE" "3" "24 Jun 2019" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfs_stat_free \- free dynamic memory of file status
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gfarm/gfarm\&.h>
.fi
.ft
.HP \w'void\ gfs_stat_free('u
.BI "void\ gfs_stat_free(struct\ gfs_stat\ *\ " "status" ");"
.SH "DESCRIPTION"
.PP
\fBgfs_stat_free()\fR
frees the memory space of file status
\fIstatus\fR
allocated by gfs_stat(3)\&.
.SH "SEE ALSO"
.PP
\fBgfs_stat\fR(3)
