'\" t
.\"     Title: gfs_acl_equiv_mode
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 14 Feb 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFS_ACL_EQUIV_MODE" "3" "14 Feb 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfs_acl_equiv_mode \- check for an equivalent Gfarm ACL
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gfarm/gfarm\&.h>
.fi
.ft
.HP \w'gfarm_error_t\ gfs_acl_equiv_mode('u
.BI "gfarm_error_t\ gfs_acl_equiv_mode(gfarm_acl_t\ " "acl" ", gfarm_mode_t\ *" "mode_p" ", int\ *" "is_not_equiv_p" ");"
.SH "INPUT ARGUMENTS"
.PP
\fIacl\fR
.RS 4
An ACL structure type\&.
.RE
.PP
\fImode_p\fR
.RS 4
If the pointer
\fImode_p\fR
is not NULL, the value pointed to by
\fImode_p\fR
is set to the value that defines the same owner/group/other permissions as contained in the ACL\&.
.RE
.PP
\fIis_not_equiv_p\fR
.RS 4
If the pointer
\fIis_not_equiv_p\fR
is not NULL, the value pointed to by
\fIis_not_equiv_p\fR
is set to 0 (the
\fIacl\fR
is an equivalent ACL) or 1 (the
\fIacl\fR
is not an equivalent ACL)\&.
.RE
.SH "RETURN VALUES"
.PP
\fBGFARM_ERR_NO_ERROR\fR
.RS 4
The function terminated successfully\&.
.RE
.PP
Others
.RS 4
An error except the above occurred\&. The reason is shown by
\fBgfarm_error_string\fR(3)\&.
.RE
.SH "SEE ALSO"
.PP

\fBgfs_acl_from_mode\fR(3)
