'\" t
.\"     Title: gfs_acl_cmp
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 14 Feb 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFS_ACL_CMP" "3" "14 Feb 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfs_acl_cmp \- compare two Gfarm ACLs
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gfarm/gfarm\&.h>
.fi
.ft
.HP \w'int\ gfs_acl_cmp('u
.BI "int\ gfs_acl_cmp(gfarm_acl_t\ " "acl1" ", gfarm_acl_t\ " "acl2" ");"
.SH "INPUT ARGUMENTS"
.PP
\fIacl1\fR, \fIacl2\fR
.RS 4
An ACL structure type which is sorted\&.
.RE
.SH "RETURN VALUES"
.PP
If the two ACLs acl1 and acl2 are equal, this function returns 0\&. And if they differ, this function returns 1\&.
.SH "SEE ALSO"
.PP

\fBgfs_acl_dup\fR(3),
\fBgfs_acl_sort\fR(3),
\fBgfs_acl_from_text\fR(3),
\fBgfs_acl_get_file\fR(3),
\fBgfs_acl_init\fR(3)
