.Id $Id$
.TH gfs_stat_free 3 "1 May 2002"

.SH NAME

gfs_stat_free \- free dynamic memory of file status

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B "void"
.br
.BI "gfs_stat_free(struct gfs_stat *" status );

.SH DESCRIPTION

\fBgfs_stat_free()\fP frees frees the memory space of file status
\fIstatus\fP allocated by gfs_stat(3).

.SH "SEE ALSO"
.BR gfs_stat (3)
