'\" t
.\"     Title: gfs_pio_write
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 27 Jun 2010
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFS_PIO_WRITE" "3" "27 Jun 2010" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfs_pio_write \- write to a file
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gfarm/gfarm\&.h>
.fi
.ft
.HP \w'gfarm_error_t\ gfs_pio_write('u
.BI "gfarm_error_t\ gfs_pio_write(GFS_File\ " "gf" ", const\ void\ *\ " "buffer" ", int\ " "size" ", int\ *\ " "np" ");"
.SH "DESCRIPTION"
.PP
\fBgfs_pio_write()\fR
writes up to
\fIsize\fR
bytes to the file
\fIgf\fR
from the buffer starting at
\fIbuffer\fR\&. It returns the number of bytes written to the address pointed by
\fInp\fR\&.
.SH "RETURN VALUES"
.PP
\fBGFARM_ERR_NO_ERROR\fR
.RS 4
The function terminated successfully\&.
.RE
.PP
\fBGFARM_ERR_OPERATION_NOT_PERMITTED\fR
.RS 4
\fIgf\fR
does not specify a regular file\&.
.RE
.PP
\fBGFARM_ERR_BAD_FILE_DESCRIPTOR\fR
.RS 4
The file descripter specified by
\fIgfp\fR
is not a valid or is not open for writing\&.
.RE
.PP
\fBGFARM_ERR_NO_SPACE\fR
.RS 4
The file system node has no room to store data
.RE
.PP
\fBGFARM_ERR_NO_FILE_SYSTEM_NODE\fR
.RS 4
There is no available file system node\&.
.RE
.PP
\fBGFARM_ERR_NO_MEMORY\fR
.RS 4
Insufficient memory was available\&.
.RE
.PP
Others
.RS 4
An error except the above occurred\&. The reason is shown by
\fBgfarm_error_string\fR(3)\&.
.RE
.SH "SEE ALSO"
.PP

\fBgfs_pio_create\fR(3),
\fBgfs_pio_flush\fR(3),
\fBgfs_pio_open\fR(3)
