.Id $Id$
.TH gfs_pio_read 3 "1 May 2002"

.SH NAME

gfs_pio_read \- binary stream input

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B "char *"
.br
.BI "gfs_pio_read(GFS_File " gf ,
.BI "void *" buffer ,
.BI "int " size ,
.BI "int *" np );

.SH DESCRIPTION

\fBgfs_pio_read()\fP attempts to read up to \fIsize\fP bytes from the
file referenced by \fIgf\fP into the buffer starting at \fIbuffer\fP,
and returns the number of bytes read to the address pointed by
\fInp\fP.  On end of file, the number of bytes read is zero.

.SH "RETURN VALUES"

.TP
.SB NULL
.br
The function terminated successfully.
.TP
.SB GFARM_ERR_NO_MEMORY
.br
Insufficient memory was available.
.TP
Others
.br
An error except the above occurred.  The reason is shown by its
pointed strings.

.SH "SEE ALSO"
.BR gfs_pio_create (3),
.BR gfs_pio_open (3)
