'\" t
.\"     Title: gfs_acl_to_xattr_value
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 14 Feb 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFS_ACL_TO_XATTR_VAL" "3" "14 Feb 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfs_acl_to_xattr_value \- convert a Gfarm ACL to binary data for Gfarm extended attribute
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gfarm/gfarm\&.h>
.fi
.ft
.HP \w'gfarm_error_t\ gfs_acl_to_xattr_value('u
.BI "gfarm_error_t\ gfs_acl_to_xattr_value(gfarm_acl_t\ " "acl" ", void\ **" "xattr_value_p" ", size_t\ *" "size_p" ");"
.SH "INPUT ARGUMENTS"
.PP
\fIacl\fR
.RS 4
An ACL structure type which is sorted\&.
.RE
.PP
\fIxattr_value_p\fR
.RS 4
A pointer to the converted binary data\&.
.RE
.PP
\fIsize_p\fR
.RS 4
A value pointed to by
\fIsize_p\fR
is set to the length of the converted binary data\&.
.RE
.SH "RETURN VALUES"
.PP
\fBGFARM_ERR_NO_ERROR\fR
.RS 4
The function terminated successfully\&.
.RE
.PP
\fBGFARM_ERR_NO_MEMORY\fR
.RS 4
Insufficient memory was available\&.
.RE
.PP
Others
.RS 4
An error except the above occurred\&. The reason is shown by
\fBgfarm_error_string\fR(3)\&.
.RE
.SH "SEE ALSO"
.PP

\fBgfs_acl_sort\fR(3),
\fBgfs_acl_set_file\fR(3),
\fBgfs_setxattr\fR(3),
\fBgfs_acl_from_xattr_value\fR(3)
