.Id $Id$
.TH gfs_rename 3 "1 May 2002"

.SH NAME

gfs_rename \- change the name or location of a file

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B "char *"
.br
.BI "gfs_rename(char *" gfarm_url_from ,
.BI "char *" gfarm_url_to );

.SH DESCRIPTION

\fBgfs_rename\fP renames \fIgfarm_url_from\fP to \fIgfarm_url_to\fP.

.SH "RETURN VALUES"

.TP
.SB NULL
.br
The function terminated successfully.
.TP
.SB GFARM_ERR_NO_MEMORY
.br
Insufficient memory was available.
.TP
.SB GFARM_ERR_AUTHENTICATION
.br
User authentication failed when connecting to gfmd(8).
.TP
.SB GFARM_ERR_PERMISSION_DENIED
.br
\fIgfarm_url_from\fP or \fIgfarm_url_from\fP
points outside your accessible address space.
.TP
.SB GFARM_ERR_ALREADY_EXISTS
\fIgfarm_url_to\fP already exists.  This includes the case where
\fIgfarm_url\fP is a symbolic link, dangling or not.
.TP
.SB GFARM_ERR_INVALID_ARGUMENT
.br
\fIgfarm_url_to\fP contained a path prefix of \fIgfarm_url_from\fP,
more generally, an attempt was made to make a directory a subdirectory
of itself.
.TP
.SB GFARM_ERR_NO_SUCH_OBJECT
.br
\fIgfarm_url_from\fP does not exist.
.\" .TP
.\" .SB GFARM_ERR_READ_ONLY_FILE_SYSTEM
.\" .br
.\" The named file resides on a read-only file system.
.TP
Others
.br
An error except the above occurred.  The reason is shown by its
pointed strings.
