'\" t
.\"     Title: gfs_acl_get_perm
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 14 Feb 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFS_ACL_GET_PERM" "3" "14 Feb 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfs_acl_get_perm \- test for a permission in a Gfarm ACL permission set
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gfarm/gfarm\&.h>
.fi
.ft
.HP \w'gfarm_error_t\ gfs_acl_get_perm('u
.BI "gfarm_error_t\ gfs_acl_get_perm(gfarm_acl_permset_t\ " "permset_d" ", gfarm_acl_perm_t\ " "perm" ", int\ *" "bool_p" ");"
.SH "INPUT ARGUMENTS"
.PP
\fIpermset_d\fR
.RS 4
An ACL permission set\&.
.RE
.PP
\fIperm\fR
.RS 4
GFARM_ACL_READ or GFARM_ACL_WRITE or GFARM_ACL_EXECUTE\&.
.RE
.PP
\fIbool_p\fR
.RS 4
If *bool_p is 1, the ACL permission set has the perm\&. If *bool_p is 0, the ACL permission set does not have the perm\&.
.RE
.SH "RETURN VALUES"
.PP
\fBGFARM_ERR_NO_ERROR\fR
.RS 4
The function terminated successfully\&.
.RE
.PP
Others
.RS 4
An error except the above occurred\&. The reason is shown by
\fBgfarm_error_string\fR(3)\&.
.RE
.SH "SEE ALSO"
.PP

\fBgfs_acl_add_perm\fR(3),
\fBgfs_acl_clear_perms\fR(3),
\fBgfs_acl_delete_perm\fR(3),
\fBgfs_acl_get_permset\fR(3),
\fBgfs_acl_set_permset\fR(3)
