'\" t
.\"     Title: gfs_acl_set_tag_type
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 14 Feb 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFS_ACL_SET_TAG_TYPE" "3" "14 Feb 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfs_acl_set_tag_type \- set the tag type of a Gfarm ACL entry
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gfarm/gfarm\&.h>
.fi
.ft
.HP \w'gfarm_error_t\ gfs_acl_set_tag_type('u
.BI "gfarm_error_t\ gfs_acl_set_tag_type(gfarm_acl_entry_t\ " "entry_d" ", gfarm_acl_tag_t\ " "tag_type" ");"
.SH "INPUT ARGUMENTS"
.PP
\fIentry_d\fR
.RS 4
An ACL entry\&.
.RE
.PP
\fItag_type\fR
.RS 4
An ACL tag type\&.
.RE
.SH "RETURN VALUES"
.PP
\fBGFARM_ERR_NO_ERROR\fR
.RS 4
The function terminated successfully\&.
.RE
.PP
Others
.RS 4
An error except the above occurred\&. The reason is shown by
\fBgfarm_error_string\fR(3)\&.
.RE
.SH "SEE ALSO"
.PP

\fBgfs_acl_create_entry\fR(3),
\fBgfs_acl_get_entry\fR(3),
\fBgfs_acl_get_permset\fR(3),
\fBgfs_acl_set_permset\fR(3),
\fBgfs_acl_get_tag_type\fR(3),
\fBgfs_acl_get_qualifier\fR(3),
\fBgfs_acl_set_qualifier\fR(3)
