'\" t
.\"     Title: gfs_unlink
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 20 Jun 2019
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFS_UNLINK" "3" "20 Jun 2019" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfs_unlink \- delete a file
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gfarm/gfarm\&.h>
.fi
.ft
.HP \w'gfarm_error_t\ gfs_unlink('u
.BI "gfarm_error_t\ gfs_unlink(const\ char\ *\ " "gfarm_url" ");"
.SH "DESCRIPTION"
.PP
\fBgfs_unlink()\fR
deletes the file whose name is the string specified by
\fIgfarm_url\fR\&.
.SH "RETURN VALUES"
.PP
\fBGFARM_ERR_NO_ERROR\fR
.RS 4
The function terminated successfully\&.
.RE
.PP
\fBGFARM_ERR_NO_MEMORY\fR
.RS 4
Insufficient memory was available\&.
.RE
.PP
\fBGFARM_ERR_AUTHENTICATION\fR
.RS 4
User authentication failed when connecting to gfmd(8)\&.
.RE
.PP
\fBGFARM_ERR_PERMISSION_DENIED\fR
.RS 4
\fIgfarm_url\fR
points outside your accessible address space\&.
.RE
.PP
\fBGFARM_ERR_NO_SUCH_OBJECT\fR
.RS 4
\fIgfarm_url\fR
does not exist\&.
.RE
.PP
\fBGFARM_ERR_NOT_A_DIRECTORY\fR
.RS 4
A component of the path prefix is not a directory\&.
.RE
.PP
Others
.RS 4
An error except the above occurred\&. The reason is shown by
\fBgfarm_error_string\fR(3)\&.
.RE
