.Id $Id$
.TH gfs_pio_set_local 3 "1 May 2002"

.SH NAME

gfs_pio_set_local \- initialize the local file view environment

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B "char *"
.br
.BI "gfs_pio_set_local(int " node ,
.BI "int " nnode );

.SH DESCRIPTION

\fBgfs_pio_set_local()\fP initializes the environment for the local file
view with the node number \fInode\fP and the total number of nodes
\fInnode\fP.

.SH "RETURN VALUES"

.TP
.SB NULL
.br
The function terminated successfully.
.TP
Others
.br
An error except the above occurred.  The reason is shown by its
pointed strings.

.SH "SEE ALSO"
.BR gfs_pio_set_view_local (3),
.BR gfs_pio_set_view_index (3)
