'\" t
.\"     Title: gfs_acl_get_entry
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 14 Feb 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFS_ACL_GET_ENTRY" "3" "14 Feb 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfs_acl_get_entry \- get a Gfarm ACL entry
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gfarm/gfarm\&.h>
.fi
.ft
.HP \w'gfarm_error_t\ gfs_acl_get_entry('u
.BI "gfarm_error_t\ gfs_acl_get_entry(gfarm_acl_t\ " "acl" ", int\ " "entry_id" ", gfarm_acl_entry_t\ *" "entry_p" ");"
.SH "INPUT ARGUMENTS"
.PP
\fIacl\fR
.RS 4
An ACL structure type\&.
.RE
.PP
\fIentry_id\fR
.RS 4
GFARM_ACL_FIRST_ENTRY (to get first ACL entry) or GFARM_ACL_NEXT_ENTRY (to get next ACL entry)\&.
.RE
.PP
\fIentry_p\fR
.RS 4
Pointer to get the ACL entry\&.
.RE
.SH "RETURN VALUES"
.PP
\fBGFARM_ERR_NO_ERROR\fR
.RS 4
The function terminated successfully\&.
.RE
.PP
\fBGFARM_ERR_NO_SUCH_OBJECT\fR
.RS 4
The ACL does not have ACL entries anymore\&. (End of ACL)
.RE
.PP
Others
.RS 4
An error except the above occurred\&. The reason is shown by
\fBgfarm_error_string\fR(3)\&.
.RE
.SH "SEE ALSO"
.PP

\fBgfs_acl_calc_mask\fR(3),
\fBgfs_acl_create_entry\fR(3),
\fBgfs_acl_delete_entry\fR(3),
\fBgfs_acl_get_file\fR(3)
