.Id $Id$
.TH gfs_pio_eof 3 "1 May 2002"

.SH NAME

gfs_pio_eof \- check file status

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B int
.br
.BI "gfs_pio_eof(GFS_File " gf );

.SH DESCRIPTION

The function \fBgfs_pio_eof()\fP tests the end-of-file indicator for
the file pointed to by \fIgf\fP.

.SH "RETURN VALUES"

.TP
.SB zero
.br
The end-of-file indicator is not set.
.TP
non-zero
.br
The end-of-file indicator is set.

.SH "SEE ALSO"
.BR gfs_pio_create (3),
.BR gfs_pio_error (3),
.BR gfs_pio_open (3)
