'\" t
.\"     Title: gfmd
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 14 Feb 2008
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFMD" "8" "14 Feb 2008" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfmd \- Gfarm metadata server
.SH "SYNOPSIS"
.HP \w'\fBgfmd\fR\ 'u
\fBgfmd\fR [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
\fBgfmd\fR
is a Gfarm filesystem metadata server for accessing the filesystem metadata of the Gfarm filesystem\&.
\fBgfmd\fR
must be running on a metadata server node in advance\&.
.PP
It is possible for
\fBgfmd\fR
to be executed as a non\-privileged user process, although only the user that executes the
\fBgfmd\fR
can be authenticated\&. Other users cannot use it\&. For details, see SETUP\&.private\&.en document
.PP
To access gfmd, the hostname and the port number should be specified by the metadb_server_host and metadb_server_port statements, respectively, in
~/\&.gfarm2rc
or in
%%SYSCONFDIR%%/gfarm2\&.conf
on a client node\&.
.SH "OPTIONS"
.PP
\fB\-L\fR \fIlog\-level\fR
.RS 4
Specifies a log priority level\&. The log output, which priority is higher or equal to this level, will be sent to syslog or standard error\&. Please refer gfarm2\&.conf(5) for the priority levels which can be specified by this option\&.
.RE
.PP
\fB\-P\fR \fIpid\-file\fR
.RS 4
Specifies a file name to be used to record the process ID of gfmd\&.
.RE
.PP
\fB\-S\fR
.RS 4
Runs as slave forcedly, even if the gfmd is set to default master\&.
.RE
.PP
\fB\-d\fR
.RS 4
Specifies the debug mode\&. With the \-d option, gfmd runs as a foreground process, not a daemon\&.
.sp
If this option is specified and
\fB\-L\fR
is not specified, the log level is set to "debug"\&.
.RE
.PP
\fB\-f\fR \fIconfig\-file\fR
.RS 4
Specifies a configuration file that is read instead of the default configuration file\&.
.RE
.PP
\fB\-p\fR \fIport\fR
.RS 4
Specifies a port number to be used by gfmd\&.
.RE
.PP
\fB\-s\fR \fIsyslog\-facility\fR
.RS 4
Specifies a syslog facility to report errors encountered by gfmd\&. By default, local0 is used\&.
.RE
.PP
\fB\-t\fR
.RS 4
Enables an audit log feature for file creation, modification and removal\&.
.RE
.PP
\fB\-v\fR
.RS 4
Makes gfmd output verbose log message on authentication\&. This is useful, when one has to resolve an issue about GSI authenticaion\&.
.RE
.PP
\fB\-?\fR
.RS 4
Displays a list of command options\&.
.RE
.SH "FILES"
.PP
%%SYSCONFDIR%%/gfmd\&.conf
.RS 4
configuration file
.RE
.SH "SEE ALSO"
.PP
\fBgfarm2.conf\fR(5)
