all:
	cd gfimport_fixed && make $@
	cd gfimport_text && make $@
	cd gfgrep && make $@
	cd gfwc && make $@

install clean veryclean distclean:
	cd gfimport_fixed && make $@
	cd gfimport_text && make $@
	cd gfgrep && make $@
	cd gfwc && make $@
