top_builddir = ..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

SUBDIRS = \
	gfchmod \
	gfchown \
	gfexport \
	gfhost \
	gfkey \
	gfls \
	gfmkdir \
	gfmv \
	gfreg \
	gfrm \
	gfrmdir \
	gfuser \
	config-gfarm

#	gfdf \
#	gfexec \
#	gfpwd \
#	gfrcmd \
#	gfrep \
#	gfsched \
#	gfsck \
#	gfsetdir \
#	gfstat \
#	gfmpirun \
#	gfps \
#	gfrun \
#	gfwhere \
#	gfwhoami \
#	example \

include $(top_srcdir)/makes/subdir.mk
