top_builddir = ..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

SUBDIRS = \
	gfchmod \
	gfchown \
	gfdf \
	gfdump \
	gfexport \
	gffindxmlattr \
	gfgroup \
	gfhost \
	gfkey \
	gfln \
	gfls \
	gfmkdir \
	gfmv \
	gfreg \
	gfrep \
	gfrm \
	gfrmdir \
	gfstat \
	gfstatus \
	gfuser \
	gfvoms-sync \
	gfwhere \
	gfwhoami \
	gfxattr \
	config-gfarm

#	gfexec \
#	gfifo \
#	gfpwd \
#	gfrcmd \
#	gfsched \
#	gfsck \
#	gfsetdir \
#	gfmpirun \
#	gfps \
#	gfq \
#	gfrun \
#	gftest \
#	gfusage \
#	example \

include $(top_srcdir)/makes/subdir.mk
