top_builddir = ..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

GLOBUS_SUBDIRS = libgfarm/gfsl

SUBDIRS = \
	libgfarm \
	gfs_hook \
	$(globus_subdirs)

include $(top_srcdir)/makes/subdir.mk
