top_objdir = ..
top_srcdir = $(top_objdir)
srcdir = .

include $(top_srcdir)/makes/var.mk

GLOBUS_SUBDIRS = libgfsl

SUBDIRS = \
	$(globus_subdirs) \
	libgfarm \
	gfs_hook

include $(top_srcdir)/makes/subdir.mk
