top_builddir = ..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

SUBDIRS = \
	bwlat-syscache \
	nconnect \
	thput-fsstripe \
	thput-fsys \
	thput-gfpio \
	gfiops

include $(top_srcdir)/makes/subdir.mk
