#!/bin/sh

FILE=$1

[ X"$FILE" = X ] && exit 1
[ -f $FILE ] || exit 1

pad() {
	d=$1===
	c=$(echo -n $d | wc -c)
	c=$((c / 4 * 4))
	echo $d | cut -b -$c
}

for i in 1 2; do
	data=$(cut -d. -f $i $FILE)
	pad $data | base64 -d | jq
done
