# $Id: Makefile 5520 2011-09-26 07:40:38Z m-kasahr $

top_builddir = ../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

datadir=$(default_datadir)/gfarm/ganglia

DATA =	$(srcdir)/gfarm_iostat.py \
	$(srcdir)/gfarm_gfmd.pyconf \
	$(srcdir)/gfarm_gfsd.pyconf

include $(top_srcdir)/makes/data.mk

