# $Id$

top_builddir = ../../../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

htmldir=$(default_htmldir)/ja/user

HTML =	export-gfarm.html \
	index.html \
	nfs-gfarmfs.html \
	samba-gfarmfs.html \
	samba-hook.html \
	smboverssh.html

include $(top_srcdir)/makes/html.mk
