# $Id$

top_builddir = ../../../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

htmldir=$(default_htmldir)/ja/user

HTML = index.html samba-gfarmfs.html samba-hook.html

include $(top_srcdir)/makes/html.mk
