DOCBOOK = \
	gfarm.3 \
	gfarm_initialize.3 \
	gfarm_terminate.3 \
	gfs_acl_init.3 \
	gfs_acl_dup.3 \
	gfs_acl_free.3 \
	gfs_acl_create_entry.3 \
	gfs_acl_delete_entry.3 \
	gfs_acl_get_entry.3 \
	gfs_acl_valid.3 \
	gfs_acl_calc_mask.3 \
	gfs_acl_get_permset.3 \
	gfs_acl_set_permset.3 \
	gfs_acl_add_perm.3 \
	gfs_acl_clear_perms.3 \
	gfs_acl_delete_perm.3 \
	gfs_acl_get_qualifier.3 \
	gfs_acl_set_qualifier.3 \
	gfs_acl_get_tag_type.3 \
	gfs_acl_set_tag_type.3 \
	gfs_acl_delete_def_file.3 \
	gfs_acl_get_file.3 \
	gfs_acl_set_file.3 \
	gfs_acl_to_text.3 \
	gfs_acl_from_text.3 \
	gfs_acl_get_perm.3 \
	gfs_acl_error.3 \
	gfs_acl_check.3 \
	gfs_acl_entries.3 \
	gfs_acl_equiv_mode.3 \
	gfs_acl_cmp.3 \
	gfs_acl_from_mode.3 \
	gfs_acl_to_any_text.3 \
	gfs_acl_to_xattr_value.3 \
	gfs_acl_from_xattr_value.3 \
	gfs_acl_sort.3 \
	gfs_acl_from_text_with_default.3 \
	gfs_pio_close.3 \
	gfs_pio_create.3 \
	gfs_pio_open.3 \
	gfs_pio_read.3 \
	gfs_pio_write.3 \
	gfs_pio_recvfile.3 \
	gfs_pio_sendfile.3

#DOCBOOK = \
#	gfarm_strings_free_deeply.3 \
#	gfarm_url_fragments_replicate.3 \
#	gfarm_url_hosts_schedule.3 \
#	gfarm_url_section_replicate_from_to.3 \
#	gfarm_url_section_replicate_to.3 \
#	gfs_chdir.3 \
#	gfs_chmod.3 \
#	gfs_closedir.3 \
#	gfs_mkdir.3 \
#	gfs_opendir.3 \
#	gfs_pio_datasync.3 \
#	gfs_pio_eof.3 \
#	gfs_pio_error.3 \
#	gfs_pio_flush.3 \
#	gfs_pio_getc.3 \
#	gfs_pio_getline.3 \
#	gfs_pio_gets.3 \
#	gfs_pio_putc.3 \
#	gfs_pio_putline.3 \
#	gfs_pio_puts.3 \
#	gfs_pio_readdelim.3 \
#	gfs_pio_readline.3 \
#	gfs_pio_seek.3 \
#	gfs_pio_sync.3 \
#	gfs_pio_set_local.3 \
#	gfs_pio_set_view_index.3 \
#	gfs_pio_set_view_local.3 \
#	gfs_pio_truncate.3 \
#	gfs_pio_ungetc.3 \
#	gfs_readdir.3 \
#	gfs_realpath.3 \
#	gfs_rename.3 \
#	gfs_rmdir.3 \
#	gfs_stat.3 \
#	gfs_stat_free.3 \
#	gfs_unlink.3 \
#	gfs_unlink_section.3 \
#	gfs_utimes.3 \
#	gfs_glob_init.3 \
#	gfs_glob.3 \
#	gfs_glob_add.3 \
#	gfs_glob_free.3
