DOCBOOK = \
	gfchgrp.1 \
	gfchmod.1 \
	gfchown.1 \
	gfcksum.1 \
	gfdf.1 \
	gfedquota.1 \
	gfexport.1 \
	gffindxmlattr.1 \
	gfgetfacl.1 \
	gfgroup.1 \
	gfhost.1 \
	gfjournaladmin.1 \
	gfkey.1 \
	gfln.1 \
	gfls.1 \
	gfmdhost.1 \
	gfmkdir.1 \
	gfmv.1 \
	gfncopy.1 \
	gfpcopy.1 \
	gfprep.1 \
	gfquota.1 \
	gfquotacheck.1 \
	gfreg.1 \
	gfrep.1 \
	gfrm.1 \
	gfrmdir.1 \
	gfsched.1 \
	gfsetfacl.1 \
	gfstat.1 \
	gfstatus.1 \
	gfsudo.1 \
	gftest.1 \
	gfusage.1 \
	gfuser.1 \
	gfwhere.1 \
	gfwhoami.1 \
	gfxattr.1 \
	gfperf-autoreplica.1 \
	gfperf-copy.1 \
	gfperf-metadata.1 \
	gfperf-parallel-autoreplica.1 \
	gfperf-parallel-read.1 \
	gfperf-parallel-replica.1 \
	gfperf-parallel-write.1 \
	gfperf-read.1 \
	gfperf-replica.1 \
	gfperf-tree.1 \
	gfperf-wrapper.sh.1 \
	gfperf-write.1 \
	gfperf.rb.1 \
	gfspoolpath.1 \
	gfstress.rb.1 \
	gfservice.1 \
	gfservice-agent.1

#	gfarm_agent.1 \
#	gfcd.1 \
#	gfexec.1 \
#	gfgrep.1 \
#	gfimport_fixed.1 \
#	gfimport_text.1 \
#	gfmpirun_p4.1 \
#	gfps.1 \
#	gfpwd.1 \
#	gfrcmd.1 \
#	gfront.1 \
#	gfrun.1 \
#	gfsetdir.1 \
#	gfwc.1 \
