/*
 * $Id$
 */

enum gfarm_agent_proto_command {
	AGENT_PROTO_PATH_INFO_GET,
	AGENT_PROTO_PATH_INFO_SET,
	AGENT_PROTO_PATH_INFO_REPLACE,
	AGENT_PROTO_PATH_INFO_REMOVE,
	AGENT_PROTO_REALPATH_CANONICAL,
	AGENT_PROTO_GET_INO,
	AGENT_PROTO_OPENDIR,
	AGENT_PROTO_READDIR,
	AGENT_PROTO_CLOSEDIR,
	AGENT_PROTO_DIRNAME,
	AGENT_PROTO_UNCACHEDIR
};
