top_builddir = ../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

SCRIPTS= $(srcdir)/pcat $(srcdir)/pcp $(srcdir)/pdel $(srcdir)/pdist $(srcdir)/prun

include $(top_srcdir)/makes/script.mk
