#!/bin/sh
#
# gfspoolmd5 - calculate and check md5 message digest of files in a spool
#
# Usage: gfspoolmd5 [spool_root] 2> log

PROG=`basename $0`

check_md5()
{
	file=$1
	inumgen=`echo $file | sed 's/.*data//' | sed 's|/||g'`
	[ $? -ne 0 ] && return
	inum_hex=`echo $inumgen | sed 's/.\{16\}$//'`
	[ $? -ne 0 ] && return
	inum=`printf "%d" 0x$inum_hex`
	[ $? -ne 0 ] && return
	gen_hex=`echo $inumgen | sed 's/^.\{16\}//'`
	[ $? -ne 0 ] && return
	gen=`printf "%d" 0x$gen_hex`
	[ $? -ne 0 ] && return

	md5_file=`md5sum $file | awk '{ print $1 }'`
	[ $? -ne 0 ] && return
	echo -n $md5_file | gfxattr -Isc -G $gen $inum gfarm.md5 >/dev/null 2>&1
	[ $? -eq 0 ] && return
	md5_mds=`gfxattr -Ig -G $gen $inum gfarm.md5 2>&1`
	if [ $? -ne 0 ]; then
		echo >&2 $file: $md5_mds
	elif [ "$md5_file" != "$md5_mds" ]; then
		echo >&2 $file: md5 digest differs: file $md5_file mds $md5_mds
	fi
}

ABORT()
{
	[ $# -gt 0 ] && echo >&2 $PROG: $*
	echo >&2 "Usage: $PROG [spool_root] 2> log"
	exit 1
}

# gfarmroot?
if gfgroup -l gfarmroot | grep "\b`gfwhoami`\b" > /dev/null
then
	:
else
	ABORT You are not gfarmroot
fi

# spool_root
[ X"$1" != X ] && spool_root=$1
: ${spool_root=`ps -ef|grep gfsd|grep -e -r|head -1|sed 's/.*-r \(.*\)/\1/'`}
[ X"$spool_root" = X ] && ABORT specify spool root
cd $spool_root || ABORT

# file counts and total size
countsize=`find . -type f -printf '%s\n' | awk '{ s+=$1 } END { print NR, s }'`
count=`echo $countsize | awk '{ print $1 }'`
size=`echo $countsize | awk '{ print $2 }'`

echo "$PROG: start (spool_root: $spool_root)"
date

c=0
s=0
itime=`date +%s.%N`
find . -type f | while read f
do
	check_md5 $f
	etime=`date +%s.%N`

	c=`expr $c + 1`
	fs=`stat --printf='%s' $f`
	s=`expr $s + $fs`
	p=`expr $s \* 100 / $size`
	bw=`echo "$s / 1000 / ($etime - $itime)" | bc -l | sed 's/^\(.*\...\).*/\1/'`
	sec=`echo "($size - $s) / 1000 / $bw" | bc`
	hour=`expr $sec / 3600`
	min=`expr \( $sec - $hour \* 3600 \) / 60`
	min=`printf '%02d' $min`
	sec=`expr $sec - $hour \* 3600 - $min \* 60`
	sec=`printf '%02d' $sec`
	echo -ne "file: $c/$count size: $s/$size ($p%) ave: $bw KB/s Est: $hour:$min:$sec "'\r'
done
echo
