#!/bin/sh
#
# gfspoolmd5 - calculate and check md5 message digest of files in a spool
#
# Usage: gfspoolmd5 [spool_root]

PROG=`basename $0`

check_md5()
{
	file=$1
	inumgen=`echo $file | sed 's/.*data//' | sed 's|/||g'`
	[ $? -ne 0 ] && return
	inum_hex=`echo $inumgen | sed 's/.\{16\}$//'`
	[ $? -ne 0 ] && return
	inum=`printf "%d" 0x$inum_hex`
	[ $? -ne 0 ] && return
	gen_hex=`echo $inumgen | sed 's/^.\{16\}//'`
	[ $? -ne 0 ] && return
	gen=`printf "%d" 0x$gen_hex`
	[ $? -ne 0 ] && return

	md5_file=`md5sum $file | awk '{ print $1 }'`
	[ $? -ne 0 ] && return
	md5_mds=`gfxattr -Ig -G $gen $inum gfarm.md5 2>&1`
	if [ $? -ne 0 ]; then
		if [ "$md5_mds" = "no such object" ]; then
			echo -n $md5_file | gfxattr -Is -G $gen $inum gfarm.md5
		else
			echo >&2 $file: $md5_mds
		fi
	elif [ "$md5_file" != "$md5_mds" ]; then
		echo >&2 $file: md5 digest differs: file $md5_file mds $md5_mds
	fi
}

ABORT()
{
	[ $# -gt 0 ] && echo >&2 $PROG: $*
	echo >&2 Usage: $PROG [spool_root]
	exit 1
}

# gfarmroot?
if gfgroup -l gfarmroot | grep "\b`gfwhoami`\b" > /dev/null
then
	:
else
	ABORT You are not gfarmroot
fi

# spool_root
[ X"$1" != X ] && spool_root=$1
: ${spool_root=`ps -ef|grep gfsd|grep -e -r|head -1|sed 's/.*-r \(.*\)/\1/'`}
[ X"$spool_root" = X ] && ABORT specify spool root
cd $spool_root || ABORT

find . -type f | while read f
do
	check_md5 $f
done
