'\" t
.\"     Title: gfarmbb
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11 Jun 2019
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFARMBB" "1" "11 Jun 2019" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfarmbb \- Gfarm/BB（Gfarm burst buffer）を構築・撤去する
.SH "SYNOPSIS"
.HP \w'\fBgfarmbb\fR\ 'u
\fBgfarmbb\fR [\fIoptions\fR] \fImode\fR
.SH "DESCRIPTION"
.PP
Gfarm/BBは計算ノードのローカルストレージを用いる、一時的なオンデマンド ユーザレベルファイルシステムです。
\fBgfarmbb\fRはGfarm/BBの構築、撤去を行い ます。\fImode\fRには、startかstopを指定します。mode がstartのとき、環境変数 が表示されます。Gfarm/BBに対しGfarmコマンドを用いるためには、次のよう に環境変数を評価します。
.PP
% eval `gfarmbb start`
.SH "OPTIONS"
.PP
\fB\-e\fR
.RS 4
Gfmdを別ノードで実行します。Gfmdはgfarmbbを実行したホストで実行さ れますが、gfmdを起動したノードではgfsdを起動しません。本オプション は、N+1ホストが割り当てられ、ホストファイルの最後のノードでgfarmbb を起動することを想定しています。
.RE
.PP
\fB\-h\fR \fIhostfile\fR
.RS 4
計算ノードのホスト名のリストを含む
\fIhostfile\fRを指定します。startと stopで同じホストファイルを指定してください。
.RE
.PP
\fB\-scr\fR \fIscratch_dir\fR
.RS 4
Gfarm/BBを構成するための各計算ノードのスクラッチディレクトリを指定 します。指定されたディレクトリが存在しない場合は作成されます。また このディレクトリ以下のファイルはgfarmbb stopで削除されます。 startとstopで同じディレクトリを指定してください。デフォルトは /tmp/gfarmbb\-scratchです。
.RE
.PP
\fB\-l\fR
.RS 4
ログインノードからGfarm/BBのアクセスを可能とします。このオプション をつけるとホームディレクトリにGfarm/BBの設定ファイルを作成します。 設定ファイルのパス名は$HOME/\&.gfarm2rc\-$IDとなります。IDは計算ノー ドのホスト名とプロセスIDで構成されます。Gfarm/BBをアクセスする場合 は、この設定ファイルをGFARM_CONFIG_FILE環境変数で指定します。
.RE
.PP
\fB\-L\fR \fIlog_dir\fR
.RS 4
ログディレクトリを指定します。指定されたディレクトリが存在しない場 合は作成されます。gfmd, gfsdのログファイル名はそれぞれgfmd\-$ID\&.log, gfsd\-$ID\&.logです。デフォルトはスクラッチディレクトリ/logです。
.RE
.PP
\fB\-m\fR \fImount_point\fR
.RS 4
このオプションが指定されたとき、構築したGfarm/BBは指定されたマウン トポイントにマウントされます。mount\&.gfarm2fsが必要です。また、本 オプションはstartのときだけ有効です。
.RE
.PP
\fB\-p\fR \fIperiod\fR
.RS 4
Gfarm/BBの共有鍵の有効期間を秒単位で指定します。有効時間はジョブ実 行時間より長くする必要があります。デフォルトは86400秒（1日）です。
.RE
.PP
\fB\-c\fR
.RS 4
Cシェルのコマンドを出力します。本オプションはstartのときだけ有効で す。
.RE
.PP
\fB\-s\fR
.RS 4
Bourneシェルのコマンドを出力します。本オプションはstartのときだけ 有効です。デフォルト設定です。
.RE
