'\" t
.\"     Title: gfchmod
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 19 Apr 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFCHMOD" "1" "19 Apr 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfchmod \- Gfarm ファイルのアクセス権限を変更する
.SH "SYNOPSIS"
.HP \w'\fBgfchmod\fR\ 'u
\fBgfchmod\fR [\fIoptions\fR] mode [\fIpath\fR...]
.SH "DESCRIPTION"
.PP
Gfarm ファイルのアクセス権限を変更します．
.SH "OPTIONS"
.PP
\fB\-h\fR
.RS 4
シンボリックリンクの指すファイル／ディレクトリではなく， シンボリック自身のアクセス権限を変更します．
.RE
.PP
\fB\-R\fR
.RS 4
再帰的にアクセス権限を変更します．
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します．
.RE
