'\" t
.\"     Title: gfcksum
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 3 Mar 2014
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFCKSUM" "1" "3 Mar 2014" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfcksum \- Gfarm ファイルのチェックサムを表示する。
.SH "SYNOPSIS"
.HP \w'\fBgfcksum\fR\ 'u
\fBgfcksum\fR [\-rl] [\-T | \-t] \fIpath\fR...
.HP \w'\fBgfcksum\fR\ 'u
\fBgfcksum\fR \-c [\-rlv] [\-h\ \fIhost\fR] \fIpath\fR...
.SH "DESCRIPTION"
.PP
指定したファイルについてチェックサムを表示します。 \-r オプションを指定すると、指定されたディレクトリに含まれるファイルのチェックサムを再帰的に表示します。
.PP
\-t オプションを指定すると、現在設定されているチェックサムの種類のみを表示します。 \-T オプションを指定すると、ファイルを修正したとき、どの種類のチェックサムが計算されるかを表示します。
.PP
\-c オプションを指定すると、ファイルのチェックサムを計算し、 メタデータに格納されているチェックサムと比較します。 \-h オプションにより、ファイルが格納されているホストを指定することができます。 \-v オプションを指定すると、実際に格納されているファイルの修正時刻なども表示します。
.PP
\-l オプションを指定すると、それぞれのファイルのパスを表示します。 デフォルトでは、ベース名 (basename) しか表示しません。
.SH "OPTIONS"
.PP
\fB\-r\fR
.RS 4
ディレクトリに含まれるファイルのチェックサムを再帰的に表示します。
.RE
.PP
\fB\-c\fR
.RS 4
ファイルのチェックサムを計算し、メタデータに格納されているチェックサムと比較します。
.RE
.PP
\fB\-h\fR \fIhost\fR
.RS 4
\-c オプションとともに用いられ、ファイルが格納されているホストを指定します。
.RE
.PP
\fB\-v\fR
.RS 4
\-c オプションとともに用いられ、実際に格納されているファイルの修正日時など詳細な情報を表示します。
.RE
.PP
\fB\-l\fR
.RS 4
それぞれのファイルのパスを表示します。 デフォルトでは、gfcksum はベース名 (basename) しか表示しません。
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します。
.RE
