'\" t
.\"     Title: gfdf
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 14 Mar 2019
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFDF" "1" "14 Mar 2019" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfdf \- ディスク空き容量取得
.SH "SYNOPSIS"
.HP \w'\fBgfdf\fR\ 'u
\fBgfdf\fR [\fIオプション\fR]
.SH "DESCRIPTION"
.PP
\fBgfdf\fR
は、Gfarmファイルシステムの ディスク空き容量を表示します。
.SH "OPTIONS"
.PP
\fB\-a\fR
.RS 4
Gfarmファイルシステム全体のディスク空き容量を表示します。
.RE
.PP
\fB\-h\fR
.RS 4
数字を「M(メガ)」のような単位つきで読みやすく表示します。 単位には2の累乗を用いますので、「M」は 1,048,576 を意味します。
.RE
.PP
\fB\-H\fR
.RS 4
数字を「M(メガ)」のような単位つきで読みやすく表示します。 単位には10の累乗を用いますので、「M」は 1,000,000 を意味します。
.RE
.PP
\fB\-n\fR
.RS 4
利用可能なファイルシステムノードのホスト名を表示します。
.RE
.PP
\fB\-r\fR
.RS 4
逆順に整列して出力します。
.RE
.PP
\fB\-S\fR
.RS 4
空き容量の順に整列して出力します。
.RE
.PP
\fB\-P\fR \fIパス名\fR
.RS 4
指定したパス名により特定のメタデータサーバを指定します． このオプションは \-a オプションと同時に利用すると無視されます．
.RE
.PP
\fB\-D\fR \fIドメイン名\fR
.RS 4
指定したドメイン名に含まれるファイルシステムノードの状態を表示します。
.RE
.PP
\fB\-R\fR
.RS 4
読込専用のファイルシステムノードも実際の空き容量を表示します。 本書 NOTES も参照してください。
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します。
.RE
.SH "NOTES"
.PP
\fBgfhost\fR
により、 読込専用と指定されれると、 Gfarmファイルシステム内部ではそれらのノードはディスクフルと扱われ、 空き容量が 0 で表示されます。 \-R オプションを用いることにより、実際の空き容量を表示することができます。 また、\-a オプションによるファイルシステム全体の空き容量は、 \-R オプションをつけたときと同様に実際の空き容量が表示されます。
.SH "SEE ALSO"
.PP
\fBgfhost\fR(1),
\fBgfarm2.conf\fR(5)
