.TH gfexport 1 "1 May 2002"
.SH NAME

gfexport \- Gfarm ファイルを通常のファイルに変換する

.SH SYNOPSIS

.B gfexport
[
.B \-H
.I ホスト指定ファイル
]
[
.B -s
.I フラグメント番号
]
.in +.5i
.I gfarm-URL
.in

.SH DESCRIPTION

指定した Gfarm URL の表す Gfarm 並列ファイルを、通常のファイルに変換
して標準出力に出力します。

.SH OPTIONS

.TP
.B \-H
.I ホスト指定ファイル
.br
フラグメントを取り出すホスト名のリストを指定します。
ホスト名は、各行に一ホストずつ記述します。
省略した場合には、自動的に選ばれたホストからフラグメントを得ます。
.TP
.B \-H
.I フラグメント番号
.br
並列ファイル中の、指定したフラグメントのみを取り出します。
実行形式のファイルの場合には、このオプションで実行アーキテクチャ
(例 「sparc\-sun-solaris」) を指定することによって、指定したアーキ
テクチャの実行ファイルを取り出せます。
.TP
.B \-?
.br
引数オプションを表示します。
