'\" t
.\"     Title: gffindxmlattr
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 18 Aug 2008
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFFINDXMLATTR" "1" "18 Aug 2008" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gffindxmlattr \- ファイルのXML拡張属性をXPathにより検索する
.SH "SYNOPSIS"
.HP \w'\fBgffindxmlattr\fR\ 'u
\fBgffindxmlattr\fR [\-d\ \fIdepth\fR] [\-F\ \fIdelim\fR] [\fIXPath\fR | [\-f\ \fIXPath\-file\fR]] \fIpath\fR
.SH "DESCRIPTION"
.PP
指定されたXPath式に一致するXML拡張属性を検索し， 一致したパス名とXML拡張属性名を表示します． 指定されたpathがファイルの場合，そのファイルのXML拡張属性を検索します． 読み込み権限のないファイルは無視されます．
.PP
指定されたpathがディレクトリの場合，depthで指定された深さまで再帰的に検索します． 0の場合，指定されたディレクトリを検索します． depthが指定されない場合，無制限に検索します． 負の値が指定された場合はエラーとなります． また，実行権限のないディレクトリは検索されません．
.PP
出力結果は，一致したパス名とXML属性名が区切り文字delimで区切って表示されます．
.SH "OPTIONS"
.PP
\fB\-d\fR depth
.RS 4
depthで指定された深さまで再帰的に検索します．
.RE
.PP
\fB\-F\fR delim
.RS 4
一致したパス名とXML拡張属性名の区切り文字を指定します． \-Fオプションが指定されない場合はタブとなります．
.RE
.PP
\fB\-f\fR XPath\-file
.RS 4
検索するXPath式を読み込むファイルを指定します．
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します．
.RE
.SH "SEE ALSO"
.PP

\fBgfxattr\fR(1)
