'\" t
.\"     Title: gfgroup
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 20 Jan 2010
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFGROUP" "1" "20 Jan 2010" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfgroup \- Gfarm グループ管理コマンド
.SH "SYNOPSIS"
.HP \w'\fBgfgroup\fR\ 'u
\fBgfgroup\fR [\-P\ \fIpath\fR] [\-l] [\fIgroup\fR...]
.HP \w'\fBgfgroup\fR\ 'u
\fBgfgroup\fR [\-P\ \fIpath\fR] \-c groupname [\fIuser\fR...]
.HP \w'\fBgfgroup\fR\ 'u
\fBgfgroup\fR [\-P\ \fIpath\fR] \-m groupname [\fIuser\fR...]
.HP \w'\fBgfgroup\fR\ 'u
\fBgfgroup\fR [\-P\ \fIpath\fR] \-d groupname
.SH "DESCRIPTION"
.PP
Gfarm ファイルシステムにおけるグループ管理を行います． デフォルトでは全登録グループを表示します． グループ名が指定されたら，指定されたグループを表示します． Gfarmファイルシステムの管理者は，\-c，\-m，\-d オプションを指定することにより，それぞれグループ作成， グループメンバ変更，グループ削除を行うことができます．
.SH "OPTIONS"
.PP
\fB\-P\fR \fIパス名\fR
.RS 4
このコマンドがアクセスするメタデータサーバを特定するための パス名または Gfarm URL を指定します。 省略した場合は、「/」を指定したのと同じ意味になります。
.RE
.PP
\fB\-l\fR
.RS 4
グループ名とグループメンバの情報を表示します．
.RE
.PP
\fB\-c\fR
.RS 4
グループの作成を行います． 登録には初期グループメンバも指定することができます． Gfarmの管理者が実行可能です．
.RE
.PP
\fB\-m\fR
.RS 4
グループメンバの変更を行います． 変更したいグループ名とメンバのリスト指定します． Gfarmの管理者が実行可能です．
.RE
.PP
\fB\-d\fR
.RS 4
グループを消去します． Gfarmの管理者が実行可能です．
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します．
.RE
.SH "SEE ALSO"
.PP

\fBgfuser\fR(1)
