'\" t
.\"     Title: gfhost
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 20 Jan 2010
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFHOST" "1" "20 Jan 2010" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfhost \- gfarm ホスト管理コマンド
.SH "SYNOPSIS"
.HP \w'\fBgfhost\fR\ 'u
\fBgfhost\fR [\-H | \-l | \-M] [\-iLprUv] [\-P\ \fIpath\fR] [\-a\ \fIアーキテクチャ\fR] [\-D\ \fIドメイン名\fR] [\-j\ \fI並列度\fR] [\fIホスト名\fR...]
.HP \w'\fBgfhost\fR\ 'u
\fBgfhost\fR \-c [\-P\ \fIpath\fR] \-a\fIアーキテクチャ\fR \-p\fIポート番号\fR [\-n\fICPU数\fR] \fIホスト名\fR
.HP \w'\fBgfhost\fR\ 'u
\fBgfhost\fR \-m [\-P\ \fIpath\fR] [\-a\fIアーキテクチャ\fR] [\-p\fIポート番号\fR] [\-n\fICPU数\fR] [\-A] \fIホスト名\fR
.HP \w'\fBgfhost\fR\ 'u
\fBgfhost\fR \-d [\-P\ \fIpath\fR] \fIホスト名\fR...
.HP \w'\fBgfhost\fR\ 'u
\fBgfhost\fR \-R [\-P\ \fIpath\fR]
.SH "DESCRIPTION"
.PP
\fBgfhost\fR
は、gfarm のファイルシステムノードに 関する情報の表示や管理を行ないます。\fBgfhost\fR
が 実行する機能は、\-c, \-d, \-H, \-l, \-M, \-m, \-R のオプションで指定します。 これら機能の指定は排他的であり、どれか一つだけを指定することができます。 また、一つも指定しなかった場合には、デフォールトの機能であるホスト名 表示が行なわれます。
.SH "FUNCTIONS"
.PP
機能指定のうち、\-c, \-d, \-M, \-m, \-R はメタデータサーバーのみを アクセスし、登録されているホスト情報の追加、削除、表示、変更を行ないます。
.PP
機能指定のうち、\-H, \-l, \-M, および特に機能を指定しなかった場合は、 ファイルシステムノードに関する情報を表示します。 このうち \-M はメタデータサーバーのみをアクセスしますが、 それ以外の機能はファイルシステムノードで動作している
\fBgfsd\fR
にもアクセスします。
\fBgfsd\fR
にアクセスする機能に関しては、そのアクセスに 関するオプションを \-i, \-j, \-U, \-v で指定できます。
.PP
表示機能に関しては、ホスト名の指定を省略することができます。この場合、 メタデータに登録されている全てのホストに関する表示を試みます。 また、\-a および \-D オプションで表示するホストの種類を限定 することもできます。 表示の順序は、ホスト名のアルファベット順ですが、\-L, \-r, \-u オプションで 順序を変更することができます。ただし、\-M 機能
と、機能を指定しなかった場合
に関しては \-L オプションは無効です。
.PP
下記は、gfhost コマンドの機能一覧です。二つ以上の機能を同時に 指定することはできません。
.PP
無指定
.RS 4
機能を特に指定しなかった場合、\fBgfsd\fR
への 問い合わせを行ない、動作しているホストのホスト名のみを表示します。 デフォールトでは、ホスト名のアルファベット順で表示します。
.RE
.PP
\fB\-c\fR
.RS 4
引数で指定したホストをメタデータへ登録します。 オプション \-a で、そのホストのアーキテクチャを指定する必要があります。 同様にオプション \-p で、そのホストのポート番号を指定する必要があります。 オプション \-n で、そのホストの CPU 数を指定します。省略した場合には 1 CPU だとみなします。
.RE
.PP
\fB\-d\fR
.RS 4
引数に指定したホスト情報をメタデータから削除します。
現在のところ、複製情報として参照されているホストも 削除できてしまいますが、これを行なうと複製データベースが不整合 状態となってしまいますので注意が必要です。
.RE
.PP
\fB\-H\fR
.RS 4

\fBgfsd\fR
に問い合わせて得た情報、すなわち ロードアベレージと認証手段を表示します。 この機能に関しては、引数でホスト名を指定した場合、表示される のは、固有識別子として用いられているホスト名ではなく、引数 で指定した名前になります。 また、ホスト名の後に、アクセスに用いられた IP アドレスを括弧で 囲って表示します。
.sp
ホストが停止やネットワーク障害のためにアクセスできなかった場合、 ロードアベレージの部分に x\&.xx/x\&.xx/x\&.xx と表示します。 ホストが動作しているが、そのホストの
\fBgfsd\fR
へ アクセスできなかった場合には \-\&.\-\-/\-\&.\-\-/\-\&.\-\- と表示します。
.sp
その次の一桁の欄は認証手段で、「G」は GSI 認証および暗号化、 「g」は認証処理のみ GSI で認証後は保護のない生データ (gsi_auth)、 「s」は sharedsecret 認証、「x」は認証失敗、「\-」は認証を 試みなかったことを示します。また、「\-U」オプション指定時には、 この認証手段の表示欄はなくなります。
.sp
デフォールトでは、ホスト名のアルファベット順で表示します。
.RE
.PP
\fB\-l\fR
.RS 4

\fBgfsd\fR
に問い合わせて得た情報、 すなわちロードアベレージおよび認証手段と、 メタデータ・サーバーに問い合わせて得た情報、 すなわちアーキテクチャ名、CPU数を 全て表示します。またアクセスに用いられたホスト名の後に、 IP アドレスを括弧で囲って表示します。
.sp
ホストが停止やネットワーク障害のためにアクセスできなかった場合、 ロードアベレージの部分に x\&.xx/x\&.xx/x\&.xx と表示します。 ホストが動作しているが、そのホストの
\fBgfsd\fR
へ アクセスできなかった場合には \-\&.\-\-/\-\&.\-\-/\-\&.\-\- と表示します。
.sp
その次の一桁の欄は認証手段で、「G」は GSI 認証および暗号化、 「g」は認証処理のみ GSI で認証後は保護のない生データ (gsi_auth)、 「s」は sharedsecret 認証、「x」は認証失敗、「\-」は認証を 試みなかったことを示します。また、「\-U」オプション指定時には、 この認証手段の表示欄はなくなります。
.sp
デフォールトでは、ホスト名のアルファベット順で表示します。
.RE
.PP
\fB\-M\fR
.RS 4
メタデータに登録されているホスト情報を表示します。 デフォールトでは、ホスト名のアルファベット順で表示します。
.RE
.PP
\fB\-m\fR
.RS 4
固有識別子として用いられているホスト名を指定し、メタデータ に登録されているホスト情報を変更します。 \-a オプションおよび \-n オプションは、それぞれ既存の値を置き換えます。
.RE
.PP
\fB\-R\fR
.RS 4
標準入力からホストに関する情報を読み込み、メタデータに 追加します。与える情報の形式は、\-M 機能の表示形式と同じです。
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します。
.RE
.SH "OPTIONS"
.PP
\fB\-a\fR \fIアーキテクチャ\fR
.RS 4
CPUアーキテクチャを、sparc\-sun\-solaris8 や i386\-redhat8\&.0\-linux の ような形式で指定します。 \-c および \-m 機能の場合には、追加・変更するホストのアーキテクチャと して、このオプションを用います。 \-H, \-l, \-M および特に機能を指定しなかった場合で、かつ ホスト名を省略した場合には、指定したアーキテクチャのホストに 関してのみ表示を行ないます。
.RE
.PP
\fB\-D\fR \fIドメイン名\fR
.RS 4
\-H, \-l, \-M および特に機能を指定しなかった場合で、かつ ホスト名を省略した場合に、このオプションで、表示するドメイン名を 限定できます。
.RE
.PP
\fB\-i\fR
.RS 4
%%SYSCONFDIR%%/gfarm2\&.conf ないし $HOME/\&.gfarm2rc 中で「address_use」を指定すると、 アクセスに用いるネットワークアドレスに優先順位をつけることができます。 gfhost コマンドに対しても、この優先順位は影響しますが、\-i オプションを つけると、この指定を無視して
\fBgfsd\fR
にアクセス するようになります。
.RE
.PP
\fB\-j\fR \fI並列度\fR
.RS 4

\fBgfsd\fR
にアクセスする際の並列度を指定します。 デフォールトは 10 です。
.RE
.PP
\fB\-L\fR
.RS 4
\-H、\-l 機能の場合
、このオプションで、 表示順序を、ロードアベレージ順に変更します。
.RE
.PP
\fB\-n\fR \fICPU数\fR
.RS 4
\-c および \-m 機能で、ホスト情報を追加・変更する際に、 そのホストが持つ CPU の数を指定します。
.RE
.PP
\fB\-p\fR \fIポート番号\fR
.RS 4
\-c および \-m 機能で、ホスト情報を追加・変更する際に、 そのホストの
\fBgfsd\fR
が用いるポート番号を指定します。
.RE
.PP
\fB\-P\fR \fIパス名\fR
.RS 4
このコマンドがアクセスするメタデータサーバを特定するための パス名または Gfarm URL を指定します。 省略した場合は、「/」を指定したのと同じ意味になります。
.RE
.PP
\fB\-r\fR
.RS 4
表示を整列している場合、表示の順序を逆にします。
.RE
.PP
\fB\-u\fR
.RS 4
\-H, \-l, \-M および特に機能を指定しなかった場合に、表示する順序を アルファベット順に整列するのを止めます。 \-M 機能の場合、引数でホスト名を指定した場合には その順序、さもなくばメタデータから取得した順序で表示します。 \-H, \-l 機能の場合および特に機能を指定しなかった場合、 ホストに順に問い合わせを行い、返事の返ってきた順序で表示します。
.RE
.PP
\fB\-U\fR
.RS 4
TCP による認証をやめ、 UDP によるロードアベレージの問い合わせのみを行うようにします。 このオプションは、\-H ないし \-l 機能を指定した場合および 特に機能を指定しなかった場合に意味のあるオプションで、 実行速度が速くなる効果があります。 \-H ないし \-l を指定している場合、このオプションを指定すると、 認証方式の表示欄がなくなります。
.RE
.PP
\fB\-v\fR
.RS 4
\-H ないし \-l 機能を指定した場合および特に機能を指定しなかった場合、 デフォールトでは、gfsd に対する問い合わせに関するエラーメッセージ を表示しません。\-v オプションを指定すると、このエラーメッセージを 表示するようになります。
.RE
.SH "SEE ALSO"
.PP

\fBgfarm2.conf\fR(5),
\fBgfsd\fR(8)
