.TH gfimport_text 1 "1 May 2002"
.SH NAME

gfimport_text \- テキスト・ファイルをフラグメントに分けて取り込む

.SH SYNOPSIS

.B gfimport_text
[
.I オプション
]
.I 入力ファイル

.SH DESCRIPTION

引数に指定したテキスト・ファイルを、一行を複数のフラグメントに分割す
ることのないように分割して Gfarm 並列ファイルシステムに取り込む
サンプル・プログラムです。

.SH OPTIONS

.TP
.B \-H
.I ホスト指定ファイル
.br
フラグメントを配置するホスト名のリストを記載したファイル名を指定します。
ホスト名は、各行に一ホストずつ記述します。
\-l オプションを省略した場合は、入力ファイルは、このオプションで
指定したホストに、等分割したフラグメントとして配置されます。
.TP
.B \-f
.I フラグメント構成ファイル
.br
各フラグメントのおおよそのサイズと、配置するホストを記載したファイ
ル名を指定します。
.br
構成ファイルは、各行が、空白で区切られたサイズとホスト名からなる形式です。
.TP
.B \-o
.I gfarm-URL
.br
出力 Gfarm ファイルの URL を指定します。
.TP
.B \-?
.br
引数オプションを表示します。
