'\" t
.\"     Title: gfkey
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 25 Feb 2010
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFKEY" "1" "25 Feb 2010" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfkey \- Gfarm セッション・キー管理コマンド
.SH "SYNOPSIS"
.HP \w'\fBgfkey\fR\ 'u
\fBgfkey\fR [\fIオプション\fR]
.SH "DESCRIPTION"
.PP
信頼された環境で gfsd、gfmd を共有秘密鍵認証でアクセスするのに 必要なセッション・キー・ファイル
\fB$HOME/\&.gfarm_shared_key\fR
を扱うコマンドです。
.PP
ホーム・ディレクトリを共有している環境では、このコマンドを使う必要性 はあまりありませんが、そうでない環境では、このコマンドでキーを生成し た後、全ファイルシステムノードにキーを配付する必要があります。
.SH "OPTIONS"
.PP
\fB\-c\fR
.RS 4
このオプションを指定すると、有効なセッション・キーがない場合に、セッ ション・キー・ファイルを作成します。既に有効なセッション・キーが存 在する場合には何もしません。
.RE
.PP
\fB\-f\fR
.RS 4
強制的にセッション・キーを作成します。 既に有効なセッション・キーが存在する場合でも、そのキーを捨てて新た にキーを作成します。
.RE
.PP
\fB\-p\fR \fIperiod\fR
.RS 4
セッション・キーの有効期限を指定します。単位は秒です。 このオプションは \-c オプションあるいは \-f オプションと同時に指定する必要があります。
.RE
.PP
\fB\-l\fR
.RS 4
現在のキーを表示します。
.RE
.PP
\fB\-e\fR
.RS 4
現在のキーの期限が切れる時刻を表示します。
.RE
.PP
\fB\-L\fR \fImessage\-priority\-level\fR
.RS 4
このオプションで指定したレベル以上の優先度のメッセージを出力します。 デフォルトはinfoです。 指定できる値はgfarm2\&.conf(5)のlog_levelの項を参照してください。
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します。
.RE
.SH "FILES"
.PP
$HOME/\&.gfarm_shared_key
.RS 4
セッション・キー・ファイルです。
.RE
