.TH gfkey 1 "1 May 2002"
.SH NAME

gfkey \- gfsd のセッション・キー管理コマンド

.SH SYNOPSIS

.B gfkey
[
.I オプション
]

.SH DESCRIPTION

gfsd をアクセスするのに必要なセッション・キー・ファイル 
.B $HOME/.gfarm_shared_key
を扱うコマンドです。

ホーム・ディレクトリを共有している環境では、このコマンドを使う必要性
はあまりありませんが、そうでない環境では、このコマンドでキーを生成し
た後、計算プールの全ホストにキーを配付する必要があります。

.SH OPTIONS

.TP
.B \-c
.br
このオプションを指定すると、有効なセッション・キーがない場合に、セッ
ション・キー・ファイルを作成します。既に有効なセッション・キーが存
在する場合には何もしません。
.TP
.B \-f
.br
強制的にセッション・キーを作成します。
既に有効なセッション・キーが存在する場合でも、そのキーを捨てて新た
にキーを作成します。
.TP
.B \-l
.br
現在のキーを表示します。
.TP
.B \-e
.br
現在のキーの期限が切れる時刻を表示します。
.TP
.B \-?
.br
引数オプションを表示します。

.SH FILES

.TP
.SB "$HOME/.gfarm_shared_key"

セッション・キー・ファイルです。


