'\" t
.\"     Title: gfls
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 27 Apr 2007
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFLS" "1" "27 Apr 2007" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfls \- Gfarm ディレクトリの内容を表示する。
.SH "SYNOPSIS"
.HP \w'\fBgfls\fR\ 'u
\fBgfls\fR [\fIオプション\fR] [\fIpath\fR...]
.SH "DESCRIPTION"
.PP
path に指定したファイルないしディレクトリの名前と 関連する情報を表示します。
.SH "OPTIONS"
.PP
\fB\-a\fR
.RS 4
``\&.\*(Aq\*(Aqで始まるパス名も表示します。
.RE
.PP
\fB\-A\fR
.RS 4
``\&.\*(Aq\*(Aqと``\&.\&.\*(Aq\*(Aqは表示しません。
.RE
.PP
\fB\-C\fR
.RS 4
マルチカラム出力を行ないます。これはデフォルトの出力形式です。
.RE
.PP
\fB\-d\fR
.RS 4
そのディレクトリに属する内容ではなく、ディレクトリ自身を表示します。
.RE
.PP
\fB\-E\fR \fI秒数\fR
.RS 4
属性キャッシュを保持する秒数を指定します。 0 を指定した場合、属性をキャッシュしません。
.RE
.PP
\fB\-F\fR
.RS 4
名称の直後に、その種類を表す文字 (*/=@| のいずれか) を表示します。
.RE
.PP
\fB\-i\fR
.RS 4
inode 番号も表示します。
.RE
.PP
\fB\-l\fR
.RS 4
ファイルのサイズ、所有者、グループ、更新時刻などの属性情報も 表示します。
.RE
.PP
\fB\-r\fR
.RS 4
逆順に整列して表示します。
.RE
.PP
\fB\-R\fR
.RS 4
ディレクトリの内容を再帰的に表示します。
.RE
.PP
\fB\-S\fR
.RS 4
ファイルサイズで整列します。
.RE
.PP
\fB\-t\fR
.RS 4
ファイル名ではなく、ファイルの時刻を基準に整列します。
.RE
.PP
\fB\-T\fR
.RS 4
\fB\-l\fR
オプションと同時に指定すると、時刻を完全な形式で表示します。
.RE
.PP
\fB\-1\fR
.RS 4
1行に1エントリずつ表示します。
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します。
.RE
