'\" t
.\"     Title: gfmdhost
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 30 June 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFMDHOST" "1" "30 June 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfmdhost \- gfarm メタデータサーバ管理コマンド
.SH "SYNOPSIS"
.HP \w'\fBgfmdhost\fR\ 'u
\fBgfmdhost\fR [\-l] [\-P\ \fIpath\fR]
.HP \w'\fBgfmdhost\fR\ 'u
\fBgfmdhost\fR {\-c | \-m} [\-P\ \fIpath\fR] [\-p\ \fIポート番号\fR] [\-C\ \fIクラスタ名\fR] [\-t\ {m\ |\ c\ |\ s}] {\fIメタデータサーバ名\fR}
.HP \w'\fBgfmdhost\fR\ 'u
\fBgfmdhost\fR {\-d} [\-P\ \fIpath\fR] {\fIメタデータサーバ名\fR}
.SH "DESCRIPTION"
.PP
\fBgfmdhost\fR
は gfarm のメタデータサーバの冗長化機能に関連する情報の表示や管理を行います。
\fBgfmdhost\fR
が実行する機能は \-l, \-c, \-m, \-d のオプションで選択します。 これら機能の指定は排他的であり、どれか一つだけを指定することができます。 また、一つも指定しなかった場合には、 デフォルトの機能である gfmd ホスト名の一覧表示が行われます。
.SH "FUNCTIONS"
.PP
下記は、\fBgfmdhost\fRコマンドの機能一覧です。二つ以上の機能を同時に 指定することはできません。
.PP
無指定
.RS 4
登録されているgfmdホストのホスト名一覧を、 アルファベット順で表示します。
.RE
.PP
\fB\-l\fR
.RS 4
登録されている gfmd ホストのホスト名一覧を、 詳細情報と共に表示します。クラスタ名ごとにホスト名を アルファベット順で表示します。
.sp
詳細情報は次の順に表示されます。
.sp
\fB接続状態 (+|\-|?|x|e)\fR
.sp
"+" はマスター gfmd と正常に接続していることを表します。 "\-" は接続していないことを表します。 "?" は、マスター gfmd と接続直後でまだ状態が判明してないか、あるいは Gfarm\-2\&.5\&.0 の gfmd に対して、Gfarm\-2\&.5\&.1 以降の gfmdhost コマンド から接続した場合に表示されます。 "x" はマスター gfmd と接続できたものの、切断している間の更新量が 多く自動同期が不可能となり、バックエンド・データベースのダンプ・ リストアを用いて同期をとる必要が生じていることを表します。 "e" は何らかのエラーが生じ、ログの調査が必要なことを表します。 "x" および "e" については、そのスレーブgfmdが停止した後でも、 表示が続きます。 マスター gfmd は常に "+" です。
.sp
\fBサーバ種別 (master|slave)\fR
.sp
マスターであるか、スレーブであるかを表します。
.sp
\fBレプリケーション種別 (sync|async|\-)\fR
.sp
sync は同期レプリケーション、 async は非同期レプリケーションを表します。 マスター gfmd には "\-" が表示されます。
.sp
\fBマスター候補の設定 (c|m|s)\fR
.sp
m はデフォルトのマスター、c はマスター候補、 s はスレーブ専用の gfmd を表します。
.sp
\fBクラスタ名\fR
.sp
gfmd が属するクラスタ名です。 デフォルトのクラスタは "(default)" と表示されます。
.RE
.PP
\fB\-c\fR
.RS 4
引数で指定した gfmd ホストを登録します。 任意でオプション \-C、\-p、\-t を指定します。
.RE
.PP
\fB\-m\fR
.RS 4
引数で指定した gfmd ホストを変更します。 任意でオプション \-C、\-p、\-t を指定します。
.RE
.PP
\fB\-d\fR
.RS 4
引数で指定した gfmd ホストを削除します。 マスター gfmd を削除することはできません。
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します。
.RE
.SH "OPTIONS"
.PP
\fB\-C\fR \fIクラスタ名\fR
.RS 4
\-c, \-m 機能で gfmd ホストが属するクラスタ名を指定します。 省略した場合、デフォルトのクラスタに属します。
.sp
クラスタ名は同期レプリケーションのグループを表します。 マスター gfmd と同一のクラスタに所属する gfmd 間は同期レプリケー ションとなり、それ以外の gfmd は非同期レプリケーションとなります。 同期レプリケーションが行われているスレーブ gfmd は、 メタデータ操作を失うことなくマスター gfmd に昇格することが可能です。
.RE
.PP
\fB\-p\fR \fIポート番号\fR
.RS 4
\-c, \-m 機能で gfmd のポート番号を指定します。 省略した場合、デフォルトのポート番号 601 を指定したことになります。
.RE
.PP
\-t {m|c|s}
.RS 4
\-c, \-m 機能でマスター候補の設定を指定します。 m はデフォルトのマスター、c はマスター候補、 s はスレーブ専用を表します。 省略した場合、c を指定したことになります。 デフォルトのマスターをマスター候補およびスレーブ専用へ、 直接変更することはできません。 デフォルトのマスター以外の gfmd を \-t m によりデフォルトのマスターに変更すると、 以前のデフォルトのマスターがマスター候補に変更されます。
.RE
.PP
\fB\-P\fR \fIpath\fR
.RS 4
このコマンドがアクセスするメタデータサーバを特定するための パス名または Gfarm URL を指定します。 省略した場合は、"/" を指定したのと同じ意味になります。
.RE
.SH "SEE ALSO"
.PP

\fBgfarm2.conf\fR(5)
