'\" t
.\"     Title: gfncopy
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 23 Oct 2012
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFNCOPY" "1" "23 Oct 2012" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfncopy \- 自動ファイル複製作成数を操作する。
.SH "SYNOPSIS"
.HP \w'\fBgfncopy\fR\ 'u
\fBgfncopy\fR [\fIオプション\fR] \fIpath\fR
.SH "DESCRIPTION"
.PP
path に指定したファイルないしディレクトリに関する自動ファイル複製作成数を操作します。 オプションを指定しない場合は、 設定された自動複製作成数を表示します。 \-vオプションを指定すると、自動複製作成数を設定している 先祖のディレクトリまでのパス名も含めて表示します。
.SH "OPTIONS"
.PP
\fB\-s\fR \fINCOPY\fR
.RS 4
自動複製作成数を設定します。
.RE
.PP
\fB\-r\fR
.RS 4
自動複製作成数の設定を消去します。
.RE
.PP
\fB\-c\fR
.RS 4
実際のファイル複製数を表示します。
.RE
.PP
\fB\-w\fR
.RS 4
ファイル複製が作成されるのを待ちます。
.RE
.PP
\fB\-v\fR
.RS 4
自動複製作成数を設定している先祖のディレクトリまでのパス名も含めて表示します。
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します。
.RE
