'\" t
.\"     Title: gfpconcat
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 7 Feb 2022
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFPCONCAT" "1" "7 Feb 2022" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfpconcat \- 複数ファイルを結合しながら並列にコピーする
.SH "SYNOPSIS"
.HP \w'\fBgfpconcat\fR\ 'u
\fBgfpconcat\fR [\-fpqvd] [\-h\ \fIfilesystem\-node\fR] [\-j\ \fInum\-of\-processes\fR] [\-m\ \fIminimum\-bytes\fR] [\-i\ \fIinput\-listfile\fR] \-o\ \fIdestination\-file\fR \fIsource\-file\fR...
.SH "DESCRIPTION"
.PP
\fBgfpconcat\fR
は、単一ファイルまたは複数ファイルを単一のファイルに対して 並列にコピーします。
.PP
\fIsource\-file\fR
には、コピー元のファイル名を指定します。 ファイル名を複数指定した場合は、指定した順序で結合します。
.PP
\fIdestination\-file\fR
には、コピー先のファイル名を指定します。 ファイルが存在する場合は、上書きしません。
.SH "SOURCE FILE"
.PP
\fIsource\-file\fR
には以下を指定できます。
.PP
\fIパス名\fR
.RS 4
ローカルファイルシステム上のパスを絶対パスまたは相対パスで指定しま す。そのパスが gfarm2fs のマウントポイントの場合は、gfarm2fsを経由 せずにGfarm からコピーします。
.RE
.PP
\fIgfarm:\&.\&.\&.\fR
.RS 4
Gfarm URL で指定します。
.RE
.PP
\fIfile:\&.\&.\&.\fR
.RS 4
ローカルファイルシステム上のパスを URL で指定します。
.RE
.SH "DESTINATION FILE"
.PP
\fIdestination\-file\fR
には以下を指定できます。
.PP
\fIパス名\fR
.RS 4
ローカルファイルシステム上のディレクトリを絶対パスまたは相対パスで 指定します。そのパスが gfarm2fs のマウントポイントの場合は、 gfarm2fs を経由せずに Gfarm へコピーします。
.RE
.PP
\fIgfarm:\&.\&.\&.\fR
.RS 4
ディレクトリを Gfarm URL で指定します。
.RE
.PP
\fIfile:\&.\&.\&.\fR
.RS 4
ローカルファイルシステム上のディレクトリを URL で指定します。
.RE
.SH "OPTIONS"
.PP
\fB\-f\fR
.RS 4
既存ファイルを上書きします。
.RE
.PP
\fB\-h\fR \fIfilesystem\-node\fR
.RS 4
指定したファイルシステムノードにファイルを作成します。
.RE
.PP
\fB\-i\fR \fIinput\-listfile\fR
.RS 4
入力ファイルを列挙したファイルをコマンドライン引数
\fIsource\-file\fR
の代わりに指定します。 そのファイル中の各行に入力 URL を一つずつ記述します。
.RE
.PP
\fB\-j\fR \fInum\-of\-processes\fR
.RS 4
並列プロセス数を指定します。 入力ファイルを均等なサイズに分割し、各プロセスに割り当てます。
.sp
デフォルト値は gfarm2\&.conf の client_parallel_copy パラメータです。 最大値は gfarm2\&.conf の client_parallel_max パラメータです。 詳細は gfarm2\&.conf のマニュアルを参照してください。
.RE
.PP
\fB\-m\fR \fIminimum\-bytes\fR
.RS 4
並列コピーする場合に、1 プロセスに割り当てる最小データサイズを バイト数で指定します。 デフォルトは 1048576 バイトです。
.RE
.PP
\fB\-p\fR
.RS 4
コピー性能を報告します。
.RE
.PP
\fB\-q\fR
.RS 4
警告を表示しません。
.RE
.PP
\fB\-v\fR
.RS 4
冗長な情報を出力します。
.RE
.PP
\fB\-d\fR
.RS 4
デバッグ情報を出力します。
.RE
.PP
\fB\-?\fR
.RS 4
コマンドオプションを出力します。
.RE
.SH "NOTES"
.PP
Gfarm 上にファイルを 1つ作成する際に、並列に書き込んだり、 ランダムアクセスで書き込んだりすると、チェックサムがファイルに付加されません。 そのため、\fBgfpconcat\fR
を使用すると、 チェックサムが付加されません。 一度ファイルをシーケンシャルに読むと、または複製を作成すると チェックサムが付加されます。 または gfmd\&.conf の
\fIwrite_verify\fR
が enable となっていれば、
\fBgfpconcat\fR
でファイル作成後にしばらく経つと チェックサムが付加されます。 詳細は gfarm2\&.conf のマニュアルを参照してください。
.SH "SEE ALSO"
.PP
\fBgfcksum\fR(1),
\fBgfarm2.conf\fR(5)
