'\" t
.\"     Title: gfpcopy
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 27 Aug 2015
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFPCOPY" "1" "27 Aug 2015" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfpcopy \- copy Gfarm files in parallel
.SH "SYNOPSIS"
.HP \w'\fBgfpcopy\fR\ 'u
\fBgfpcopy\fR [\-nqvdpPU] [\-X\ \fIregexp\fR] [\-S\ \fIsource\-domainname\fR] [\-h\ \fIsource\-hostfile\fR] [\-D\ \fIdestination\-domainname\fR] [\-H\ \fIdestination\-hostfile\fR] [\-j\ \fInum\-of\-processes\fR] [\-J\ \fInum\-of\-processes\fR] [\-M\ \fItotal\-byte\fR] [\-z\ \fIminimum\-byte\fR] [\-Z\ \fImaximum\-byte\fR] [\-w\ \fIway\-of\-scheduling\fR] [\-W\ \fIkilobytes\-for\-threshold\fR] [\-s\ \fIKB/s\-to\-simulate\fR] [\-F\ \fInum\-for\-readahead\fR] [\-f] [\-b\ \fIbufsize\fR] [\-e] [\-k] \fIsource\-path\fR \fIdestination\-path\fR
.SH "DESCRIPTION"
.PP
\fBgfpcopy\fR
は、 複数のファイルを並列にコピーします。
.PP
\fIsource\-path\fR
がディレクトリの場合は、 その下にあるすべてのファイルとディレクトリをコピーします。
.PP
\fIdestination\-path\fR
が存在しない場合は、 ディレクトリを作成します。
\fIdestination\-path\fR
が存在する場合は、 そのディレクトリの下に
\fIsource\-path\fR
のディレクトリと同名のディレクトリを作成します。
.PP
転送先や転送元のホスト群を指定するには、ドメイン名で指定するか、 ホスト名を行ごとに記述したホストリストファイルを指定します。 ドメイン名とホストリストファイルを両方指定した場合は、 両方の条件に合うホスト群を決定します。 転送元ホスト群を指定した場合、 そのホストに存在するファイルのみコピーされます。
.PP
\fBgfpcopy\fR
は、ディレクトリを辿る際に、 ディレクトリエントリ情報も並列に取得します。
.SH "SOURCE PATH"
.PP
\fIsource\-path\fR
には以下を指定できます。 HPSS 上のファイルをコピーできません。
.PP
\fIgfarm:\&.\&.\&.\fR
.RS 4
Gfarm URL で指定します。
.RE
.PP
\fIfile:\&.\&.\&.\fR
.RS 4
ローカルファイルシステム上のパスを URL で指定します。
.RE
.PP
\fI任意\fR
.RS 4
ローカルファイルシステム上のパスを絶対パスまたは相対パスで指定します。 そのパスが gfarm2fs のマウントポイントの場合は、 gfarm2fs を経由せずに Gfarm からコピーします。
.RE
.SH "DESTINATION PATH"
.PP
\fIdestination\-path\fR
には以下を指定できます。
.PP
\fIgfarm:\&.\&.\&.\fR
.RS 4
ディレクトリを Gfarm URL で指定します。
.RE
.PP
\fIfile:\&.\&.\&.\fR
.RS 4
ローカルファイルシステム上のディレクトリを URL で指定します。
.RE
.PP
\fIhpss:\&.\&.\&.\fR
.RS 4
HPSS 上に存在するディレクトリを URL で指定します。 その下に
\fIsource\-path\fR
と同名のディレクトリが存在する場合はエラーになります。 HPSS に対して差分コピーはできません。 hpss:\&. や hpss:dir のように相対パスで指定することもできます。
.RE
.PP
\fI任意\fR
.RS 4
ローカルファイルシステム上のディレクトリを絶対パスまたは相対パスで指定します。 そのパスが gfarm2fs のマウントポイントの場合は、 gfarm2fs を経由せずに Gfarm へコピーします。
.RE
.SH "GFPCOPY OPTIONS"
.PP
以下は
\fBgfpcopy\fR
専用のオプションです。
.PP
\fB\-b\fR \fIbufsize\fR
.RS 4
コピー時に使用するバッファサイズを指定します。
.sp
標準は 64 キビバイト (64 * 1024) です。
.RE
.PP
\fB\-f\fR
.RS 4
\-f オプションを指定する場合、コピー先のファイルとコピー元のファイルが、 サイズまたは mtime が異なる場合に上書きします。
.sp
\-f オプションを指定しない場合、 コピー先のほうが mtime が古い場合に、上書きします。
.RE
.PP
\fB\-e\fR
.RS 4
gfpcopy を複数同時に実行するために、コピー先にファイルが存在すれば無視 します。
.RE
.PP
\fB\-k\fR
.RS 4
シンボリックリンクをコピーしません。
.RE
.SH "COMMON OPTIONS"
.PP
\fBgfpcopy\fR
には
\fBgfprep\fR
と共通のオプションがあります。
\fBgfprep\fR
のマニュアルを参照してください。
.SH "EXAMPLES"
.PP
ディレクトリ以下すべてをコピーします。
.sp
.if n \{\
.RS 4
.\}
.nf
$ gfpcopy gfarm:///dir file:///tmp/dir
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
$ gfpcopy file:///tmp/dir gfarm:///dir
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
$ gfpcopy gfarm:///dir1 gfarm:///dir2
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
$ gfpcopy gfarm:///dir hpss:///tmp/dir
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
$ cd /mnt/gfarm2fs
$ gfpcopy dir /tmp/dir
.fi
.if n \{\
.RE
.\}
.PP
一つのファイルをコピーします。
.sp
.if n \{\
.RS 4
.\}
.nf
$ gfpcopy gfarm:///dir/file file:///dir
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
$ cd /mnt/gfarm2fs
$ gfpcopy file /tmp/dir
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.PP
\fBgfmd\fR
と
\fBgfpcopy\fR
が距離的に離れている場合には、
\fBgfpcopy\fR
の動作が遅くなります。 そのような場合には、\-j または \-J オプションに大きな値を指定すると、 性能が改善するかもしれません。
.SH "SEE ALSO"
.PP
\fBgfprep\fR(1),
\fBgfreg\fR(1),
\fBgfexport\fR(1),
\fBgfarm2.conf\fR(5)
