'\" t
.\"     Title: gfperf-parallel-replica
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 19 May 2012
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFPERF\-PARALLEL\-RE" "1" "19 May 2012" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfperf-parallel-replica \- Gfarm ファイル複製の性能測定を行う。
.SH "SYNOPSIS"
.HP \w'\fBgfperf\-parallel\-replica\fR\ 'u
\fBgfperf\-parallel\-replica\fR \-s,\ \-\-src\ \fI複製元gfsd名\fR \-s,\ \-\-dst\ \fI複製先gfsd名\fR [\-l,\ \-\-filesize\ \fIファイルサイズ\fR] [\-t,\ \-\-testdir\ \fIテストディレクトリ\fR] [\-n,\ \-\-name\ \fIグループ名\fR] [\-w,\ \-\-wait\ \fI開始時刻\fR]
.SH "DESCRIPTION"
.PP
引数
\fIテストディレクトリ\fR
にテスト用のファイルを作成し、その複製性能を測定します。
.PP
本コマンドはgfperf\&.rbから並列に呼出されることを期待しています。
.SH "OPTIONS"
.PP
\fB\-s, \-\-src\fR \fI複製元gfsd名\fR
.RS 4
複製元gfsd名を指定します。
.RE
.PP
\fB\-d, \-\-dst\fR \fI複製先gfsd名\fR
.RS 4
複製先gfsd名を指定します。
.RE
.PP
\fB\-l, \-\-filesize\fR \fIファイルサイズ\fR
.RS 4
テストで使用するファイルサイズを指定します。 デフォルトは1Mです。
.RE
.PP
\fB\-t, \-\-testdir\fR \fIテストディレクトリ\fR
.RS 4
テストを実施するディレクトリを指定します。 gfarm url (gfarm:///で始まるもの) を指定します。 デフォルトはgfarm:///tmpです。
.RE
.PP
\fB\-n, \-\-name\fR \fIグループ名\fR
.RS 4
複数起動された場合に目印となるグループ名を指定します。
.RE
.PP
\fB\-w, \-\-wait\fR \fI開始時刻\fR
.RS 4
指定された時刻になるまでテストを開始しません。 通常、gfperf\&.rbにより指定されます。 時刻はUTCで指定され、現在時刻よりも10秒以上先の時刻は指定できません。
.RE
