'\" t
.\"     Title: gfperf-autoreplica
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 19 May 2012
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFPERF\-AUTOREPLICA" "1" "19 May 2012" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfperf-autoreplica \- Gfarm 自動複製機能の性能測定を行う。
.SH "SYNOPSIS"
.HP \w'\fBgfperf\-autoreplica\fR\ 'u
\fBgfperf\-autoreplica\fR [\-t,\ \-\-testdir\ \fIテストディレクトリ\fR] [\-m,\ \-\-gfarm2fs\ \fIgfarm2fsマウントポイント\fR] [\-l,\ \-\-filesize\ \fIファイルサイズ\fR] [\-f,\ \-\-number\ \fIファイル数\fR] [\-r,\ \-\-replica\ \fI複製数\fR] [\-s,\ \-\-stop\ \fI待ち時間\fR]
.SH "DESCRIPTION"
.PP
引数
\fIテストディレクトリ\fR
に指定されたサイズのファイルを指定された数作成し、その作成性能を測定します。それぞれのファイルは指定された複製数で自動複製が行われます。
.SH "OPTIONS"
.PP
\fB\-t, \-\-testdir\fR \fIテストディレクトリ\fR
.RS 4
テストを実施するディレクトリを指定します。 gfarm url (gfarm:///で始まるもの) を指定します。 デフォルトはgfarm:///tmpです。
.RE
.PP
\fB\-m, \-\-gfarm2fs\fR \fIgfarm2fsマウントポイント\fR
.RS 4
gfarm2fsのマウントポイントを指定します。
.RE
.PP
\fB\-l, \-\-filesize\fR \fIファイルサイズ\fR
.RS 4
使用するファイルサイズを指定します。 デフォルトは1Gです。
.RE
.PP
\fB\-f, \-\-number\fR \fIファイル数\fR
.RS 4
生成するファイル数を指定します。 デフォルトは10です。
.RE
.PP
\fB\-r, \-\-replica\fR \fI複製数\fR
.RS 4
自動複製機能で複製する数を指定します。 デフォルトは1です。
.RE
.PP
\fB\-s, \-\-stop\fR \fI待ち時間\fR
.RS 4
複製が作成されるのを最大何秒待つのかを指定します。 デフォルトは60です。
.RE
