'\" t
.\"     Title: gfperf-tree
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 19 May 2012
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFPERF\-TREE" "1" "19 May 2012" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfperf-tree \- Gfarm ディレクトリツリーの性能測定を行う。
.SH "SYNOPSIS"
.HP \w'\fBgfperf\-tree\fR\ 'u
\fBgfperf\-tree\fR [\-t,\ \-\-testdir\ \fIテストディレクトリ\fR] [\-w,\ \-\-width\ \fIディレクトリ数\fR] [\-d,\ \-\-depth\ \fIディレクトリ階層\fR] [\-u,\ \-\-unit\ \fI出力の単位\fR]
.SH "DESCRIPTION"
.PP
引数
\fIテストディレクトリ\fR
にテスト用のディレクトリツリーを作成、削除し、その実行性能を測定します。生成されるディクトリの数はwidthのdepth乗です。
.PP
測定する内容は指定されたディレクトリツリーの生成、及び削除にかかった時間を測定し、指定された単位で表示します。
.SH "OPTIONS"
.PP
\fB\-t, \-\-testdir\fR \fIテストディレクトリ\fR
.RS 4
テストを実施するディレクトリを指定します。 gfarm url(gfarm:///で始まるもの)を指定した場合、該当のgfarm上のディレクトリに対してlibgfarmの関数を使用した場合の性能を測定します。 file url(file:///で始まるもの)を指定した場合、該当のunixファイルシステム上にposixの関数を使用した場合の性能を測定します。 デフォルトはgfarm:///tmpです。
.RE
.PP
\fB\-w, \-\-width\fR \fIディレクトリ数\fR
.RS 4
サブディレクトリを作成する数を指定します。
.RE
.PP
\fB\-d, \-\-depth\fR \fIディレクトリ階層\fR
.RS 4
サブディレクトリを何階層作成するか指定します。
.RE
.PP
\fB\-u, \-\-uinit\fR \fI出力の単位\fR
.RS 4
ops(operations per second)またはusecを指定します。指定した単位で出力を返します。デフォルトはopsです。
.RE
