'\" t
.\"     Title: gfperf-metadata
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 19 May 2012
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFPERF\-METADATA" "1" "19 May 2012" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfperf-metadata \- Gfarm メタデータの性能測定を行う。
.SH "SYNOPSIS"
.HP \w'\fBgfperf\-metadata\fR\ 'u
\fBgfperf\-metadata\fR [\-n,\ \-\-number\ \fIテスト実施数\fR] [\-t,\ \-\-testdir\ \fIテストディレクトリ\fR] [\-u,\ \-\-unit\ \fI出力の単位\fR]
.SH "DESCRIPTION"
.PP
引数
\fIテストディレクトリ\fR
にテスト用のファイルやディレクトリを作成し、その実行性能を測定します。
.PP
測定する項目は次の通りです。
.PP
create
.RS 4
gfs_pio_create()またはcreat()の性能を測定します。 出力結果は１回辺りの平均値です。
.RE
.PP
readdir
.RS 4
gfs_opendir_caching()から\fIテスト実施数\fR分gfs_readdir()を行い、gfs_closedir()を実行するまでの性能を測定します。 posixの場合はopendir()から\fIテスト実施数\fR分readdir()を行い、closedir()を実行するまでの性能を測定します。 出力結果は上記測定にかかった時間を\fIテスト実施数\fRで割った平均値です，
.RE
.PP
readdir+stat
.RS 4
上記readdirの測定時に\fIテスト実施数\fR分gfs_lstat_cached()またはlstat()を実行した時間を足して測定したものです。 出力結果は測定にかかった時間を\fIテスト実施数\fRで割った平均値です。
.RE
.PP
unlink
.RS 4
gfs_unlink()またはunlink()の性能を測定します。 出力結果は１回辺りの平均値です。
.RE
.PP
mkdir
.RS 4
gfs_mkdir()またはmkdir()の性能を測定します。 出力結果は１回辺りの平均値です。
.RE
.PP
stat
.RS 4
gfs_lstat()またはlstat()の性能を測定します。 出力結果は１回辺りの平均値です。
.RE
.PP
chmod
.RS 4
gfs_chmod()またはchmod()の性能を測定します。 出力結果は１回辺りの平均値です。
.RE
.PP
utimes
.RS 4
gfs_utimes()またはutimes()の性能を測定します。 出力結果は１回辺りの平均値です。
.RE
.PP
rename
.RS 4
gfs_rename()またはrename()の性能を測定します。 出力結果は１回辺りの平均値です。
.RE
.PP
symlink
.RS 4
gfs_symlink()またはsymlink()の性能を測定します。 出力結果は１回辺りの平均値です。
.RE
.PP
readlink
.RS 4
gfs_readlink()またはreadlink()の性能を測定します。 出力結果は１回辺りの平均値です。
.RE
.PP
setxattr
.RS 4
gfs_setxattr()またはsetxattr()の性能を測定します。 出力結果は１回辺りの平均値です。
.RE
.PP
getxattr
.RS 4
gfs_getxattr()またはgetxattr()の性能を測定します。 出力結果は１回辺りの平均値です。
.RE
.PP
removexattr
.RS 4
gfs_removexattr()またはremovexattr()の性能を測定します。 出力結果は１回辺りの平均値です。
.RE
.PP
rmdir
.RS 4
gfs_rmdir()またはrmdir()の性能を測定します。 出力結果は１回辺りの平均値です。
.RE
.SH "OPTIONS"
.PP
\fB\-n, \-\-number\fR \fIテスト実施数\fR
.RS 4
それぞれの測定項目に対して何回実施するかを指定します。デフォルトは250です。
.RE
.PP
\fB\-t, \-\-testdir\fR \fIテストディレクトリ\fR
.RS 4
テストを実施するディレクトリを指定します。 gfarm url(gfarm:///で始まるもの)を指定した場合、該当のgfarm上のディレクトリに対してlibgfarmの関数を使用した場合の性能を測定します。 file url(file:///で始まるもの)を指定した場合、該当のunixファイルシステム上にposixの関数を使用した場合の性能を測定します。 デフォルトはgfarm:///tmpです。
.RE
.PP
\fB\-u, \-\-uinit\fR \fI出力の単位\fR
.RS 4
ops(operations per second)またはusecを指定します。指定した単位で出力を返します。デフォルトはopsです。
.RE
