'\" t
.\"     Title: gfprep
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 14 Jan 2017
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFPREP" "1" "14 Jan 2017" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfprep \- ファイルの複製を並列に作成する
.SH "SYNOPSIS"
.HP \w'\fBgfprep\fR\ 'u
\fBgfprep\fR [\-nqvdpPBU] [\-X\ \fIregexp\fR] [\-S\ \fIsource\-domainname\fR] [\-h\ \fIsource\-hostfile\fR] [\-D\ \fIdestination\-domainname\fR] [\-H\ \fIdestination\-hostfile\fR] [\-j\ \fInum\-of\-processes\fR] [\-J\ \fInum\-of\-processes\fR] [\-M\ \fItotal\-byte\fR] [\-z\ \fIminimum\-byte\fR] [\-Z\ \fImaximum\-byte\fR] [\-w\ \fIway\-of\-scheduling\fR] [\-W\ \fIkilobytes\-for\-threshold\fR] [\-s\ \fIKB/s\-to\-simulate\fR] [\-F\ \fInum\-for\-readahead\fR] [\-I\ \fIsec\-to\-update\fR] [\-mx] [\-N\ \fInum\-of\-replicas\fR] \fIpath\fR
.SH "DESCRIPTION"
.PP
\fBgfprep\fR
は、ファイルの複製を並列に作成します。
.PP
\fIpath\fR
がディレクトリの場合、 その下にあるすべてのファイルに対する複製を 作成します。
.PP
\fIpath\fR
には、 Gfarm URL または gfarm2fs 上のパスを指定できます。
.PP
作成先のホスト群を指定することにより、ファイルの複製を作成するホストを 指定することができます。ホスト群は、ドメイン名か、ホスト名を行ごとに記 述したホストファイルで指定します。ドメイン名とホストファイルを両方指定 した場合は、両方の条件に合うホスト群が選ばれます。また、作成元のホスト 群も指定可能です。その場合、そのホスト群に存在するファイルのみ複製が作 成されます。
.PP
\fBgfprep\fRは、なるべく複製を作成中ではないホストを選択してファイル複製を作 成します。作成元や作成先 1 ホストあたりの最大並列転送数は、ホストごと の CPU数です。 CPU 数については、\fBgfhost\fR
コマンドのマニュアルを参照して ください。
.PP
\fBgfprep\fR
は、ディレクトリを辿る際に、 ディレクトリエントリ情報も並列に取 得します。
.SH "GFPREP OPTIONS"
.PP
以下は
\fBgfprep\fR
専用のオプションです。
.PP
\fB\-N\fR \fInum\-of\-replicas\fR
.RS 4
ファイル複製数を指定します。 作成先のホスト群に十分な数の複製が存 在する場合、複製作成も複製削除も、どちらもしません。
.sp
このオプションを指定しない場合は、\-N 1 を指定したことになります。
.RE
.PP
\fB\-x\fR
.RS 4
\-N オプションで指定された数よりも多くのファイル複製が作成先のホス ト群に存在する場合は、余分なファイル複製を削除します。
.RE
.PP
\fB\-m\fR
.RS 4
作成元から作成先にファイルの複製を移動します。 \-mm のように 2 回指 定すると、作成元のファイルの複製を削除しません。
.sp
\-S, \-h, \-D, \-H のいずれかのオプションが必要です。
.sp
このオプションと \-N オプションは、どちらか一方を使用できます。
.RE
.SH "COMMON OPTIONS"
.PP
\fBgfpcopy\fR
には
\fBgfprep\fR
と共通のオプションがあります。
\fBgfpcopy\fR
のマニュアル を参照してください。
.SH "EXAMPLES"
.PP
ディレクトリ以下すべてのファイルの複製を作成します。
.sp
.if n \{\
.RS 4
.\}
.nf
$ gfprep \-N 3 gfarm:///dir
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
$ cd /mnt/gfarm2fs
$ gfprep \-N 3 dir
.fi
.if n \{\
.RE
.\}
.PP
足りなければ複製を増やし、余分な複製があれば削除します。
.sp
.if n \{\
.RS 4
.\}
.nf
$ gfprep \-N 3 \-x gfarm:///dir/file
.fi
.if n \{\
.RE
.\}
.PP
gfsd1\&.example\&.com にある複製を別のノードに移動します。
.sp
.if n \{\
.RS 4
.\}
.nf
$ gfprep \-m \-S gfsd1\&.example\&.com gfarm:///
.fi
.if n \{\
.RE
.\}
.SH "NOTES"
.PP
\-L または \-m オプションを使用しない場合は、指定した作成元の中から ファイルの複製、コピーが行われるとはとは限りません。
.PP
\fBgfprep\fR
コマンドは、
\fBgfmd\fR
と同じホストで実行するほうがよいです。
\fBgfmd\fR
と
\fBgfprep\fR
が距離的に離れている場合には、
\fBgfprep\fR
の動作が遅くなります。 そのような場合には、\-j または \-J オプションに大きな値を指定すると、 性能が改善するかもしれません。
.SH "SEE ALSO"
.PP
\fBgfrep\fR(1),
\fBgfpcopy\fR(1),
\fBgfhost\fR(1),
\fBgfarm2.conf\fR(5)
