.TH gfps 1 "1 May 2002"
.SH NAME

gfps \- 現在実行中のジョブを表示する。

.SH SYNOPSIS

.B gfps
[
.B \-al
]
[
.I ジョブID…
]

.SH DESCRIPTION

引数に指定したジョブIDに関する情報を表示します。
引数を省略した場合には、自ユーザー権限で実行中のジョブ全てを表示しま
す。

.SH OPTIONS

.TP
.B \-a
.br
全てのユーザーのジョブを表示します。
.TP
.B \-l
.br
より詳細な情報を表示します。
.TP
.B \-?
.br
引数オプションを表示します。



