'\" t
.\"     Title: gfquota
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 23 Mar 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFQUOTA" "1" "23 Mar 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfquota \- 現在の使用量と制限値を表示
.SH "SYNOPSIS"
.HP \w'\fBgfquota\fR\ 'u
\fBgfquota\fR [\fIオプション\fR]
.SH "DESCRIPTION"
.PP
\fBgfquota\fR
は、現在の使用量と制限値を表示します。 gfarmadm グループに所属している管理者は、ユーザ名やグループ名を指定する ことができます。 一般ユーザの場合は、そのユーザが所属するグループ名を指定することができ ます。
.PP
\fBgfedquota\fR
と
\fBgfquotacheck\fR
を 実行すると使用量のカウントと制限値が有効になり、
\fBgfquota\fR
で表示できるようになります。
.SH "OPTIONS"
.PP
\fB\-P NAME\fR
.RS 4
指定したパス名により特定のメタデータサーバを指定します。
.RE
.PP
\fB\-q\fR
.RS 4
使用量を表示しません。 制限値を超えていた場合に警告だけを表示します。
.RE
.PP
\fB\-u NAME\fR
.RS 4
指定したユーザ名の使用量と制限値を表示します。
.RE
.PP
\fB\-g NAME\fR
.RS 4
指定したグループ名の使用量と制限値を表示します。
.RE
.PP
\fB\-h\fR
.RS 4
数字を「M(メガ)」のような単位つきで読みやすく表示します。 単位には2の累乗を用いますので、「M」は 1,048,576 を意味します。
.RE
.PP
\fB\-H\fR
.RS 4
数字を「M(メガ)」のような単位つきで読みやすく表示します。 単位には10の累乗を用いますので、「M」は 1,000,000 を意味します。
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します。
.RE
.SH "SEE ALSO"
.PP

\fBgfedquota\fR(1),
\fBgfquotacheck\fR(1),
\fBgfusage\fR(1)
