'\" t
.\"     Title: gfrepattr
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 14 Jun 2012
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFREPATTR" "1" "14 Jun 2012" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfrepattr \- Gfarm ファイルシステムにおけるレプリケーション設定を操作する
.SH "SYNOPSIS"
.HP \w'\fBgfrepattr\fR\ 'u
\fBgfrepattr\fR [\-s | \-r] [\-c | \-m] [\-h] \fIARG\fR [\fIARG\fR...]
.HP \w'\fBgfrepattr\fR\ 'u
\fBgfrepattr\fR \-s [\-c | \-m] [\-h] \fIpath\fR \fIattr\fR
.HP \w'\fBgfrepattr\fR\ 'u
\fBgfrepattr\fR \-r [\-h] \fIpath\fR [\fIpath\fR...]
.HP \w'\fBgfrepattr\fR\ 'u
\fBgfrepattr\fR [\-h] \fIpath\fR [\fIpath\fR...]
.SH "DESCRIPTION"
.PP

\fBgfrepattr\fR
はファイルまたはディレクトリのレプリケーション属性を操作します。 レプリケーション属性は\fBレプリケーション属性を基にしたファイルレプリケーション\fRに使用されます。 レプリケーション属性はホストグループ名とそのホストグループ内での最大の複製数から構成されます。
.PP
デフォルトでは指定したファイルまたはディレクトリのレプリケーション属性を表示します。
.SH "OPTIONS"
.PP
\fB\-s\fR
.RS 4
ファイルまたはディレクトリにレプリケーション属性を設定します。
.sp
\-s オプションには引数にレプリケーション属性
\fIattr\fR
が必要です。
.sp
attr は以下の BNF で定義されます:
.sp
.if n \{\
.RS 4
.\}
.nf
        attr := | anattr \*(Aq,\*(Aq attr
        anattr := string \*(Aq:\*(Aq integer
      
.fi
.if n \{\
.RE
.\}
.sp
e\&.g\&.)
.sp
.if n \{\
.RS 4
.\}
.nf
        \*(Aqgroup0:2\*(Aq
        \*(Aqgroup0:1,group1:3\*(Aq
      
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fB\-r\fR
.RS 4
ファイルまたはディレクトリからレプリケーション属性を消去します。
.RE
.PP
\fB\-c\fR
.RS 4
レプリケーション属性が既に設定されている場合はエラーを返します。 このオプションの使用には \-s オプションが必要です。
.RE
.PP
\fB\-m\fR
.RS 4
レプリケーション属性が未設定の場合はエラーを返します。 このオプションの使用には \-s オプションが必要です。
.RE
.PP
\fB\-h\fR
.RS 4
シンボリックリンクを解決します。
.RE
.SH "SEE ALSO"
.PP

\fBgfhostgroup\fR(1)
