.TH gfrep 1 "1 May 2002"
.SH NAME

gfrep \- Gfarm ファイルのレプリカを作成する。

.SH SYNOPSIS

.B gfrep
.B \-H
.I ホスト指定ファイル
.I gfarm-URL

.SH DESCRIPTION

引数 Gfarm-URL のレプリカを、ホスト指定ファイルに記述されたホストに作ります。
ホストファイル中のホスト名の数は、フラグメントの数と一致している必要
があります。

.SH OPTIONS

.TP
.B \-H
.I ホスト指定ファイル
.br
フラグメントを取り出すホスト名のリストを指定します。
ホスト名は、各行に一ホストずつ記述します。
.TP
.B \-?
.br
引数オプションを表示します。



