.TH gfrep 1 "1 May 2002"
.SH NAME

gfrep \- Gfarm ファイルのレプリカを作成する。

.SH SYNOPSIS

.B gfrep
.B \-H
.I ホスト指定ファイル
.I gfarm-URL

.B gfrep
.B \-D
.I ドメイン名
.I gfarm-URL

.B gfrep
.B \-I
.I フラグメント番号
[
.B \-s
.I 複製元ホスト
]
.B \-d
.I 複製先ホスト
.I gfarm-URL

.SH DESCRIPTION

引数 Gfarm-URL の複製を、ホスト指定ファイルに記述されたホス
トあるいは指定されたドメイン名のホストに作成します。

\-I オプションでフラグメント番号あるいはセクション名を指定し
た場合は，指定したファイルフラグメントの複製を -d オプション
で指定したホストに作成します．-s オプションが指定された場合
は，指定されたホストからファイルの複製を作成します．

.SH OPTIONS

.TP
.B \-H
.I ホスト指定ファイル
.br
各フラグメントの複製を作成するホスト名のリストを指定します。
ホスト名は、各行に一ホストずつ記述します。ホストファイル中
のホスト名の数は、フラグメントの数と一致している必要があり
ます。
.br
ファイル名として ``-'' を指定した場合、標準入力からホス
ト名のリストを読み込みます。
.TP
.B \-D
.I ドメイン名
.br
各フラグメントの複製を作成するホストのドメイン名を指定します。
.TP
.B \-I
.I フラグメント番号
.br
複製を作成するファイルフラグメントを指定します。
ファイルフラグメントはフラグメント番号あるいはアーキテク
チャなどのセクション名です．
.TP
.B \-s
.I 複製元ホスト
.br
\-I オプションと共に指定し，ファイルフラグメントの複製元
のホストを指定します．
.TP
.B \-d
.I 複製先ホスト
.br
\-I オプションと共に指定し，ファイルフラグメントの複製先
のホストを指定します．
.TP
.B \-?
.br
引数オプションを表示します。
