.TH gfrun 1 "1 May 2002"
.SH NAME

gfrun, gfrsh, gfssh \- ファイルシステムノードで、gfarm 並列コマンドを実行する

.SH SYNOPSIS

.B gfrun
[ -G
.I gfarm-URL
| -H
.I ホスト指定ファイル
]
.I プログラム名
.I 引数…
.br

.B gfrsh
[ -G
.I gfarm-URL
| -H
.I ホスト指定ファイル
]
.I プログラム名
.I 引数…
.br

.B gfssh
[ -G
.I gfarm-URL
| -H
.I ホスト指定ファイル
]
.I プログラム名
.I 引数…
.br

.SH DESCRIPTION

並列プログラムを実行します．実行されるファイルシステムノードは，
\-G オプションで指定される Gfarm ファイル \fIgfarm-URL\fP の
ファイル・アフィニティ・スケジューリングにより決定されます．
ファイル・アフィニティ・スケジューリングでは，指定された Gfarm
ファイルのそれぞれのファイル断片に対し，複製が格納されている
ノードのうち一ノードが選ばれます．つまり，ファイル断片の数と
同数のプロセスが，ファイル断片を格納しているノードで実行され
るということになります．

\-H オプションで \fIホスト指定ファイル\fP が指定された場合は，
そのファイルに記述されたノードで並列プログラムを実行します．

\-Gオプションも\-Hオプションも指定されない場合は，引数に指定され
た既に存在するGfarmファイルのうち一番はじめのファイルを利用して，
ファイル・アフィニティ・スケジューリングされます．

指定されたファイルシステムノード群に対して、並列プログラムの
それぞれのプロセスは
「gfrcmd ホスト プログラム名 \-N 全ノード数 \-I ノード番号 引数…」
で実行されます。

gfrsh や gfssh コマンドは、gfrcmd の代わりに rsh、ssh を
利用することを除いて、gfrun と同様です。

プログラム名としては、gfreg コマンドで登録したプログラムの gfarm-URL 
も指定できます。

.SH OPTIONS

.TP
.B \-G
.I gfarm-URL
.br
gfarm-URL のファイル・アフィニティ・スケジューリングにより
並列プログラムを実行します．
.TP
.B \-H
.I ホスト指定ファイル
.br
並列プログラムを実行するファイルシステムノード群を記載したファイル名を
指定します。
ホスト名は、各行に一ホストずつ記述します。
.br
ファイル名として ``-'' を指定した場合、標準入力からホスト名のリストを
読み込みます。
.TP
.B \-?
.br
引数オプションを表示します。

.SH ENVIROMNENT VARIABLES

.TP
.B GFRUN_CMD
.br
遠隔起動コマンドを指定します．globus-job-runを指定すれ
ば，gfrunはglobus-job-run を使ってそれぞれのプロセスを
起動します．
