.TH gfrun(1), gfrsh(1), gfssh 1 "1 May 2002"
.SH NAME

gfrun, gfrsh, gfssh \- 計算プールで、gfarm 並列コマンドを実行する

.SH SYNOPSIS

.B gfrun
.I プログラム名
.I 引数…
.br

.B gfrsh
.I プログラム名
.I 引数…
.br

.B gfssh
.I プログラム名
.I 引数…
.br

.SH DESCRIPTION

引数に指定した Gfarm入力ファイル の存在する計算プールのホスト群に対して、
「gfrcmd ホスト プログラム名 \-N 全ノード数 \-I ノード番号」を実行します。

gfrsh や gfssh コマンドは、gfrcmd の代わりに rsh、ssh を利用すること
を除いて、gfrun と同様です。

プログラム名としては、gfreg コマンドで登録したプログラムの gfarm-URL 
も指定できます。

.SH OPTIONS

.TP
.B \-H
.I パス名
.br
Gfarm入力ファイルの存在するホスト群の代わりに、パス名で指定したファイル
に記述されたホスト群でコマンドを実行します。
パス名として、gfarm-URL を指定すると、その Gfarm ファイルの存在す
るホスト群でコマンドを実行します。
.TP
.B \-?
.br
引数オプションを表示します。

.SH BUGS

入力ファイルか否かは、単に、指定された Gfarm URL が既に存在するかど
うかだけで判断するので、Gfarm URL の綴りを間違えると、意図したホスト
で実行されません。確実に指定したい場合には \-H オプションをご利用く
ださい。

