'\" t
.\"     Title: gfsched
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 22 Dec 2014
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFSCHED" "1" "22 Dec 2014" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfsched \- ファイルシステムノードをスケジューリングし、利用可能なノードを表示
.SH "SYNOPSIS"
.HP \w'\fBgfsched\fR\ 'u
\fBgfsched\fR \-f\ \fIgfarm\-URL\fR [\-D\ \fIドメイン名\fR] [\-n\ \fIノード数\fR] [\-LMOSclw]
.HP \w'\fBgfsched\fR\ 'u
\fBgfsched\fR [\-P\ \fIgfarm\-URL\fR] [\-D\ \fIドメイン名\fR] [\-n\ \fIノード数\fR] [\-LMOSlw]
.SH "DESCRIPTION"
.PP

\fBgfsched\fR
に
\fB\-f\fR
\fIgfarm\-URL\fR
オプションを 指定した場合、そのgfarmファイルを保持するファイルシステムノードの うちで、現在利用可能なもの表示します。
.PP

\fB\-f\fRオプションを指定しなかった場合、利用可能な ファイルシステムノードを表示します。この場合、
\fB\-P\fR
\fIgfarm\-URL\fR
オプションで パス名か gfarm URL を指定することにより、表示対象のメタデータサーバを 切替えることができます。
.SH "OPTIONS"
.PP
\fB\-D\fR \fIドメイン名\fR
.RS 4
ドメイン名ないしホスト名を指定し、検索対象のファイルシステムノードを 絞ります。
.RE
.PP
\fB\-L\fR
.RS 4
そのホストに対して、認証が成功するか否かの確認を省略します。 高速になりますが、認証不能なホストがスケジューリングされてしまう 危険があります。
.RE
.PP
\fB\-M\fR
.RS 4
メタデータサーバに問い合わせた結果のみを表示し、クライアント側での スケジューリング処理を行ないません。 このオプションを指定すると、動作は高速になりますが、ネットワーク的に到 達不能なホストや、認証不能なホストが表示される危険があります。
.RE
.PP
\fB\-O\fR
.RS 4
gfsched コマンドを実行しているホストとは異なるホストである ファイルシステムノードのみ表示します。
.RE
.PP
\fB\-P\fR \fIgfarm\-URL\fR
.RS 4
ファイルシステムノードを管理するメタデータサーバを特定する ために、gfarm\-URL ないしパス名を指定します。 このオプションは、\fB\-f\fR
オプションと排他的です。
.RE
.PP
\fB\-S\fR
.RS 4
gfsched コマンドを実行しているホストと同一ホストである ファイルシステムノードのみ表示します。
.RE
.PP
\fB\-f\fR \fIgfarm\-URL\fR
.RS 4
指定したファイルについて、その複製を保持するファイルシステムノードを 検索します。 このオプションは、\fB\-P\fR
オプションと排他的です。
.RE
.PP
\fB\-c\fR
.RS 4
オプション「\fB\-f\fR」で指定したファイルが存在しない 場合で、かつ、このオプションを指定した場合、ファイルを新規作成した 場合のスケジューリング情報を表示します。
.sp
現在、このオプションを利用すると、指定したファイルを新規作成します。 この挙動は将来変更される可能性があるのでご注意ください。
.RE
.PP
\fB\-l\fR
.RS 4
ホスト名のみならず、ポート番号も表示します。 このオプションの表示形式は、将来変更される可能性がありますのでご注意ください。
.RE
.PP
\fB\-n\fR \fIノード数\fR
.RS 4
指定した数をファイルシステムノードの表示を試みます。 ノード数がその数に満たない場合には、そこで表示を打ち切ります。 このオプションを指定しない場合、条件を満たす全ノードを表示します。
.RE
.PP
\fB\-w\fR
.RS 4
ファイルの書き込みを行なう前提で、スケジューリングを行ないます。 このオプションを指定した場合、ディスクの空き容量が足りないファイルシステム ノードは除外されます。
.sp
このオプションと、\fB\-f\fR
オプションを同時に指定し、 かつ、そのファイルが既存のプロセスによって書き込みオープンされている場合には、
\fB\-n\fR
の指定に関わらず、現在このファイルの書き込み用に 割り当てられているファイルシステムノード 1つのみを表示します。
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します。
.RE
.SH "EXAMPLES"
.PP
以下は、メタデータサーバが動作中であると把握している、ファイルシステムノードを 問い合わせる例です。
.sp
.if n \{\
.RS 4
.\}
.nf
$ gfsched \-M
.fi
.if n \{\
.RE
.\}
