'\" t
.\"     Title: gfsetfacl
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 4 Feb 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFSETFACL" "1" "4 Feb 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfsetfacl \- Gfarm ファイルのアクセス制御リストを設定する
.SH "SYNOPSIS"
.HP \w'\fBgfsetfacl\fR\ 'u
\fBgfsetfacl\fR [\fIオプション\fR] [\fIpath\fR...]
.SH "DESCRIPTION"
.PP
\fBgfsetfacl\fR
は Gfarm ファイルシステム上にある ファイルやディレクトリのアクセスコントロールリスト (ACL) を設定します．
.SH "OPTIONS"
.PP
\fB\-b\fR
.RS 4
すべての拡張 ACL エントリを削除します． 基本 ACL (所有者，グループ，その他) は削除されません．
.RE
.PP
\fB\-k\fR
.RS 4
デフォルト ACL だけを削除します．
.RE
.PP
\fB\-n\fR
.RS 4
ACL マスクエントリを再計算しません．gfsetfacl コマンドデフォルト の挙動は，マスクエントリが指定されなかった場合だけマスクエントリを再計 算します．
.RE
.PP
\fB\-r\fR
.RS 4
常に ACL マスクエントリを再計算します．マスクエントリを指定したと しても再計算します．(\-n オプションも参照してください．)
.RE
.PP
\fB\-t\fR
.RS 4
テストモードです．ファイルやディレクトリの ACL を変更する代わりに， ACL 入力と変更予定の新しい ACL を文字列で表示します．
.RE
.PP
\fB\-m\fR \fIacl_spec\fR
.RS 4
ファイルやディレクトリの ACL エントリを追加または置換するために， ACL エントリの文字列表現をこのオプションで指定します． 複数の ACL エントリをコンマ文字 (`,\*(Aq) で区切ります．
.RE
.PP
\fB\-M\fR \fIacl_file\fR
.RS 4
ファイルやディレクトリの ACL エントリを追加または置換するために， ACL 文字列表現が記述されたファイルまたは標準入力 (`\-\*(Aq) を指定します． この ACL ファイル入力は gfgetfacl コマンドの出力を受け付けます．
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します．
.RE
.SH "ACL ENTRIES"
.PP
gfsetfacl コマンドは以下の ACL エントリ書式を認識します． perms フィールドは許可を表す文字を組み合わせです． デフォルト ACL エントリは d[efault:] 接頭辞を持ちます．
.PP
[d[efault:]u[ser]::perms
.RS 4
所有者の許可
.RE
.PP
[d[efault:]u[ser]:username:perms
.RS 4
指名ユーザの許可
.RE
.PP
[d[efault:]g[roup]::perms
.RS 4
ファイルグループの許可
.RE
.PP
[d[efault:]g[roup]:groupname:perms
.RS 4
指名グループの許可
.RE
.PP
[d[efault:]m[ask]::perms
.RS 4
実行権のマスク(最大の許可) (所有者とその他、以外に効果)
.RE
.PP
[d[efault:]o[ther]::perms
.RS 4
その他への許可
.RE
.SH "EXAMPLES"
.PP
指名ユーザへの読み込みアクセスを許可する．
.RS 4
gfsetfalc \-m u:testuser:r filename
.RE
.PP
filename2 の ACL をfilename1 の ACL で置換する．
.RS 4
gfgetfacl filename1 | gfsetfacl \-b \-M \- filename2
.RE
.PP
長い形式の ACL 文字列表現
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
# comment
user::rw\-
user:testuser:rw\-       #effective:r\-\-
group::r\-\-
group:testgroup:rw\-     #effective:r\-\-
mask::r\-\-
other::r\-\-
default:user::rwx
default:group::r\-x
default:other::r\-x
.fi
.if n \{\
.RE
.\}
.RE
.PP
短い形式の ACL 文字列表現
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
u::rw,u:user1:rw,g::r,g:group1:rw,m::r,o::r,d:u::rwx,d:g::rx,d:o::rx
.fi
.if n \{\
.RE
.\}
.RE
.SH "SEE ALSO"
.PP

\fBgfgetfacl\fR(1)
