'\" t
.\"     Title: gfservice-agent
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 6 Jun 2013
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFSERVICE\-AGENT" "1" "6 Jun 2013" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfservice-agent \- \fBgfservice\fR のエージェント
.SH "SYNOPSIS"
.HP \w'\fBgfservice\-agent\fR\ 'u
\fBgfservice\-agent\fR [\fIオプション\fR] ホスト\ ID サブコマンド [\fI引数\ \&.\&.\&.\fR]
.SH "DESCRIPTION"
.PP

\fBgfservice\-agent\fR
は、\fBgfservice\fR
の エージェントです。
\fBgfservice\fR
を用いて操作したいホストすべてに、この エージェントをインストールする必要があります。
\fBgfservice\fR
と異なり、設定ファイルは読み込みません。
.PP

\fBgfservice\-agent\fR
は、ユーザが直接実行することを意図 して作成されたものではありません。 日常の利用では、SSH と Sudo を介して
\fBgfservice\fR
コマンド によって実行されるだけです。
.PP
ホスト ID 引数は
\fBgfservice\fR
のものと同じですが、
\fBgfservice\-agent\fR
ではホスト ID をホストの種別 ("gfmd", "gfsd", "client" のいずれか) を区別するため、および デバッグメッセージのためにしか使っていません。
.PP

\fBgfservice\-agent\fR
のサブコマンド名は
\fBgfservice\fR
のものに似ていますが、引数は異なります。 たとえば、\fBgfservice\-agent\fR
の
\fBunmount\fR
サブコマンドは、 「\fIdirectory\fR=\fIディレクトリ\fR」 という引数をとります。
.sp
.if n \{\
.RS 4
.\}
.nf
	gfservice\-agent client3 unmount directory=/somewhere
.fi
.if n \{\
.RE
.\}
.PP
これに対して、\fBgfservice\fR
では、 「\fIディレクトリ\fR」という引数をとります。
.sp
.if n \{\
.RS 4
.\}
.nf
	gfservice unmount client3 /somewhere
.fi
.if n \{\
.RE
.\}
.PP

\fBgfservice\-agent\fR
の引数はほとんどすべて、「キー=値」 という形になっています。 複数の引数をとる場合、引数の順序は任意です。
\fBgfservice\-agent\fR
は、未知のキーを無視します。
.SH "OPTIONS"
.PP
\fB\-d\fR
.RS 4
デバッグ情報を出力します。
.RE
.SH "SUB-COMMANDS"
.PP

\fBgfservice\-agent\fR
は現在のところ、次のサブコマンドを 認識します。
.PP
\fBget\-config\-gfarm\-param\fR \fIparam\fR=\fIパラメタ名\fR \fIconfig\-gfarm\-options\fR=\fIオプション\fR
.RS 4
「\fBconfig\-gfarm \-T\fR」コマンドを実行して、 「\fIパラメタ名\fR
」の値を標準出力に出力します。 引数「\fIparam\fR=\fIパラメタ名\fR」 が省略された場合は、「\fBconfig\-gfarm \-T\fR」コマンドの 結果すべてを出力します。
.RE
.PP
\fBget\-config\-gfsd\-param\fR \fIparam\fR=\fIパラメタ名\fR \fIconfig\-gfsd\-options\fR=\fIオプション\fR
.RS 4
「\fBconfig\-gfsd \-T\fR」コマンドを実行して、 「\fIパラメタ名\fR」の値を標準出力に 出力します。 引数「\fIparam\fR=\fIパラメタ名\fR」 が省略された場合は、「\fBconfig\-gfsd \-T\fR」コマンドの 結果すべてを出力します。
.RE
.PP
\fBbackend\-db\-status\fR \fIconfig\-gfarm\-options\fR=\fIオプション\fR
.RS 4
バックエンドデータベースが動作中であれば、終了コード 0 で終了します。 それ以外の場合は、1 で終了します。
.RE
.PP
\fBgfmd\-status\fR \fIconfig\-gfarm\-options\fR=\fIオプション\fR
.RS 4
gfmd が動作中であれば、終了コード 0 で終了します。 それ以外の場合は、1 で終了します。
.RE
.PP
\fBgfsd\-status\fR \fIconfig\-gfsd\-options\fR=\fIオプション\fR
.RS 4
gfsd が動作中であれば、終了コード 0 で終了します。 それ以外の場合は、1 で終了します。
.RE
.PP
\fBstart\-backend\-db\fR \fIconfig\-gfarm\-options\fR=\fIオプション\fR \fItimeout\fR=\fI時間\fR
.RS 4
バックエンドデータベースが実行中でなければ、実行を開始します。
.RE
.PP
\fBstart\-gfmd\fR \fIconfig\-gfarm\-options\fR=\fIオプション\fR \fItimeout\fR=\fI時間\fR
.RS 4
gfmd が実行中でなければ、実行を開始します。
.RE
.PP
\fBstart\-gfsd\fR \fIconfig\-gfsd\-options\fR=\fIオプション\fR \fItimeout\fR=\fI時間\fR
.RS 4
gfsd が実行中でなければ、実行を開始します。
.RE
.PP
\fBconfig\-gfarm\fR \fIconfig\-gfarm\-options\fR=\fIオプション\fR
.RS 4
「\fBconfig\-gfarm\fR」コマンドを実行します。
.RE
.PP
\fBconfig\-gfarm\-master\fR \fIconfig\-gfarm\-options\fR=\fIオプション\fR
.RS 4
「\fBconfig\-gfarm\fR
\fI\-r\fR」コマンドを実行 します。
.RE
.PP
\fBconfig\-gfsd\fR \fIconfig\-gfsd\-options\fR=\fIオプション\fR
.RS 4
「\fBconfig\-gfsd\fR」コマンドを実行します。
.RE
.PP
\fBunconfig\-gfarm\fR \fIconfig\-gfarm\-options\fR=\fIオプション\fR
.RS 4

\fBstop\-gfarm\fR
サブコマンドを実行して、その後 gfmd と バックエンドデータベースが作成したファイルやディレクトリをすべて削除します。
.RE
.PP
\fBunconfig\-gfsd\fR \fIconfig\-gfsd\-options\fR=\fIオプション\fR
.RS 4
サブコマンド
\fBstop\-gfsd\fR
を実行し、その後 gfsd が作成した ファイルやディレクトリをすべて削除します。
.RE
.PP
\fBunconfig\-client\fR \fIconfig\-gfsd\-options\fR=\fIオプション\fR
.RS 4

gfarm2\&.conf
ファイルと共有秘密鍵ファイルを削除します。
.RE
.PP
\fBpromote\fR \fIconfig\-gfarm\-options\fR=\fIオプション\fR
.RS 4

\fBgfmd\fR
をスレーブからマスターへ昇格させます。
.RE
.PP
\fBpromote\-gfmd\fR \fIconfig\-gfarm\-options\fR=\fIオプション\fR
.RS 4
サブコマンド
\fBpromote\fR
の別名です。
.RE
.PP
\fBmount\fR \fIdirectory\fR=\fIディレクトリ\fR \fIoptions\fR=\fIオプション\fR
.RS 4
Gfarm2 ファイルシステムを「\fIディレクトリ\fR」に マウントします。
.RE
.PP
\fBunmount\fR \fIdirectory\fR=\fIディレクトリ\fR
.RS 4
「\fIディレクトリ\fR」にマウントされた Gfarm2 ファイルシステムをアンマウントします。
.RE
.PP
\fBumount\fR \fIdirectory\fR=\fIディレクトリ\fR
.RS 4
サブコマンド
\fBunmount\fR
の別名です。
.RE
.PP
\fBset\-gfmd\-conf\fR \fIdirective\fR=\fI設定名称\fR \fIvalue\fR=\fI値\fR
.RS 4

gfmd\&.conf
ファイルに、
.sp
.if n \{\
.RS 4
.\}
.nf
	\fI設定名称\fR \fI値\fR
.fi
.if n \{\
.RE
.\}
.sp
という行を追加します。
.RE
.PP
\fBset\-gfarm\-conf\fR \fIdirective\fR=\fI設定名称\fR \fIvalue\fR=\fI値\fR
.RS 4

gfarm2\&.conf
ファイルに、
.sp
.if n \{\
.RS 4
.\}
.nf
	\fI設定名称\fR \fI値\fR
.fi
.if n \{\
.RE
.\}
.sp
という行を追加します。
.RE
.PP
\fBset\-gfsd\-conf\fR \fIdirective\fR=\fI設定名称\fR \fIvalue\fR=\fI値\fR
.RS 4

gfsd\&.conf
ファイルに、
.sp
.if n \{\
.RS 4
.\}
.nf
	\fI設定名称\fR \fI値\fR
.fi
.if n \{\
.RE
.\}
.sp
という行を追加します。
.RE
.PP
\fBunset\-gfmd\-conf\fR \fIdirective\fR=\fI設定名称\fR
.RS 4
「\fI設定名称\fR」行を
gfmd\&.conf
ファイルから削除します。
.RE
.PP
\fBunset\-gfarm\-conf\fR \fIdirective\fR=\fI設定名称\fR
.RS 4
「\fI設定名称\fR」行を
gfarm\&.conf
ファイルから削除します。
.RE
.PP
\fBunset\-gfsd\-conf\fR \fIdirective\fR=\fI設定名称\fR
.RS 4
「\fI設定名称\fR」行を
gfsd\&.conf
ファイルから削除します。
.RE
.PP
\fBbackup\-backend\-db\fR
.RS 4
バックエンドデータベースのバックアップを行い、バックアップデータを標準出力 へ出力します。
.RE
.PP
\fBbackup\-gfmd\-conf\fR
.RS 4

gfmd\&.conf
ファイルを標準出力に出力します。
.RE
.PP
\fBbackup\-gfarm\-conf\fR
.RS 4

gfarm2\&.conf
ファイルを標準出力に出力します。
.RE
.PP
\fBbackup\-gfsd\-conf\fR
.RS 4

gfsd\&.conf
ファイルを標準出力に出力します。
.RE
.PP
\fBbackup\-usermap\fR
.RS 4

usermap
ファイルを標準出力に出力します。
.RE
.PP
\fBbackup\-shared\-key\fR
.RS 4

$HOME/\&.gfarm_shared_key
ファイルを標準出力に 出力します。
.RE
.PP
\fBrestore\-backend\-db\fR
.RS 4
バックエンドデータベースをリストアします。 バックアップデータは、標準入力から読み込みます。
.RE
.PP
\fBrestore\-gfmd\-conf\fR
.RS 4

gfmd\&.conf
ファイルをリストアします。 バックアップデータは、標準入力から読み込みます。
.RE
.PP
\fBrestore\-gfarm\-conf\fR
.RS 4

gfarm2\&.conf
ファイルをリストアします。 バックアップデータは、標準入力から読み込みます。
.RE
.PP
\fBrestore\-gfsd\-conf\fR
.RS 4

gfsd\&.conf
ファイルをリストアします。 バックアップデータは、標準入力から読み込みます。
.RE
.PP
\fBrestore\-usermap\fR
.RS 4

usermap
ファイルをリストアします。 バックアップデータは、標準入力から読み込みます。
.RE
.PP
\fBrestore\-shared\-key\fR
.RS 4

$HOME/\&.gfarm_shared_key
ファイルをリストアします。 バックアップデータは、標準入力から読み込みます。
.RE
.PP
\fBgfcmd\fR \fIcmd\fR=\fIコマンド名\fR \fIargs\fR="\fIコマンドの引数 \&.\&.\&.\fR"
.RS 4
Gfarm コマンドを実行します。
.RE
.PP
\fBgrid\-proxy\-init\fR \fIargs\fR="\fIコマンドの引数 \&.\&.\&.\fR"
.RS 4

\fBgrid\-proxy\-init\fR
コマンドを実行します。
.RE
