'\" t
.\"     Title: gfstat
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 9 Sep 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFSTAT" "1" "9 Sep 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfstat \- Gfarm ファイルまたはディレクトリの情報を表示する
.SH "SYNOPSIS"
.HP \w'\fBgfstat\fR\ 'u
\fBgfstat\fR [\fIoptions\fR] [\fIpath\fR...]
.SH "DESCRIPTION"
.PP
指定したファイルあるいはディレクトリの情報を表示します．
.SH "OPTIONS"
.PP
\fB\-M\fR
.RS 4
メタデータ・サーバの情報も表示します．
.RE
.PP
\fB\-c\fR
.RS 4
ファイル複製の数のみを表示します．
.RE
.PP
\fB\-l\fR
.RS 4
シンボリックリンクを辿らず．リンク自身の情報を表示します．
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します．
.RE
