'\" t
.\"     Title: gfstress.rb
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 7 Mar 2013
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFSTRESS\&.RB" "1" "7 Mar 2013" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfstress.rb \- Gfarm 負荷試験を行う
.SH "SYNOPSIS"
.HP \w'\fBgfstress\&.rb\fR\ 'u
\fBgfstress\&.rb\fR [\-t,\ \-\-testdir\ \fIテストディレクトリ\fR] [\-m,\ \-\-gfarm2fs\ \fIgfarm2fsマウントポイント\fR] [\-n,\ \-\-number\ \fI擬似ユーザ数\fR] [\-T,\ \-\-timeout\ \fI制限時間(秒)\fR]
.SH "DESCRIPTION"
.PP
\fIテストディレクトリ\fRを使用してgfperf\-metadata, gfperf\-tree, gfperf\-read, gfperf\-write, gfperf\-replicaを同時並列に起動し、高負荷状態を作り出します。gfschedを呼び出し、各gfsdに対し並列にgfperf\-read, gfperf\-write, gfperf\-replicaを実行します。
.PP
本コマンドは、Ctrl\-CまたはTERMシグナルで停止させない限り、エラーを検出するまでデフォルトでは動作し続けます。\-T オプションで制限時間を指定できます。
.PP
擬似ユーザ数はgfperf\-metadata, gfperf\-read, gfperf\-write, gfperf\-replicaを一セットとし、何セットを同時実行するかを指定するものです。本コマンドを同時に複数個呼出したのと同等の効果が得られます。
.PP
gfarm2fsマウントポイントが与えられた場合はlibgfarmを使用した通常の負荷に加えてgfarm2fsを経由した負荷も同時に与えます。
.SH "OPTIONS"
.PP
\fB\-t, \-\-testdir\fR \fIテストディレクトリ\fR
.RS 4
高負荷試験に使用するディレクトリを指定します。デフォルトはgfarm:///stressです。 テスト終了後にテストデータを削除します。
.RE
.PP
\fB\-m, \-\-gfarm2fs\fR \fIgfarm2fsマウントポイント\fR
.RS 4
gfarm2fsのマウントポイントを指定します。
.RE
.PP
\fB\-n, \-\-number\fR \fI擬似ユーザ数\fR
.RS 4
本コマンドを複数個同時に呼出したのと同じ効果が得られます。
.RE
.PP
\fB\-T, \-\-timeout\fR \fI秒数\fR
.RS 4
制限時間を指定します。
.RE
