'\" t
.\"     Title: gfuser
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 20 Jan 2010
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFUSER" "1" "20 Jan 2010" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfuser \- Gfarm ユーザ管理コマンド
.SH "SYNOPSIS"
.HP \w'\fBgfuser\fR\ 'u
\fBgfuser\fR [\-P\ \fIpath\fR] [\-l] [\fIuser\fR...]
.HP \w'\fBgfuser\fR\ 'u
\fBgfuser\fR [\-P\ \fIpath\fR] \-c username realname homedir gsi_dn
.HP \w'\fBgfuser\fR\ 'u
\fBgfuser\fR [\-P\ \fIpath\fR] \-m username realname homedir gsi_dn
.HP \w'\fBgfuser\fR\ 'u
\fBgfuser\fR [\-P\ \fIpath\fR] \-d username
.SH "DESCRIPTION"
.PP
Gfarm ファイルシステムにおける利用ユーザの管理を行います． デフォルトでは登録ユーザを表示します． ユーザ名が指定されたら，指定されたユーザを表示します． Gfarmファイルシステムの管理者は，\-c，\-m，\-d オプションを指定することにより，それぞれユーザの登録， 登録情報変更，登録削除を行うことができます．
.SH "OPTIONS"
.PP
\fB\-P\fR \fIパス名\fR
.RS 4
このコマンドがアクセスするメタデータサーバを特定するための パス名または Gfarm URL を指定します。 省略した場合は、「/」を指定したのと同じ意味になります。
.RE
.PP
\fB\-l\fR
.RS 4
登録ユーザの情報を詳細に表示します．
.RE
.PP
\fB\-c\fR
.RS 4
ユーザの登録を行います． 登録にはGfarmファイルシステムに置けるグローバルユーザ名， 実ユーザ名，Gfarm上のホームディレクトリ，GSI認証における ユーザ証明書のSubject DNを指定します． 実ユーザ名，Subject DNなどに空白が含まれる場合は， ダブルクオートなどで括る必要があります． Gfarmの管理者が実行可能です．
.RE
.PP
\fB\-m\fR
.RS 4
登録ユーザの情報の変更を行います． 変更したいグローバルユーザ名， 実ユーザ名，Gfarm上のホームディレクトリ，GSI認証における ユーザ証明書のSubject DNを指定します． Gfarmの管理者が実行可能です．
.RE
.PP
\fB\-d\fR
.RS 4
登録ユーザの情報を消去します． 消去したいグローバルユーザ名を指定します． Gfarmの管理者が実行可能です．
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します．
.RE
.SH "SEE ALSO"
.PP

\fBgfgroup\fR(1)
