.TH gfwhere 1 "1 May 2002"
.SH NAME

gfwhere \- Gfarm ファイルのレプリカの所在を表示する。

.SH SYNOPSIS

.B gfwhere
.I gfarm-URL

.SH DESCRIPTION

指定した Gfarm-URL を構成するファイルについて、レプリカの所在を表示
します。

フラグメント化されたファイルの場合、各行は、下記の形式になります。
.in +.5i
.nf
フラグメント番号: レプリカのあるホスト名....
.fi
.in

また、実行ファイルの場合、各行は、下記の形式になります。
.in +.5i
.nf
アーキテクチャ: レプリカのあるホスト名....
.fi
.in

.SH OPTIONS

.TP
.B \-?
.br
引数オプションを表示します。
