'\" t
.\"     Title: gfwhere
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 12 Mar 2016
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFWHERE" "1" "12 Mar 2016" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfwhere \- Gfarm ファイルのレプリカの所在を表示する。
.SH "SYNOPSIS"
.HP \w'\fBgfwhere\fR\ 'u
\fBgfwhere\fR [\fIオプション\fR] \fIpath\fR...
.SH "DESCRIPTION"
.PP
指定したファイルについて、そのファイルのレプリカを保持する ファイルシステムノードのホスト名を表示します。
.SH "OPTIONS"
.PP
\fB\-a\fR
.RS 4
全てのレプリカに関する情報を表示します。 オプション
\fB\-dio\fR
を指定するのと等価です。
.RE
.PP
\fB\-d\fR
.RS 4
現在停止しているファイルシステムノード上に存在するレプリカの情報も表示します。
.RE
.PP
\fB\-F\fR
.RS 4
ホスト名の直後に、以下の情報もつけ加えて表示します。 論理的には削除されているが、まだ実体が残っている可能性のあるレプリカの場合 「;世代番号」、 複製途中の不完全なレプリカの場合「?」、 停止中のファイルシステムノードの場合「\-」。
.RE
.PP
\fB\-h\fR \fIhost\fR
.RS 4
指定されたhostに複製が格納されているファイルについて複製情報を表示します。 複数回指定された場合は、指定された全てのホストに格納されているファイルについて複製情報が表示されます。 指定されるホスト数は最大3です。
.RE
.PP
\fB\-i\fR
.RS 4
複製処理途中で、不完全な状態のレプリカの情報も表示します。
.RE
.PP
\fB\-l\fR
.RS 4
以下のように、より長い形式で表示します。
.sp
一行に、ひとつのホストのみ表示して改行します。
.sp
\fB\-o\fR
オプションないし
\fB\-a\fR
オプションが 指定されている場合は、ホスト名の後にレプリカの世代番号も表示します。
.sp
\fB\-d\fR
オプションないし
\fB\-a\fR
オプションが 指定されている場合は、その次に、そのホストが停止しているか否かを表示します。 停止している場合は「d」、稼働している場合は「\-」となります。
.sp
\fB\-i\fR
オプションないし
\fB\-a\fR
オプションが 指定されている場合は、その次に、そのレプリカが不完全な状態か否かを表示します。 複製途中で不完全な場合は「i」、完全な状態の場合は「\-」となります。
.sp
\fB\-o\fR
オプションないし
\fB\-a\fR
オプションが 指定されている場合は、その次に、そのレプリカが論理的に削除済か否かを表示します。 論理的に削除済の場合は「o」、削除されていない場合は「\-」となります。
.RE
.PP
\fB\-m\fR \fIN\fR
.RS 4
複製数がN以下でサイズが0以上のファイルについて複製情報を表示します。
.RE
.PP
\fB\-o\fR
.RS 4
論理的には削除されているが、物理的にはまだ存在している可能性があるレプリカの 情報も表示します。
.RE
.PP
\fB\-r, \-R\fR
.RS 4
ディレクトリに含まれるファイルのレプリカの所在を 再帰的に表示します。
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します。
.RE
