'\" t
.\"     Title: gfxattr
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 18 Aug 2008
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFXATTR" "1" "18 Aug 2008" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfxattr \- Gfarm ファイルシステムのファイルの拡張属性を操作する
.SH "SYNOPSIS"
.HP \w'\fBgfxattr\fR\ 'u
\fBgfxattr\fR [\-s | \-g | \-l | \-r] [\-x] [\-c | \-m] [\-f\ \fIxattrfile\fR] \fIfile\fR [\fIxattrname\fR]
.SH "DESCRIPTION"
.PP
指定したファイルの拡張属性およびXML拡張属性を操作します． 拡張属性は属性名と属性値からなり，いずれも任意の文字列です． XML拡張属性は属性値がXML型である拡張属性です． XML拡張属性は通常の拡張属性とは独立に扱われるため， 同一の属性名が利用可能です．
.PP
XML拡張属性を操作する場合，\-xオプションを指定します． XML拡張属性はgffindxmlattrコマンドを利用することにより XPath検索の対象となります．
.PP
拡張属性はGfarmの全てのファイル，ディレクトリに設定することができます． ファイルを削除すると，そのファイルに設定されていた拡張属性も全て削除されます．
.PP
\-s，\-g，\-l，\-rオプションは必ず何れかが指定される必要があります．
.SH "OPTIONS"
.PP
\fB\-s\fR
.RS 4
指定されたファイルに属性名xattrnameの拡張属性を設定します． 属性値は\-fオプションで指定されたxattrfileの内容となります． \-fオプションが指定されない場合は標準入力からの入力内容となります． \-c，\-mオプションが指定されない場合， すでに拡張属性が設定されていても上書きされます．
.RE
.PP
\fB\-g\fR
.RS 4
指定されたファイルの属性名xattrnameの拡張属性を表示します．
.RE
.PP
\fB\-l\fR
.RS 4
指定されたファイルの属性名の一覧を表示します．
.RE
.PP
\fB\-r\fR
.RS 4
指定されたファイルの属性名xattrnameの拡張属性を消去します．
.RE
.PP
\fB\-x\fR
.RS 4
XML拡張属性を処理します．
.RE
.PP
\fB\-c\fR
.RS 4
\-sオプションと共に用いられ，拡張属性を新規に設定します． このとき既に拡張属性が設定済みであればエラーとなります．
.RE
.PP
\fB\-m\fR
.RS 4
\-sオプションと共に用いられ，拡張属性の変更を行います． このとき拡張属性が設定されていなければエラーとなります．
.RE
.PP
\fB\-f\fR xattrfile
.RS 4
\-sオプションと共に用いると，指定されたファイルから拡張属性を読込みます． \-gオプションと共に用いると，指定されたファイルに拡張属性を書込みます．
.RE
.PP
\fB\-?\fR
.RS 4
引数オプションを表示します．
.RE
.SH "SEE ALSO"
.PP

\fBgffindxmlattr\fR(1)
