# $Id$

top_objdir = ../../../../..
top_srcdir = $(top_objdir)
srcdir = .

include $(top_srcdir)/makes/var.mk

htmldir=$(default_htmldir)/ja/ref/man3

DOCBOOK_DIR=$(top_srcdir)/doc/docbook/ja/ref/man3
include $(DOCBOOK_DIR)/Makefile.inc
HTMLSRC=$(DOCBOOK)

include $(top_srcdir)/makes/html.mk
