'\" t
.\"     Title: gfdf
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 14 Mar 2019
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFDF" "1" "14 Mar 2019" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfdf \- display disk free space of Gfarm file system
.SH "SYNOPSIS"
.HP \w'\fBgfdf\fR\ 'u
\fBgfdf\fR [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
\fBgfdf\fR
displays disk usage and free space of Gfarm file system\&.
.SH "OPTIONS"
.PP
\fB\-a\fR
.RS 4
Displays only summary information of the Gfarm file system\&.
.RE
.PP
\fB\-h\fR
.RS 4
Displays numbers in human readable format by adding a prefix multiplier symbol like "M" (mega)\&. Since this option uses powers of 1024, "M" means 1,048,576\&.
.RE
.PP
\fB\-H\fR
.RS 4
Displays numbers in human readable format by adding a prefix multiplier symbol like "M" (mega)\&. Since this option uses powers of 1000, "M" means 1,000,000\&.
.RE
.PP
\fB\-n\fR
.RS 4
Displays hostnames of available Gfarm file system nodes\&.
.RE
.PP
\fB\-r\fR
.RS 4
Sort output in the reverse order\&.
.RE
.PP
\fB\-S\fR
.RS 4
Sort output in the increasing order of the available disk capacity\&.
.RE
.PP
\fB\-P\fR \fIpath\fR
.RS 4
Specifies a path name to specify a metadata server instead of the root metadata server\&. Note that this option is not effective with the \-a option\&.
.RE
.PP
\fB\-D\fR \fIdomainname\fR
.RS 4
Specifies a domain name of filesystem nodes to list the status of disk free space\&.
.RE
.PP
\fB\-R\fR
.RS 4
Displays real disk spaces even if some Gfarm file system nodes are readonly\&. Please see also the following NOTES\&.
.RE
.PP
\fB\-?\fR
.RS 4
Displays a list of command options\&.
.RE
.SH "NOTES"
.PP
Filesystem nodes may be changed to a read\-only mode by the
\fBgfhost\fR
command\&. The read\-only filesystem nodes are internally treated as disk full not to create a new file\&. That is why
\fBgfdf\fR
shows these read\-only filesystem nodes have no available capacity\&. With the \-R option,
\fBgfdf\fR
shows the real disk usage\&. The \-a option is not affected by this behavior, which shows the real disk usage always\&.
.SH "SEE ALSO"
.PP
\fBgfhost\fR(1),
\fBgfarm2.conf\fR(5)
