'\" t
.\"     Title: gffindxmlattr
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 18 Aug 2008
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFFINDXMLATTR" "1" "18 Aug 2008" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gffindxmlattr \- Find XML extended attributes by XPath query
.SH "SYNOPSIS"
.HP \w'\fBgffindxmlattr\fR\ 'u
\fBgffindxmlattr\fR [\-d\ \fIdepth\fR] [\-F\ \fIdelim\fR] [\fIXPath\fR | [\-f\ \fIXPath\-file\fR]] \fIpath\fR
.SH "DESCRIPTION"
.PP
gffindxmlattr finds XML extended attributes by a specified XPath expression, and displays path names and the corresponding XML extended attribute names\&. When a file is specified, XML extended attributes associated to the file are searched if there is the read permission\&.
.PP
When a directory is specified, files or directories within the depth are recursively searched\&. When 0 is specified for the depth, the specified directory is searched\&. If the depth is not specified, all files and directories under the specified directory are searched\&. If the negative value is specified, gffindxmlattr returns error\&. Directories that do not have execute permission cannot be searched\&.
.PP
gffindxmlattr displays path names and the corresponding XML extended attribute separated by the delim\&.
.SH "OPTIONS"
.PP
\fB\-d\fR depth
.RS 4
specifies the depth to be searched recursively\&.
.RE
.PP
\fB\-F\fR delim
.RS 4
specifies a delimiter that separates the path name and the XML extended attribute name\&. By detault, the delimiter is TAB\&.
.RE
.PP
\fB\-f\fR XPath\-file
.RS 4
specifies a file that contains XPath expression\&.
.RE
.PP
\fB\-?\fR
.RS 4
displays usage\&.
.RE
.SH "SEE ALSO"
.PP

\fBgfxattr\fR(1)
