'\" t
.\"     Title: gfgetfacl
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 4 Feb 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFGETFACL" "1" "4 Feb 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfgetfacl \- display Gfarm file access control lists
.SH "SYNOPSIS"
.HP \w'\fBgfgetfacl\fR\ 'u
\fBgfgetfacl\fR [\fIoptions\fR] [\fIpath\fR...]
.SH "DESCRIPTION"
.PP
\fBgfgetfacl\fR
displays the file/directory name, owner, the group, and the Access Control List (ACL) about the specified files or directories in the Gfarm filesystem\&.
.SH "OPTIONS"
.PP
\fB\-?\fR
.RS 4
displays a list of command options\&.
.RE
.SH "NOTES"
.PP
If a Gfarm user/group is removed from a Gfarm filesystem, all of the ACL enties which have the same user/group name (qualifier) remain in the ACLs of files/directories\&.
.SH "SEE ALSO"
.PP

\fBgfsetfacl\fR(1)
