.Id $Id$
.TH gfgrep 1 "1 May 2002"
.SH NAME

gfgrep \- search a file for a pattern

.SH SYNOPSIS

.B gfrun gfarm:gfgrep
.B \-o
.I output-gfarm-URL
.I pattern
.I input-gfarm-URL
.br

.B gfrun gfarm:gfgrep
.B \-o
.I output-gfarm-URL
.B -e
.I pattern
.I input-gfarm-URL

.SH DESCRIPTION

\fBgfgrep\fP is a sample program of parallel applications executed by
gfrun(1) as well as an example to create a Gfarm file in the local
file view.

\fBgfgrep\fP searches a \fIpattern\fP from \fIinput-gfarm-URL\fP, and
outputs to \fIoutput-gfarm-URL\fP.

Every parallel application executed by gfrun(1) should interpret the
\-I and \-N options that show the rank and the size of the parallel
program, respectively, and call gfs_pio_set_local().

.SH OPTIONS

.TP
.B \-e
.I pattern
.br
is useful to protect patterns beginning with \-.
.TP
.B \-o
.I gfarm-URL
.br
specifies an output Gfarm file.
.TP
.B \-?
.br
displays a list of command options.
