'\" t
.\"     Title: gfgroup
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 20 Jan 2010
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFGROUP" "1" "20 Jan 2010" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfgroup \- Gfarm group maintenance command
.SH "SYNOPSIS"
.HP \w'\fBgfgroup\fR\ 'u
\fBgfgroup\fR [\-P\ \fIpath\fR] [\-l] [\fIgroup\fR...]
.HP \w'\fBgfgroup\fR\ 'u
\fBgfgroup\fR [\-P\ \fIpath\fR] \-c groupname [\fIuser\fR...]
.HP \w'\fBgfgroup\fR\ 'u
\fBgfgroup\fR [\-P\ \fIpath\fR] [\-a] [\-r] \-m groupname [\fIuser\fR...]
.HP \w'\fBgfgroup\fR\ 'u
\fBgfgroup\fR [\-P\ \fIpath\fR] \-d groupname
.SH "DESCRIPTION"
.PP

\fBgfgroup\fR
manages Gfarm groups in Gfarm file system\&. Default action displays all registered groups\&. When group names are specified, specified groups are displayed\&. Gfarm administrator can creates, modifies, and deletes a Gfarm group by \-c, \-m, and \-d options, respectively\&.
.SH "OPTIONS"
.PP
\fB\-P\fR \fIpath\fR
.RS 4
This option specifies a pathname or a Gfarm URL to identify a metadata server which will be accessed by this command\&. If not specified, "/" is used as the default value\&.
.RE
.PP
\fB\-l\fR
.RS 4
Displays group names and the group members\&.
.RE
.PP
\fB\-c\fR
.RS 4
Creates a group in Gfarm file system by specifying a group name and initial group members\&. This option can be used by Gfarm administrators\&.
.RE
.PP
\fB\-m\fR
.RS 4
Replaces all group members of the existing group\&. This option can be used by Gfarm administrators\&.
.RE
.PP
\fB\-a\fR
.RS 4
Adds group members to the existing group\&. This option is only available with
\fB\-m\fR
option\&. This option can be used by Gfarm administrators\&.
.RE
.PP
\fB\-r\fR
.RS 4
Removes group members from the existing group\&. This option is only available with
\fB\-m\fR
option\&. This option can be used by Gfarm administrators\&.
.RE
.PP
\fB\-d\fR
.RS 4
Deletes a group\&. This option can be used by Gfarm administrators\&.
.RE
.PP
\fB\-?\fR
.RS 4
Displays a list of command options\&.
.RE
.SH "SEE ALSO"
.PP

\fBgfuser\fR(1)
