.Id $Id$
.TH gfimport_text 1 "1 May 2002"
.SH NAME

gfimport_text \- divide and register a text file

.SH SYNOPSIS

.B gfimport_text
[
.I options
]
.I file

.SH DESCRIPTION

\fBgfimport_text\fP is a sample program for dividing a text file to
file fragments by the line and registering it to the Gfarm filesystem.

.SH OPTIONS

.TP
.B \-H
.I hostfile
.br
specifies a list of filesystem nodes.  The \fIhostfile\fP consists of
a hostname of a filesystem node in each line.  The file is almost
uniformly divided into file fragments.
.TP
.B \-f
.I fragment-file
.br
specifies a \fIfragment-file\fP that consists of a fragment size in
byte and a filesystem node separated by a white space in each line.
.TP
.B \-o
.I gfarm-URL
.br
specifies an output file.
.TP
.B \-?
.br
displays a list of command options.
