'\" t
.\"     Title: gfjournal
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 2 Jul 2012
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFJOURNAL" "1" "2 Jul 2012" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfjournal \- display status of a journal file
.SH "SYNOPSIS"
.HP \w'\fBgfjournal\fR\ 'u
\fBgfjournal\fR [\fIoptions\fR] \fIjournal\-file\fR
.SH "DESCRIPTION"
.PP

\fBgfjournal\fR
reads a journal file and outputs status report about the file to standard out\&. By default, it outputs the status summary of the journal file, like this:
.sp
.if n \{\
.RS 4
.\}
.nf
	records  seqnum(min/max)          record length(min/max/ave)
	     30           2/          31          24/    120/     37
.fi
.if n \{\
.RE
.\}
.PP
With \*(Aq\-l\*(Aq option,
\fBgfjournal\fR
also outputs all records in the journal file:
.sp
.if n \{\
.RS 4
.\}
.nf
	seqnum    operation        length  argument
	        2 BEGIN                 24
	        3 MDHOST_ADD            56 name=gfmd1\&.example\&.com
	        4 END                   24
	        5 BEGIN                 24
	        6 USER_ADD              68 username=gfarmadm
	        7 END                   24
	(snip)
	records  seqnum(min/max)          record length(min/max/ave)
	     30             2/        31          24/    120/     37
.fi
.if n \{\
.RE
.\}
.SH "OPTIONS"
.PP
\fB\-d\fR
.RS 4
Set log level to \*(Aqdebug\*(Aq\&.
.RE
.PP
\fB\-h\fR
.RS 4
Displays a list of command options\&.
.RE
.PP
\fB\-?\fR
.RS 4
Equivalent to
\fB\-h\fR\&.
.RE
.PP
\fB\-l\fR
.RS 4
List all records in the journal file\&.
.RE
.PP
\fB\-m\fR
.RS 4
Display the maximum sequence number only\&.
.RE
.PP
\fB\-r\fR
.RS 4
Do not display status summary or a header line for a list of records\&. This option is effective only when it is specified with
\fB\-l\fR
option\&.
.RE
.PP
\fB\-v\fR
.RS 4
Prints verbose messages\&.
.RE
