.Id $Id$
.TH gfkey 1 "1 May 2002"
.SH NAME

gfkey \- management of gfsd session keys

.SH SYNOPSIS

.B gfkey
[
.I options
]

.SH DESCRIPTION

\fBgfkey\fP manages the session key file
.B $HOME/.gfarm_shared_key
that is used for user authentication in a trusted environment when
connecting to gfsd.

When the home directory is shared among filesystem nodes, it is not
necessary to use this command.  If not, it is necessary to distribute
a session key to every filesystem node in advance that is created with
the -c or -f option.

.SH OPTIONS

.TP
.B \-c
.br
creates a new session key when there is no valid session key.  If
a valid session key already exists, no operation is performed.
.TP
.B \-f
.br
forces to create a new session key even if a valid session key already
exists.
.TP
.B \-l
.br
displays the current key.
.TP
.B \-e
.br
displays the expiration date of the current key.
.TP
.B \-?
.br
displays a list of command options.

.SH FILES

.TP
.SB "$HOME/.gfarm_shared_key"

a file for a session key
