'\" t
.\"     Title: gfperf-parallel-read
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 19 May 2012
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFPERF\-PARALLEL\-RE" "1" "19 May 2012" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfperf-parallel-read \- Gfarm measure file read performance
.SH "SYNOPSIS"
.HP \w'\fBgfperf\-parallel\-read\fR\ 'u
\fBgfperf\-parallel\-read\fR [\-t,\ \-\-testdir\ \fItest\ directory\fR] [\-m,\ \-\-gfarm2fs\ \fIgfarm2fs\ mount\ point\fR] [\-l,\ \-\-filesize\ \fIfile\ size\fR] [\-b,\ \-\-bufsize\ \fIbuffer\ size\fR] [\-r,\ \-\-random\ \fIrandom\fR] [\-g,\ \-\-gfsd\ \fIgfsd\ name\fR] [\-k,\ \-\-timeout\ \fItimeout\ seconds\fR] [\-n,\ \-\-name\ \fIgroup\ name\fR] [\-w,\ \-\-wait\ \fIstart\ time\fR]
.SH "DESCRIPTION"
.PP
This command mesures file read performance of specified size of file in
\fItest directory\fR\&. The test file is automatically created and not removed to be reused again\&.
.PP
This command is expected to be called by gfperf\&.rb in parallel\&.
.SH "OPTIONS"
.PP
\fB\-t, \-\-testdir\fR \fItest directory\fR
.RS 4
Test file is created in
\fItest directory\fR\&. Specify only gfarm url (that begins with gfarm:///) \&. The default is gfarm:///tmp \&.
.RE
.PP
\fB\-m, \-\-gfarm2fs\fR \fIgfarm2fs mount point\fR
.RS 4
Specify gfarm2fs mount point\&.
.RE
.PP
\fB\-l, \-\-filesize\fR \fIfile size\fR
.RS 4
File size to be created\&. The default is 1M\&. (1G=2^20)
.RE
.PP
\fB\-b, \-\-bufsize\fR \fIbuffer size\fR
.RS 4
Buffer size to read test file\&. The default is 4K\&. (1K=2^10)
.RE
.PP
\fB\-r, \-\-random\fR \fIrandom\fR
.RS 4
Only if this option is specified, Reads test file randomly\&. Option parameter is free\&. If this option is omitted, this command reads test file sequentially\&.
.RE
.PP
\fB\-g, \-\-gfsd\fR \fIgfsd name\fR
.RS 4
Specify gfsd name on which test file is created\&. If this option is omitted, gfmd determines automatically\&.
.RE
.PP
\fB\-k, \-\-timeout\fR \fItimeout seconds\fR
.RS 4
Maximum read time in seconds\&. This comannd measures how much data to be read in this seconds\&.
.RE
.PP
\fB\-n, \-\-name\fR \fIgroup name\fR
.RS 4
Group name in parallel execution\&.
.RE
.PP
\fB\-w, \-\-wait\fR \fIstart time\fR
.RS 4
Start time specified by gfperf\&.rb\&. This command waits until start time\&. Start time is written in UTC (YYYY\-MM\-DDThh:mm:ssZ) and must be in 10 seconds from current time\&.
.RE
