'\" t
.\"     Title: gfperf-autoreplica
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 19 May 2012
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFPERF\-AUTOREPLICA" "1" "19 May 2012" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfperf-autoreplica \- Gfarm measure autoreplica performance
.SH "SYNOPSIS"
.HP \w'\fBgfperf\-autoreplica\fR\ 'u
\fBgfperf\-autoreplica\fR [\-t,\ \-\-testdir\ \fItest\ directory\fR] [\-m,\ \-\-gfarm2fs\ \fIgfarm2fs\ mount\ point\fR] [\-l,\ \-\-filesize\ \fIfile\ size\fR] [\-f,\ \-\-number\ \fInumber\ of\ files\fR] [\-r,\ \-\-replica\ \fInumber\ of\ replica\fR] [\-s,\ \-\-stop\ \fIwait\ time\fR]
.SH "DESCRIPTION"
.PP
This command measures file creation performance in auto replication by gfmd\&. This command creates specified number of files in specified size\&. Between creation of files per second is performance of auto replica\&.
.PP
All test files are created in
\fItest directory\fR, and automatically removed on success\&.
.SH "OPTIONS"
.PP
\fB\-t, \-\-testdir\fR \fItest directory\fR
.RS 4
Test files are created in this directory\&. Specify gfarm url (that begins with gfarm:///)\&. The default is \*(Aqgfarm:///tmp\*(Aq\&.
.RE
.PP
\fB\-m, \-\-gfarm2fs\fR \fIgfarm2fs mount point\fR
.RS 4
Specify gfarm2fs mount point\&.
.RE
.PP
\fB\-l, \-\-filesize\fR \fIfile size\fR
.RS 4
File size to be created\&. The default is 1G\&. (1G = 2^30)
.RE
.PP
\fB\-f, \-\-number\fR \fInumber of files\fR
.RS 4
Number of files to be created\&. The default is 10\&.
.RE
.PP
\fB\-r, \-\-replica\fR \fInumber of replica\fR
.RS 4
Number of replica that is automatically replicated by gfmd\&. The default is 1\&.
.RE
.PP
\fB\-s, \-\-stop\fR \fIwait time\fR
.RS 4
Wait time for file replication in seconds\&. The default is 60 seconds\&.
.RE
