'\" t
.\"     Title: gfperf-copy
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 19 May 2012
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFPERF\-COPY" "1" "19 May 2012" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfperf-copy \- Gfarm measure file copy performance
.SH "SYNOPSIS"
.HP \w'\fBgfperf\-copy\fR\ 'u
\fBgfperf\-copy\fR \-s,\ \-\-src\ \fIsource\ url\fR \-d,\ \-\-dst\ \fIdestination\ url\fR [\-l,\ \-\-filesize\ \fIfile\ size\fR] [\-b,\ \-\-busize\ \fIbuffer\ size\fR] [\-g,\ \-\-gfsd\ \fIgfsd\ name\fR] [\-m,\ \-\-gfarm2fs\ \fIgfarm2fs\ mount\ point\fR]
.SH "DESCRIPTION"
.PP
This command measures file copy performance from source directory to destination directory\&. One of source and destination url must be gfarm url (that begins with gfarm:///)\&. Other must be file url (that begins with file:///)\&.
.PP
Test file is automatically created but source file is not removed\&. When this command is executed on same parameters, source file is reused again\&.
.SH "OPTIONS"
.PP
\fB\-s, \-\-src\fR \fIsource url\fR
.RS 4
Test file is created automatically in source url\&. If
\fIsource url\fR
is gfarm url,
\fIdestination url\fR
must be file url\&.
.RE
.PP
\fB\-d, \-\-dst\fR \fIdestination url\fR
.RS 4
Test file is copied to
\fIdestination url\fR\&. If
\fIdestinatiln url\fR
is gfarm url,
\fIsource url\fR
must be file url\&.
.RE
.PP
\fB\-l, \-\-filesize\fR \fIfile size\fR
.RS 4
File size to be created\&. The default is 1M\&. (1M=2^20)
.RE
.PP
\fB\-b, \-\-bufsize\fR \fIbuffer size\fR
.RS 4
Copy buffer size\&. The default is 4K\&. (1K=2^10)
.RE
.PP
\fB\-g, \-\-gfsd\fR \fIgfsd name\fR
.RS 4
Target gfsd name\&. Test file is created or copied on this gfsd\&. If no gfsd is specified, gfmd determines automatically\&.
.RE
.PP
\fB\-m, \-\-gfarm2fs\fR \fIgfarm2fs mount point\fR
.RS 4
Specify gfarm2fs mount point\&. This mount point path is added to gfarm url\&.
.RE
