'\" t
.\"     Title: gfperf-replica
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 19 May 2012
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFPERF\-REPLICA" "1" "19 May 2012" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfperf-replica \- Gfarm measure file replicate performance
.SH "SYNOPSIS"
.HP \w'\fBgfperf\-replica\fR\ 'u
\fBgfperf\-replica\fR \-s,\ \-\-src\ \fIsource\ gfsd\ name\fR \-s,\ \-\-dst\ \fIdestinatiln\ gfsd\ name\fR [\-l,\ \-\-filesize\ \fIfile\ size\fR] [\-t,\ \-\-testdir\ \fItest\ directory\fR]
.SH "DESCRIPTION"
.PP
This command creates test file in
\fItest directory\fR
and measures replication performance\&.
.SH "OPTIONS"
.PP
\fB\-s, \-\-src\fR \fIsource gfsd name\fR
.RS 4
Specify source gfsd name\&.
.RE
.PP
\fB\-d, \-\-dst\fR \fIdestination gfsd name\fR
.RS 4
Specify destination gfsd name\&.
.RE
.PP
\fB\-l, \-\-filesize\fR \fIfile size\fR
.RS 4
File size to be created\&. The default is 1M\&. (1M=2^20)
.RE
.PP
\fB\-t, \-\-testdir\fR \fItest directory\fR
.RS 4
Test file is created in
\fItest directory\fR\&. Specify only gfarm url (that begins with gfarm:///) \&. The default is gfarm:///tmp \&.
.RE
