'\" t
.\"     Title: gfperf-metadata
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 19 May 2012
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFPERF\-METADATA" "1" "19 May 2012" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfperf-metadata \- Gfarm measure metadata performance
.SH "SYNOPSIS"
.HP \w'\fBgfperf\-metadata\fR\ 'u
\fBgfperf\-metadata\fR [\-n,\ \-\-number\ \fInumber\ of\ entries\fR] [\-t,\ \-\-testdir\ \fItest\ directory\fR] [\-u,\ \-\-unit\ \fIoutput\ unit\fR]
.SH "DESCRIPTION"
.PP
This command makes sepcified number of files and directories in
\fItest directory\fR\&. And measures performance of execution time\&.
.PP
The following points to measure\&.
.PP
create
.RS 4
Measuring gfs_pio_create() or creat() performance\&. The output is average of execute time of this function\&.
.RE
.PP
readdir
.RS 4
Measuring execution time from gfs_opendir_caching() and gfs_readdir() to gfs_closedir()\&. In posix filesystem, measuring execution time from opendir() and readdir() to closedir()\&. The output is the time divided by
\fInumber of entries\fR\&.
.RE
.PP
readdir+stat
.RS 4
Measuring time of gfs_lstat_cached() or lstat() added to mentioned above in readdir\&. The output is the time divided by
\fInumber of entries\fR\&.
.RE
.PP
unlink
.RS 4
Measuring gfs_unlink() or unlink() performance\&. The output is average of execute time of this function\&.
.RE
.PP
mkdir
.RS 4
Measuring gfs_mkdir() or mkdir() performance\&. The output is average of execute time of this function\&.
.RE
.PP
stat
.RS 4
Measuring gfs_lstat() or lstat() performance\&. The output is average of execute time of this function\&.
.RE
.PP
chmod
.RS 4
Measuring gfs_chmod() or chmod() performance\&. The output is average of execute time of this function\&.
.RE
.PP
utimes
.RS 4
Measuring gfs_utimes() or utimes() performance\&. The output is average of execute time of this function\&.
.RE
.PP
rename
.RS 4
Measuring gfs_rename() or rename() performance\&. The output is average of execute time of this function\&.
.RE
.PP
symlink
.RS 4
Measuring gfs_symlink() or symlink() performance\&. The output is average of execute time of this function\&.
.RE
.PP
readlink
.RS 4
Measuring gfs_readlink() or readlink() performance\&. The output is average of execute time of this function\&.
.RE
.PP
setxattr
.RS 4
Measuring gfs_setattr() or setxattr() performance\&. The output is average of execute time of this function\&.
.RE
.PP
getxattr
.RS 4
Measuring gfs_getattr() or getxattr() performance\&. The output is average of execute time of this function\&.
.RE
.PP
removexattr
.RS 4
Measuring gfs_removeattr() or removexattr() performance\&. The output is average of execute time of this function\&.
.RE
.PP
rmdir
.RS 4
Measuring gfs_removedir() or removedir() performance\&. The output is average of execute time of this function\&.
.RE
.SH "OPTIONS"
.PP
\fB\-n, \-\-number\fR \fInumber of entries\fR
.RS 4
Creating number of files or directories to measure\&. The default is 250\&.
.RE
.PP
\fB\-t, \-\-testdir\fR \fItest directory\fR
.RS 4
Files and directories are created in
\fItest directory\fR\&. If gfarm url (that begins with gfarm:///) is specified, measured by gfarm functions\&. If file url (that begins with file:///) is specified, measured by posix functions\&. The default is gfarm:///tmp \&.
.RE
.PP
\fB\-u, \-\-uinit\fR \fIoutput unit\fR
.RS 4
Specify ops (operations per second) or usec (micro second)\&. The default is ops\&.
.RE
