'\" t
.\"     Title: gfperf-tree
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 19 May 2012
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFPERF\-TREE" "1" "19 May 2012" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfperf-tree \- Gfarm measure directory tree performance
.SH "SYNOPSIS"
.HP \w'\fBgfperf\-tree\fR\ 'u
\fBgfperf\-tree\fR [\-t,\ \-\-testdir\ \fItest\ directory\fR] [\-w,\ \-\-width\ \fInumber\ of\ directories\fR] [\-d,\ \-\-depth\ \fIdepth\ of\ directories\fR] [\-u,\ \-\-unit\ \fIoutput\ unit\fR]
.SH "DESCRIPTION"
.PP
This command creates a directory tree in
\fItest directory\fR\&. And measures performance creating directory tree and removing it\&. The created directory tree has
\fInumber of directories\fR
in each subdirectories\&. Total depth of the tree is
\fI depth of directories\fR
.PP
Output unit is ops (operation per second) or usec (micro second)\&.
.SH "OPTIONS"
.PP
\fB\-t, \-\-testdir\fR \fItest directory\fR
.RS 4
Directory tree is created in
\fItest directory\fR\&. If gfarm url (that begins with gfarm:///) is specified, measured by gfarm functions\&. If file url (that begins with file:///) is specified, measured by posix functions\&. The default is gfarm:///tmp \&.
.RE
.PP
\fB\-w, \-\-width\fR \fInumber of directories\fR
.RS 4
Specify number of directories in each subdirectories\&.
.RE
.PP
\fB\-d, \-\-depth\fR \fIdepth of directories\fR
.RS 4
Total depth of directory tree\&.
.RE
.PP
\fB\-u, \-\-uinit\fR \fIoutput unit\fR
.RS 4
Specify ops (operations per second) or usec (micro second)\&. The default is ops\&.
.RE
