.Id $Id$
.TH gfps 1 "1 May 2002"
.SH NAME

gfps \- report process status

.SH SYNOPSIS

.B gfps
[
.B \-al
]
[
.I job ID ...
]

.SH DESCRIPTION

\fBgfps\fP prints information about processes specified by the
arguments.  If the argments is missing, all processes that have the
same effective user ID.

.SH OPTIONS

.TP
.B \-a
.br
lists information about all jobs.
.TP
.B \-l
.br
displays with a long format.
.TP
.B \-?
.br
displays a list of command options.


