'\" t
.\"     Title: gfquotacheck
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 25 Aug 2015
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFQUOTACHECK" "1" "25 Aug 2015" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfquotacheck \- rebuild a table of file usage
.SH "SYNOPSIS"
.HP \w'\fBgfquotacheck\fR\ 'u
\fBgfquotacheck\fR [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
\fBgfquotacheck\fR
rebuilds a table of the current file usage for users and groups\&.
.PP
This command can be executed by an administrator in the gfarmadm group\&.
.SH "OPTIONS"
.PP
\fB\-P NAME\fR
.RS 4
Specifies a path name to specify a metadata server instead of the root metadata server\&.
.RE
.PP
\fB\-?\fR
.RS 4
Displays a list of command options\&.
.RE
.SH "SEE ALSO"
.PP
\fBgfedquota\fR(1),
\fBgfquota\fR(1),
\fBgfusage\fR(1)
