.Id $Id$
.TH gfreg 1 "1 May 2002"
.SH NAME

gfreg \- register a Gfarm program or a Gfarm file fragment

.SH SYNOPSIS

.B gfreg
[
.B \-a
.I architecture
]
[
.B \-N
.I num-of-replicas
]
.I program
.I gfarm-URL
.br

.B gfreg
.B \-N
.I total-num-of-fragments
.B \-I
.I fragment-index
[
.B \-h
.I filesystem-node
]
.in +0.5i
.I localfile
.I gfarm-URL
.in

.SH DESCRIPTION

The first form copies and registers the program \fIprogram\fP as a
Gfarm file \fIgfarm-URL\fP in the Gfarm filesystem.  After this
registration, the \fIgfarm-URL\fP can be specified as a program name
of gfrun(1) and gfmpirun(1).  Without the \-a option, architecture of
the specified program is assumed to be the same architecture as the
client host on that gfreg(1) is executed, which is obtained by the
Gfarm metaserver.  The \-N option specifies the number of file
replicas.  When it is omitted, one file replica is created.  The
destination filesystem node is automatically selected among filesystem
nodes of the same architecture.

The second form registers \fIlocalfile\fP as a file fragment of a
Gfarm file.  The total number of fragments and the fragment index
are specified by the \-N option and the \-I option, respectively.
By default, the destination filesystem node is the client host on the
gfreg(1) is executed, although which is changed by the -h option.
