'\" t
.\"     Title: gfrmdir
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 15 May 2008
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFRMDIR" "1" "15 May 2008" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfrmdir \- remove Gfarm directories
.SH "SYNOPSIS"
.HP \w'\fBgfrmdir\fR\ 'u
\fBgfrmdir\fR \fIpath\fR...
.SH "DESCRIPTION"
.PP
\fBgfrmdir\fR
removes directories specified in the arguments\&.
.SH "OPTIONS"
.PP
\fB\-?\fR
.RS 4
displays a list of command options\&.
.RE
.SH "SEE ALSO"
.PP

\fBgfmkdir\fR(1)
