'\" t
.\"     Title: gfsched
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 28 Dec 2010
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFSCHED" "1" "28 Dec 2010" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfsched \- schedule and display available file system nodes
.SH "SYNOPSIS"
.HP \w'\fBgfsched\fR\ 'u
\fBgfsched\fR \-f\ \fIgfarm\-URL\fR [\-D\ \fIdomain\-name\fR] [\-n\ \fInumber\fR] [\-LMclw]
.HP \w'\fBgfsched\fR\ 'u
\fBgfsched\fR [\-P\ \fIgfarm\-URL\fR] [\-D\ \fIdomain\-name\fR] [\-n\ \fInumber\fR] [\-LMlw]
.SH "DESCRIPTION"
.PP
The
\fBgfsched\fR
command with the
\fB\-f\fR
\fIgfarm\-URL\fR
option displays available file system nodes which have a file replica of the specified gfarm\-URL\&.
.PP
When the
\fB\-f\fR
\fIgfarm\-URL\fR
option is not specified, the
\fBgfsched\fR
command just displays available file system nodes\&. In this case, you can specify a metadata server by the
\fB\-P\fR
\fIgfarm\-URL\fR
option, if necessary\&.
.SH "OPTIONS"
.PP
\fB\-D\fR \fIdomain\-name\fR
.RS 4
Limits file system node by specifying a domain name or a hostname\&.
.RE
.PP
\fB\-c\fR
.RS 4
Displays scheduling information for a file creation, if the file specified by
\fB\-f\fR
doesn\*(Aqt exist\&.
.sp
Currently, this option creates the specified file\&. But please note that this behavior may be changed in future\&.
.RE
.PP
\fB\-L\fR
.RS 4
Suppresses authentication check\&. Without this option, the scheduler checks whether the user will be successfully authenticated with the hosts or not\&. This option omits the check to make scheduling faster, but that creates a risk that hosts which fail authentication with the user may be scheduled\&.
.RE
.PP
\fB\-M\fR
.RS 4
Suppresses client\-side scheduling and only performs metadata\-server\-side scheduling\&. This option makes scheduling faster, but also creates a risk that hosts which is network\-unreachable or fails authentication with the user may be scheduled\&.
.RE
.PP
\fB\-P\fR \fIgfarm\-URL\fR
.RS 4
Specifies a
\fIgfarm\-URL\fR
or a pathname to identify a metadata server which is used for the scheduling\&. This option conflicts with the
\fB\-f\fR
option\&.
.RE
.PP
\fB\-f\fR \fIgfarm\-URL\fR
.RS 4
The
\fBgfsched\fR
command schedules file system nodes which have a replica of a file specified by this option\&. This option conflicts with the
\fB\-P\fR
option\&.
.RE
.PP
\fB\-l\fR
.RS 4
Long format\&. This option displays port numbers as well as hostnames\&. Note that the display format of this option may be changed in future\&.
.RE
.PP
\fB\-n\fR \fInumber\fR
.RS 4
Displays specified number of file system nodes at most\&. If this option is not specified, it displays all available nodes\&.
.RE
.PP
\fB\-w\fR
.RS 4
Schedules with write\-mode\&. When this option is specified, file system nodes which don\*(Aqt have enough free space won\*(Aqt be displayed\&.
.sp
When both this option and the
\fB\-f\fR
are specified, and if the file is already opened by an existing process with write\-mode, the
\fBgfsched\fR
command only displays one file system node which is assigned for writing to the file\&.
.RE
.PP
\fB\-?\fR
.RS 4
Displays a list of command options\&.
.RE
.SH "EXAMPLES"
.PP
The following is an example to inquire file system nodes that the metadata server thinks they are currently working\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ gfsched \-M
.fi
.if n \{\
.RE
.\}
