.Id $Id$
.TH gfsched 1 "1 May 2002"
.SH NAME

gfsched \- create a host file using file-affinity scheduling

.SH SYNOPSIS

.B gfsched
[
.B \-I
.I fragment-index
]
.I gfarm-URL
[
.I output-hostfile
]
.in

.SH DESCRIPTION

\fBgfsched\fP creates a host file using the file-affinity scheduing of
\fIgfarm-URL\fP.  When \fIoutput-hostfile\fP is omitted, \fBgfsched\fP
displays to the standard output.

.SH OPTIONS

.TP
.B \-I
.I fragment-index
.br
specifies the fragment index to be scheduled.  If the \fIgfarm-URL\fP
is an executable file, an architecture name, for example,
sparc-sun-solaris, can be used to specify the executable architecture
to be scheduled.
.TP
.B \-?
.br
displays a list of command options.
