'\" t
.\"     Title: gfsetfacl
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 4 Feb 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFSETFACL" "1" "4 Feb 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfsetfacl \- set Gfarm file access control lists
.SH "SYNOPSIS"
.HP \w'\fBgfsetfacl\fR\ 'u
\fBgfsetfacl\fR [\fIoptions\fR] [\fIpath\fR...]
.SH "DESCRIPTION"
.PP
\fBgfsetfacl\fR
changes the Access Control List (ACL) of files or directories in the Gfarm filesystem\&.
.SH "OPTIONS"
.PP
\fB\-b\fR
.RS 4
removes all extended ACL entries\&. (The base ACL entries of the owner, group and others are not removed\&.)
.RE
.PP
\fB\-k\fR
.RS 4
removes the only Default ACL\&.
.RE
.PP
\fB\-n\fR
.RS 4
do not recalculate the mask entry of the ACL\&. The default behavior of gfsetfacl is to recalculate the mask entry, if a mask entry is not explicitly given\&.
.RE
.PP
\fB\-r\fR
.RS 4
always recalculate the mask entry of the ACL\&. (Even if a mask entry is explicitly given\&.) (See the \-n option\&.)
.RE
.PP
\fB\-t\fR
.RS 4
is test mode\&. Instead of changing the ACL of any files or directories, the ACL text of input text and the new ACL text are displayed\&.
.RE
.PP
\fB\-m\fR \fIacl_spec\fR
.RS 4
This option specifies the ACL entries text to add/replace the ACL entries of a Gfarm files or directories\&. Multiple ACL entries are separated by comma characters (`,\*(Aq)\&.
.RE
.PP
\fB\-M\fR \fIacl_file\fR
.RS 4
This option specifies the file or standard input (`\-\*(Aq) to add/replace the ACL entries of a Gfarm files or directories\&. This input of ACL file accepts the output of gfgetfacl command\&.
.RE
.PP
\fB\-?\fR
.RS 4
displays a list of command options\&.
.RE
.SH "ACL ENTRIES"
.PP
The gfsetfacl command recognizes the following ACL entry formats\&. The perms field is a combination of characters that indicate the permissions: read (r), write (w), execute (x)\&. A Default ACL entry has a d[efault:] prefix\&.
.PP
[d[efault:]u[ser]::perms
.RS 4
Permissions of owner\&.
.RE
.PP
[d[efault:]u[ser]:username:perms
.RS 4
Permissions of a named user\&.
.RE
.PP
[d[efault:]g[roup]::perms
.RS 4
Permissions of a file group\&.
.RE
.PP
[d[efault:]g[roup]:groupname:perms
.RS 4
Permissions of a named group\&.
.RE
.PP
[d[efault:]m[ask]::perms
.RS 4
mask of effective rights
.RE
.PP
[d[efault:]o[ther]::perms
.RS 4
Permissions of others\&.
.RE
.SH "EXAMPLES"
.PP
Granting read access to a named user
.RS 4
gfsetfalc \-m u:testuser:r filename
.RE
.PP
Replacing the ACL of filename2 by filename1
.RS 4
gfgetfacl filename1 | gfsetfacl \-b \-M \- filename2
.RE
.PP
ACL text of long form
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
# comment
user::rw\-
user:testuser:rw\-       #effective:r\-\-
group::r\-\-
group:testgroup:rw\-     #effective:r\-\-
mask::r\-\-
other::r\-\-
default:user::rwx
default:group::r\-x
default:other::r\-x
.fi
.if n \{\
.RE
.\}
.RE
.PP
ACL text of short form
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
u::rw,u:user1:rw,g::r,g:group1:rw,m::r,o::r,d:u::rwx,d:g::rx,d:o::rx
.fi
.if n \{\
.RE
.\}
.RE
.SH "SEE ALSO"
.PP

\fBgfgetfacl\fR(1)
