'\" t
.\"     Title: gfservice-agent
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 6 Jun 2013
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFSERVICE\-AGENT" "1" "6 Jun 2013" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfservice-agent \- agent of \fBgfservice\fR
.SH "SYNOPSIS"
.HP \w'\fBgfservice\-agent\fR\ 'u
\fBgfservice\-agent\fR [\fIoptions\fR] host\-id sub\-command [\fIargument\ \&.\&.\&.\fR]
.SH "DESCRIPTION"
.PP

\fBgfservice\-agent\fR
is an agent of
\fBgfservice\fR\&. It must be installed on all hosts you want to operate using
\fBgfservice\fR\&. Unlike
\fBgfservice\fR, it doesn\*(Aqt read a configuration file\&.
.PP

\fBgfservice\-agent\fR
is not designed to be executed directly by an user\&. In daily use, it is executed only by
\fBgfservice\fR
via SSH and Sudo\&.
.PP
Host\-id argument is the same as that of
\fBgfservice\fR, but
\fBgfservice\-agent\fR
uses host\-id for recognizing type of host ("gfmd", "gfsd" or "client") and debug messages only\&.
.PP
Sub\-command names of
\fBgfservice\-agent\fR
are similar to those of
\fBgfservice\fR, but their arguments are different\&. For example,
\fB"unmount"\fR
sub\-command of
\fBgfservice\-agent\fR
takes
\fI"directory=\fR\fI\fIdirectory\fR\fR\fI"\fR
argument:
.sp
.if n \{\
.RS 4
.\}
.nf
	gfservice\-agent client3 unmount directory=/somewhere
.fi
.if n \{\
.RE
.\}
.PP
while
\fB"unmount"\fR
sub\-command of
\fBgfservice\fR
takes
\fI"directory"\fR
argument:
.sp
.if n \{\
.RS 4
.\}
.nf
	gfservice unmount client3 /somewhere
.fi
.if n \{\
.RE
.\}
.PP
Almost all arguments of
\fBgfservice\-agent\fR
have "key=value" form\&. When two or more arguments are given,
\fBgfservice\-agent\fR
doesn\*(Aqt care about the order of arguments\&.
\fBgfservice\-agent\fR
ignores arguments with unknown keys\&.
.SH "OPTIONS"
.PP
\fB\-d\fR
.RS 4
Print debug information\&.
.RE
.SH "SUB-COMMANDS"
.PP

\fBgfservice\-agent\fR
currently recognizes the following sub\-commands\&.
.PP
\fBget\-config\-gfarm\-param\fR \fIparam\fR=\fIname\fR \fIconfig\-gfarm\-options\fR=\fIoptions\fR
.RS 4
Execute
\fBconfig\-gfarm \-T\fR
command and output a value of the parameter
\fIname\fR
to standard out\&. If the "\fIparam\fR=\fIname\fR" argument is not specified, it outputs entire
\fBconfig\-gfarm \-T\fR
results\&.
.RE
.PP
\fBget\-config\-gfsd\-param\fR \fIparam\fR=\fIname\fR \fIconfig\-gfsd\-options\fR=\fIoptions\fR
.RS 4
Execute
\fBconfig\-gfsd \-T\fR
command and output a value of the parameter
\fIname\fR
to standard out\&. If the "\fIparam\fR=\fIname\fR" argument is not specified, it outputs entire
\fBconfig\-gfsd \-T\fR
results\&.
.RE
.PP
\fBbackend\-db\-status\fR \fIconfig\-gfarm\-options\fR=\fIoptions\fR
.RS 4
Exit with an exit code 0, if a backend database is currently running\&. Otherwise exits with 1\&.
.RE
.PP
\fBgfmd\-status\fR \fIconfig\-gfarm\-options\fR=\fIoptions\fR
.RS 4
Exit with an exit code 0, if gfmd is currently running\&. Otherwise exits with 1\&.
.RE
.PP
\fBgfsd\-status\fR \fIconfig\-gfsd\-options\fR=\fIoptions\fR
.RS 4
Exit with an exit code 0, if gfsd is currently running\&. Otherwise exits with 1\&.
.RE
.PP
\fBstart\-backend\-db\fR \fIconfig\-gfarm\-options\fR=\fIoptions\fR \fItimeout\fR=\fItime\fR
.RS 4
Start a backend database if it is not running currently\&.
.RE
.PP
\fBstart\-gfmd\fR \fIconfig\-gfarm\-options\fR=\fIoptions\fR \fItimeout\fR=\fItime\fR
.RS 4
Start gfmd if it is not running currently\&.
.RE
.PP
\fBstart\-gfsd\fR \fIconfig\-gfsd\-options\fR=\fIoptions\fR \fItimeout\fR=\fItime\fR
.RS 4
Start gfsd if it is not running currently\&.
.RE
.PP
\fBconfig\-gfarm\fR \fIconfig\-gfarm\-options\fR=\fIoptions\fR
.RS 4
Execute
\fBconfig\-gfarm\fR
command\&.
.RE
.PP
\fBconfig\-gfarm\-master\fR \fIconfig\-gfarm\-options\fR=\fIoptions\fR
.RS 4
Execute
\fBconfig\-gfarm\fR
\fI\-r\fR
command\&.
.RE
.PP
\fBconfig\-gfsd\fR \fIconfig\-gfsd\-options\fR=\fIoptions\fR
.RS 4
Execute
\fBconfig\-gfsd\fR
command\&.
.RE
.PP
\fBunconfig\-gfarm\fR \fIconfig\-gfarm\-options\fR=\fIoptions\fR
.RS 4
Execute
\fBstop\-gfarm\fR
sub\-command and then delete all files and directories created by gfmd and a backend database\&.
.RE
.PP
\fBunconfig\-gfsd\fR \fIconfig\-gfsd\-options\fR=\fIoptions\fR
.RS 4
Execute
\fBstop\-gfsd\fR
sub\-command and then delete all files and directories created by gfsd\&.
.RE
.PP
\fBunconfig\-client\fR \fIconfig\-gfsd\-options\fR=\fIoptions\fR
.RS 4
Delete
gfarm2\&.conf
file\&.
.RE
.PP
\fBpromote\fR \fIconfig\-gfarm\-options\fR=\fIoptions\fR
.RS 4
Promote
\fBgfmd\fR
from a slave to a master\&.
.RE
.PP
\fBpromote\-gfmd\fR \fIconfig\-gfarm\-options\fR=\fIoptions\fR
.RS 4
An alias of
\fBpromote\fR
sub\-command\&.
.RE
.PP
\fBmount\fR \fIdirectory\fR=\fIdirectory\fR \fIoptions\fR=\fIoptions\fR
.RS 4
Mount a Gfarm2 filesystem on
\fIdirectory\fR\&.
.RE
.PP
\fBunmount\fR \fIdirectory\fR=\fIdirectory\fR
.RS 4
Unmount a Gfarm2 filesystem currently mounted on
\fIdirectory\fR\&.
.RE
.PP
\fBumount\fR \fIdirectory\fR=\fIdirectory\fR
.RS 4
An alias of
\fBunmount\fR
sub\-command\&.
.RE
.PP
\fBset\-gfmd\-conf\fR \fIdirective\fR=\fIname\fR \fIvalue\fR=\fIvalue\fR
.RS 4
Add
.sp
.if n \{\
.RS 4
.\}
.nf
	\fIdirective\fR \fIvalue\fR
.fi
.if n \{\
.RE
.\}
.sp
line to
gfmd\&.conf
file\&.
.RE
.PP
\fBset\-gfarm\-conf\fR \fIdirective\fR=\fIname\fR \fIvalue\fR=\fIvalue\fR
.RS 4
Add
.sp
.if n \{\
.RS 4
.\}
.nf
	\fIdirective\fR \fIvalue\fR
.fi
.if n \{\
.RE
.\}
.sp
line to
gfarm2\&.conf
file\&.
.RE
.PP
\fBset\-gfsd\-conf\fR \fIdirective\fR=\fIname\fR \fIvalue\fR=\fIvalue\fR
.RS 4
Add
.sp
.if n \{\
.RS 4
.\}
.nf
	\fIdirective\fR \fIvalue\fR
.fi
.if n \{\
.RE
.\}
.sp
line to
gfsd\&.conf
file\&.
.RE
.PP
\fBunset\-gfmd\-conf\fR \fIdirective\fR=\fIname\fR
.RS 4
Delete a
\fIdirective\fR
line in
gfmd\&.conf
file\&.
.RE
.PP
\fBunset\-gfarm\-conf\fR \fIdirective\fR=\fIname\fR
.RS 4
Delete a
\fIdirective\fR
line in
gfarm2\&.conf
file\&.
.RE
.PP
\fBunset\-gfsd\-conf\fR \fIdirective\fR=\fIname\fR
.RS 4
Delete a
\fIdirective\fR
line in
gfsd\&.conf
file\&.
.RE
.PP
\fBbackup\-backend\-db\fR
.RS 4
Backup a backend database and output the backup data to standard out\&.
.RE
.PP
\fBbackup\-gfmd\-conf\fR
.RS 4
Output
gfmd\&.conf
file to standard out\&.
.RE
.PP
\fBbackup\-gfarm\-conf\fR
.RS 4
Output
gfarm2\&.conf
file to standard out\&.
.RE
.PP
\fBbackup\-gfsd\-conf\fR
.RS 4
Output
gfsd\&.conf
file to standard out\&.
.RE
.PP
\fBbackup\-usermap\fR
.RS 4
Output
usermap
file to standard out\&.
.RE
.PP
\fBbackup\-shared\-key\fR
.RS 4
Output
$HOME/\&.gfarm_shared_key
file to standard out\&.
.RE
.PP
\fBrestore\-backend\-db\fR
.RS 4
Restore a backend database\&. The backup data are read from standard in\&.
.RE
.PP
\fBrestore\-gfmd\-conf\fR
.RS 4
Restore
gfmd\&.conf
file\&. The backup data are read from standard in\&.
.RE
.PP
\fBrestore\-gfarm\-conf\fR
.RS 4
Restore
gfarm2\&.conf
file\&. The backup data are read from standard in\&.
.RE
.PP
\fBrestore\-gfsd\-conf\fR
.RS 4
Restore
gfsd\&.conf
file\&. The backup data are read from standard in\&.
.RE
.PP
\fBrestore\-usermap\fR
.RS 4
Restore
usermap
file\&. The backup data are read from standard in\&.
.RE
.PP
\fBrestore\-shared\-key\fR
.RS 4
Restore
$HOME/\&.gfarm_shared_key
file\&. The backup data are read from standard in\&.
.RE
.PP
\fBgfcmd\fR \fIcmd\fR=\fIcommand\-name\fR \fIargs\fR="\fIcommand\-argument \&.\&.\&.\fR"
.RS 4
Execute a Gfarm command\&.
.RE
.PP
\fBgrid\-proxy\-init\fR \fIargs\fR="\fIcommand\-argument \&.\&.\&.\fR"
.RS 4
Execute
\fBgrid\-proxy\-init\fR
command\&.
.RE
