'\" t
.\"     Title: gfspoolpath
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 17 Oct 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFSPOOLPATH" "1" "17 Oct 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfspoolpath \- display a pathname on a filesystem node about a Gfarm file
.SH "SYNOPSIS"
.HP \w'\fBgfspoolpath\fR\ 'u
\fBgfspoolpath\fR [\fIpath\fR...]
.SH "DESCRIPTION"
.PP
This command displays a pathname of a concrete file on a filesystem node, which is corresponding to a Gfarm file specified in the command argument\&. The pathname is relative to the top directory of a spool directory of gfsd\&.
.SH "BUGS"
.PP
No error is reported, if the command argument refers a directory\&.
