'\" t
.\"     Title: gfstress.rb
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 7 Mar 2013
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFSTRESS\&.RB" "1" "7 Mar 2013" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfstress.rb \- Gfarm stress test
.SH "SYNOPSIS"
.HP \w'\fBgfstress\&.rb\fR\ 'u
\fBgfstress\&.rb\fR [\-t,\ \-\-testdir\ \fItest\ directory\fR] [\-m,\ \-\-gfarm2fs\ \fIgfarm2fs\ mount\ point\fR] [\-n,\ \-\-number\ \fInumber\ of\ pseudo\ users\fR] [\-T,\ \-\-timeout\ \fItimeout(seconds)\fR]
.SH "DESCRIPTION"
.PP
This comannd executes gfperf\-metadata, gfperf\-tree, gfperf\-read, gfperf\-write, gfperf\-replica in parallel to make gfarm system high load average\&. gfperf\-read, gfperf\-write, gfperf\-replica are executed for each gfsd servers\&.
.PP
This command runs until an error occured by default\&. If you need to stop, press Ctrl\-C or send TERM signal\&. If you want set timeout, \-T option is usable\&.
.PP
Number of pseudo users means multiplex set of gfperf\-metadata, gfperf\-tree, gfperf\-read, gfperf\-write, gfperf\-replica\&. Same as multiplex execution of this command\&.
.PP
If gfarm2fs mount point is specified, more gfperf\-metadata, gfperf\-tree, gfperf\-read, gfeprf\-write commands that use gfarm2fs are executed\&.
.SH "OPTIONS"
.PP
\fB\-t, \-\-testdir\fR \fItest_directory\fR
.RS 4
This directory is used for high load average test\&. The default is gfarm:///stress \&. All files and directories are removed at the end of testing\&.
.RE
.PP
\fB\-m, \-\-gfarm2fs\fR \fIgfarm2fs_mountpoint\fR
.RS 4
Specify gfarm2fs mount point
.RE
.PP
\fB\-n, \-\-number\fR \fInumber_of_pseudo_users\fR
.RS 4
Specify number of pseudo users\&.
.RE
.PP
\fB\-T, \-\-timeout\fR \fIseconds\fR
.RS 4
Specify timeout\&.
.RE
