'\" t
.\"     Title: gfusage
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 23 Mar 2011
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFUSAGE" "1" "23 Mar 2011" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfusage \- display the current usage
.SH "SYNOPSIS"
.HP \w'\fBgfusage\fR\ 'u
\fBgfusage\fR [options] [name]
.SH "DESCRIPTION"
.PP
\fBgfusage\fR
displays the current usage for users or groups\&. If
\fIname\fR
is specified, it displays only the specified user or group\&. With the \-g option, it displays the current usage for groups\&. The current usage is available for users or groups after building a table of the current usage by
\fBgfedquota\fR
and
\fBgfquotacheck\fR\&.
.SH "OPTIONS"
.PP
\fB\-g\fR
.RS 4
Displays the current usage for groups\&.
.RE
.PP
\fB\-h\fR
.RS 4
Displays numbers in human readable format by adding a prefix multiplier symbol like "M" (mega)\&. Since this option uses powers of 1024, "M" means 1,048,576\&.
.RE
.PP
\fB\-H\fR
.RS 4
Displays numbers in human readable format by adding a prefix multiplier symbol like "M" (mega)\&. Since this option uses powers of 1000, "M" means 1,000,000\&.
.RE
.PP
\fB\-?\fR
.RS 4
Displays a list of command options\&.
.RE
.SH "SEE ALSO"
.PP

\fBgfdf\fR(1),
\fBgfquota\fR(1)
