'\" t
.\"     Title: gfuser
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 20 Jan 2010
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFUSER" "1" "20 Jan 2010" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfuser \- Gfarm user maintenance command
.SH "SYNOPSIS"
.HP \w'\fBgfuser\fR\ 'u
\fBgfuser\fR [\-P\ \fIpath\fR] [\-l] [\fIuser\fR...]
.HP \w'\fBgfuser\fR\ 'u
\fBgfuser\fR [\-P\ \fIpath\fR] \-c username realname homedir gsi_dn
.HP \w'\fBgfuser\fR\ 'u
\fBgfuser\fR [\-P\ \fIpath\fR] \-m username realname homedir gsi_dn
.HP \w'\fBgfuser\fR\ 'u
\fBgfuser\fR [\-P\ \fIpath\fR] \-d username
.SH "DESCRIPTION"
.PP

\fBgfuser\fR
manages Gfarm global users in Gfarm file system\&. Default action displays all registered users\&. When user names are specified, specified users are displayed\&. Gfarm administrator can creates, modifies, and deletes a Gfarm user by \-c, \-m, and \-d options, respectively\&.
.SH "OPTIONS"
.PP
\fB\-P\fR \fIpath\fR
.RS 4
This option specifies a pathname or a Gfarm URL to identify a metadata server which will be accessed by this command\&. If not specified, "/" is used as the default value\&.
.RE
.PP
\fB\-l\fR
.RS 4
Displays verbose information of registered users\&.
.RE
.PP
\fB\-c\fR
.RS 4
Creates a user by specifying a global username in Gfarm file system, a real username, a home directory in Gfarm, and a Subject DN used in GSI\&. When the real username or the Subject DN includes spaces, it is needed to be quoted\&. This option can be used by Gfarm administrators\&.
.RE
.PP
\fB\-m\fR
.RS 4
Replaces a user information of the specified global user with specified real name, home directory and Subject DN\&. This option can be used by Gfarm administrators\&.
.RE
.PP
\fB\-d\fR
.RS 4
Deletes a registered user\&. This option can be used by Gfarm administrators\&.
.RE
.PP
\fB\-?\fR
.RS 4
Displays a list of command options\&.
.RE
.SH "SEE ALSO"
.PP

\fBgfgroup\fR(1)
