'\" t
.\"     Title: gfwhere
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 12 Mar 2016
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFWHERE" "1" "12 Mar 2016" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfwhere \- print replica locations
.SH "SYNOPSIS"
.HP \w'\fBgfwhere\fR\ 'u
\fBgfwhere\fR [\fIoptions\fR] \fIpath\fR...
.SH "DESCRIPTION"
.PP
The
\fBgfwhere\fR
command prints hostnames of filesystem nodes which hold replicas of the specified files\&.
.SH "OPTIONS"
.PP
\fB\-a\fR
.RS 4
Displays information of all replicas\&. This is similar to specifying the
\fB\-dio\fR
options\&.
.RE
.PP
\fB\-d\fR
.RS 4
Displays replicas on filesystem nodes which are currently down as well\&.
.RE
.PP
\fB\-F\fR
.RS 4
Displays the following indicators just after each hostname\&. If the replica has been logically removed, but may still remain phisically, ";" and the replica\*(Aqs generation number are displayed\&. If the replica is incomplete because it\*(Aqs in the midst of replication, "?" is displayed\&. If the host is currently down, "\-" is displayed\&.
.RE
.PP
\fB\-h\fR \fIhost\fR
.RS 4
Only displays files stored on the specified host\&. When the \-h option is specified multiple times, it displays files stored on all specified hosts\&. When the host A and host B are specified, it displays files stored on both host A and host B\&. The \-h option can be specified up to three times\&.
.RE
.PP
\fB\-i\fR
.RS 4
Displays incomplete replicas which are in the midst of replication\&.
.RE
.PP
\fB\-l\fR
.RS 4
Displays in long format as follows\&.
.sp
This displays one hostname in each line\&.
.sp
If
\fB\-o\fR
option or
\fB\-a\fR
option is specified, this displays the generation number of the replica after the hostname\&.
.sp
If
\fB\-d\fR
option or
\fB\-a\fR
option is specified, this displays an indicator which shows whether this host is down (d) or up (\-) at next column\&.
.sp
If
\fB\-i\fR
option or
\fB\-a\fR
option is specified, this displays an indicator which shows whether this replica is incomplete (i) or not (\-) at next column\&. In the former case, this replica is in the midst of replication\&.
.sp
If
\fB\-o\fR
option or
\fB\-a\fR
option is specified, this displays an indicator which shows whether this replica is obsolete (o) or not (\-) at next column\&. In the former case, this replica has been logicall removed\&.
.RE
.PP
\fB\-m\fR \fIN\fR
.RS 4
Only displays files having less than or equal to N replicas and having greater than 0 bytes\&.
.RE
.PP
\fB\-o\fR
.RS 4
Displays obsolete replicas which has been logically removed, but may still remain phisically\&.
.RE
.PP
\fB\-r, \-R\fR
.RS 4
Displays subdirectories recursively\&.
.RE
.PP
\fB\-?\fR
.RS 4
Displays a list of command options\&.
.RE
