'\" t
.\"     Title: gfxattr
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 18 Aug 2008
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFXATTR" "1" "18 Aug 2008" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfxattr \- Manipulate extended attributes in Gfarm file system
.SH "SYNOPSIS"
.HP \w'\fBgfxattr\fR\ 'u
\fBgfxattr\fR [\-s | \-g | \-l | \-r] [\-x] [\-c | \-m] [\-f\ \fIxattrfile\fR] \fIfile\fR [\fIxattrname\fR]
.SH "DESCRIPTION"
.PP
gfxattr manipulates extended attributes and XML extended attributes of a specified file\&. An extended attribute consists of an attribute name and an attribute value, which are arbitrary strings\&. An XML extended attribute is an extended attribute having an XML attribute value\&. Since XML extended attributes have a different name space from extended attributes, the same attribute name can be used\&.
.PP
When the \-x option is specified, XML extended attributes are manipulated\&. It is possible to search XML extended attributes by XPath query using gffindxmlattr command\&.
.PP
All files and directories in Gfarm file system can keep extended attributes\&. When removing a file or directory, the associated extended attributes are also removed\&.
.PP
Either \-s, \-g, \-l, or \-r option should be specified\&.
.SH "OPTIONS"
.PP
\fB\-s\fR
.RS 4
sets a new value with an extended attribute xattrname for a specified file\&. With the \-f option, the value can be specified by the file xattrfile instead of by the standard input\&. When neither \-c nor \-m option is specified, the extended attribute is overwritten if it is already set\&.
.RE
.PP
\fB\-g\fR
.RS 4
reads a value with an extended attribute xattrname for a specified file\&.
.RE
.PP
\fB\-l\fR
.RS 4
display a list of extended attributes for a specified file\&.
.RE
.PP
\fB\-r\fR
.RS 4
removes a extended attribute xattrname for a specified file\&.
.RE
.PP
\fB\-x\fR
.RS 4
manipulates XML extended attributes\&.
.RE
.PP
\fB\-c\fR
.RS 4
sets a new extended attribute if it is not set\&. This option is used with the \-s option\&.
.RE
.PP
\fB\-m\fR
.RS 4
modifies the extended attribute if there it is\&. This option is used with the \-s option\&.
.RE
.PP
\fB\-f\fR xattrfile
.RS 4
With the \-s option, reads an extended attribute from the specified xattrfile instead of from the standard input\&. With the \-g option, writes the extended attribute to the specified xattrfile instead of to the standard output\&.
.RE
.PP
\fB\-?\fR
.RS 4
displays usage\&.
.RE
.SH "SEE ALSO"
.PP

\fBgffindxmlattr\fR(1)
