# $Id$

top_objdir = ../..
top_srcdir = $(top_objdir)
srcdir = .

include $(top_srcdir)/makes/var.mk

MAN = digest.1 gfexport.1 gfgrep.1 gfimport_fixed.1 gfimport_text.1 \
	gfkey.1 gfmpirun.1 gfps.1 gfrcmd.1 gfreg.1 \
	gfrep.1 gfrm.1 gfrsh.1 gfrun.1 gfssh.1 gfwc.1 gfwhere.1
#	gfls.1 gfmkdir.1 gfrmdir.1

include $(top_srcdir)/makes/man.mk
