DOCBOOK = \
	digest.1 \
	gfexport.1 \
	gfgrep.1 \
	gfimport_fixed.1 \
	gfimport_text.1 \
	gfkey.1 \
	gfls.1 \
	gfmpirun_p4.1 \
	gfps.1 \
	gfrcmd.1 \
	gfreg.1 \
	gfrep.1 \
	gfrm.1 \
	gfrun.1 \
	gfsched.1 \
	gfwc.1 \
	gfwhere.1
