DOCBOOK = \
	gfchgrp.1 \
	gfchmod.1 \
	gfchown.1 \
	gfdf.1 \
	gffindxmlattr.1 \
	gfgroup.1 \
	gfhost.1 \
	gfkey.1 \
	gfln.1 \
	gfls.1 \
	gfmkdir.1 \
	gfmv.1 \
	gfrep.1 \
	gfrmdir.1 \
	gfstat.1 \
	gfstatus.1 \
	gfuser.1 \
	gfwhere.1 \
	gfwhoami.1 \
	gfxattr.1

#	gfarm_agent.1 \
#	gfcd.1 \
#	gfexec.1 \
#	gfexport.1 \
#	gfgrep.1 \
#	gfimport_fixed.1 \
#	gfimport_text.1 \
#	gfmpirun_p4.1 \
#	gfps.1 \
#	gfpwd.1 \
#	gfrcmd.1 \
#	gfreg.1 \
#	gfrm.1 \
#	gfront.1 \
#	gfrun.1 \
#	gfsched.1 \
#	gfsetdir.1 \
#	gfusage.1 \
#	gfwc.1 \
