.TH gfarm_stringlist_length 3 "1 May 2002"

.SH NAME

gfarm_stringlist_length \- stringlist の文字列数を返す

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B int
.br
.BI "gfarm_stringlist_length(gfarm_stringlist *" listp );

.SH DESCRIPTION

.I listp
の表す文字列配列の配列要素数を返します。

.SH "RETURN VALUES"

文字列の数を返します。

.SH "SEE ALSO"
.BR GFARM_STRINGLIST_ELEM (3),
.BR GFARM_STRINGLIST_STRARRAY (3) ,
.BR gfarm_stringlist_add (3),
.BR gfarm_stringlist_cat (3),
.BR gfarm_stringlist_elem (3),
.BR gfarm_stringlist_free (3),
.BR gfarm_stringlist_free_deeply (3),
.BR gfarm_stringlist_init (3)

