.TH gfarm_url_program_deliver 3 "10 Sep 2002"

.SH NAME

gfarm_url_program_deliver \- プログラムを指定したホストに配布する

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B "char *"
.br
.BI "gfarm_url_program_deliver(char *" gfarm_url ,
.in +.5i
.BI "int " nhosts ,
.BI "char **" hosts ,
.br
.BI "char *** " delivered_paths );
.in

.SH DESCRIPTION

.I gfarm_url
で指定したプログラムを、
.I nhosts
個の要素を持つ文字列配列
.I hosts
で指定したホストに配布します。
配布された各ホスト上でのプログラムの絶対パスを、
.I nhosts
個の要素を持つ文字列配列に格納し、その配列のアドレスを
.I delivered_paths
が指す先に返します。

.I delivered_paths
に得た文字列配列は、不要になったら 
.BR gfarm_strings_free_deeply (3)
で解放する必要があります。

.SH "RETURN VALUES"

.TP
.SB NULL
.br
正常終了を示します。
.TP
.SB GFARM_ERR_NO_MEMORY
.br
メモリ不足のため処理を中止しました。
.TP
その他
.br
上記以外のエラーが生じたことを示します。

.SH "SEE ALSO"
.BR gfarm_url_program_deliver (3),
.BR gfarm_strings_free_deeply (3)
