.TH gfarm_url_fragments_replicate 3 "10 Sep 2002"

.SH NAME

gfarm_url_fragments_replicate \- ファイルのレプリカを作成する

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B "char *"
.br
.BI "gfarm_url_fragments_replicate(char *" gfarm_url ,
.in +.5i
.BI "int " ndsthosts ,
.br
.BI "char **" dsthosts );
.in

.SH DESCRIPTION

ファイル
.I gfarm_url
を構成する、
.I ndsthosts
個のフラグメントのレプリカを、文字列配列
.I dsthosts
で指定したホストに作成します。
N 番目のフラグメントは、配列
.I dsthosts
の N 番目の要素で指定したホストに複製されます。

フラグメントの数と異なる値を
.I ndsthosts
に指定した場合には、エラーとなります。

.SH "RETURN VALUES"

.TP
.SB NULL
.br
正常終了を示します。
.TP
.SB GFARM_ERR_NO_MEMORY
.br
メモリ不足のため処理を中止しました。
.TP
.SB GFARM_ERR_OPERATION_NOT_PERMITTED
.br
引数として、フラグメント化ファイル以外のファイルを指定しました。
.TP
その他
.br
上記以外のエラーが生じたことを示します。

.SH "SEE ALSO"
.BR gfarm_url_section_replicate_from_to (3),
.BR gfarm_url_section_replicate_from_to (3)
