.TH gfarm_url_program_register 3 "10 Sep 2002"

.SH NAME

gfarm_url_program_register \- プログラムを登録する

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B "char *"
.br
.BI "gfarm_url_program_register(char *" gfarm_url ,
.in +.5i
.BI "char *" architecture ,
.BI "char *" filename ,
.br
.BI "int " nreplicas );
.in

.SH DESCRIPTION

引数
.I architecture
で指定した機種向けの実行形式ファイル
.I filename
を、
.I gfarm_url
で指定したパス名に登録します。
また、
.I nreplicas
に、作成するレプリカの数を指定します。

引数
.I nreplicas
は、将来のバージョンで削除される予定です。

.SH "RETURN VALUES"

.TP
.SB NULL
.br
正常終了を示します。
.TP
.SB GFARM_ERR_NO_MEMORY
.br
メモリ不足のため処理を中止しました。
.TP
.SB GFARM_ERR_OPERATION_NOT_PERMITTED
.br
指定したファイルに、実行可能ビットが立っていませんでした。
.TP
その他
.br
上記以外のエラーが生じたことを示します。

.SH "SEE ALSO"
.BR gfarm_url_program_deliver (3)
