'\" t
.\"     Title: gfs_pio_seek
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 20 Jun 2019
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFS_PIO_SEEK" "3" "20 Jun 2019" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfs_pio_seek \- 指定した位置にシークする
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gfarm/gfarm\&.h>
.fi
.ft
.HP \w'gfarm_error_t\ gfs_pio_seek('u
.BI "gfarm_error_t\ gfs_pio_seek(GFS_File\ " "gf" ", gfarm_off_t\ " "offset" ", int\ " "whence" ", gfarm_off_t\ *\ " "result" ");"
.SH "DESCRIPTION"
.PP
ファイル
\fIgf\fR
を、
\fIwhence\fR
と
\fIoffset\fR
で指定した位置にシークします。 引数
\fIoffset\fR
は、
\fIwhence\fR
が GFARM_SEEK_SET の場合にはファイル先頭から、 GFARM_SEEK_CUR の場合には現在のシーク位置から、 GFARM_SEEK_END の場合にはファイル末尾からのオフセットです。
.PP
引数
\fIresult\fR
が
NULL
でない場合には、移動後の位置を
\fIresult\fR
の指す先に返します。
.SH "RETURN VALUES"
.PP
\fBGFARM_ERR_NO_ERROR\fR
.RS 4
正常終了を示します。
.RE
.PP
\fBGFARM_ERR_NO_MEMORY\fR
.RS 4
メモリ不足のため処理を中止しました。
.RE
.PP
\fBGFARM_ERR_INVALID_ARGUMENT\fR
.RS 4
指定されたwhenceとoffsetが不正な値です。
.RE
.PP
その他
.RS 4
上記以外のエラーが生じたことを示します。
\fBgfarm_error_string\fR(3)
によりエラーの原因を文字列に変換することができます。
.RE
.SH "SEE ALSO"
.PP
\fBgfs_pio_create\fR(3),
\fBgfs_pio_open\fR(3)
