'\" t
.\"     Title: gfs_pio_datasync
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 20 Jun 2019
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFS_PIO_DATASYNC" "3" "20 Jun 2019" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfs_pio_datasync \- メモリ上のファイルの内容をディスクに反映させる
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gfarm/gfarm\&.h>
.fi
.ft
.HP \w'gfarm_error_t\ gfs_pio_datasync('u
.BI "gfarm_error_t\ gfs_pio_datasync(GFS_File\ " "gf" ");"
.SH "DESCRIPTION"
.PP
書き込み用にオープンしているファイル
\fIgf\fRの、メモリ上にあるデータを実際 にディスクに書き込み，入出力の完了を待ってから戻ります．メタデータは 更新しません．別の関数
\fBgfs_pio_sync\fRは，ファイルデータに加えてメタデー タもディスクに書き込みます．
.SH "RETURN VALUES"
.PP
\fBGFARM_ERR_NO_ERROR\fR
.RS 4
正常終了を示します．
.RE
.PP
\fBGFARM_ERR_NO_MEMORY\fR
.RS 4
メモリ不足のため処理を中止しました．
.RE
.PP
その他
.RS 4
上記以外のエラーが生じたことを示します．
.RE
.SH "SEE ALSO"
.PP
\fBgfs_pio_sync\fR(3),
\fBgfs_pio_create\fR(3),
\fBgfs_pio_open\fR(3),
\fBgfs_pio_write\fR(3),
\fBgfs_pio_flush\fR(3)
