.TH gfs_pio_write 3 "1 May 2002"

.SH NAME

gfs_pio_write \- ファイルの書き込み

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B "char *"
.br
.BI "gfs_pio_write(GFS_File " gf ,
.BI "void *" buffer ,
.BI "int " size ,
.BI "int *" np );

.SH DESCRIPTION

.I buffer
から
.I size
バイトだけ、ファイル
.I gf
へ書き込みます。
実際に書き込まれたバイト数は
.I np
の指す先に返します。

.SH "RETURN VALUES"

.TP
.SB NULL
.br
正常終了を示します。
.TP
.SB GFARM_ERR_NO_MEMORY
.br
メモリ不足のため処理を中止しました。
.TP
その他
.br
上記以外のエラーが生じたことを示します。


.SH "SEE ALSO"
.BR gfs_pio_create (3),
.BR gfs_pio_flush (3),
.BR gfs_pio_open (3)
