'\" t
.\"     Title: gfs_stat
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 24 Jun 2019
.\"    Manual: Gfarm
.\"    Source: Gfarm
.\"  Language: English
.\"
.TH "GFS_STAT" "3" "24 Jun 2019" "Gfarm" "Gfarm"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gfs_stat \- ファイル属性取得
.SH "SYNOPSIS"
.sp
.ft B
.nf
#include <gfarm/gfarm\&.h>
.fi
.ft
.HP \w'gfarm_error_t\ gfs_stat('u
.BI "gfarm_error_t\ gfs_stat(const\ char\ *\ " "gfarm_url" ", struct\ gfs_stat\ *\ " "status" ");"
.SH "DESCRIPTION"
.PP
引数
\fIgfarm_url\fR
のファイル属性を
\fIstatus\fR
の指す先に取得します。
\fIstatus\fR
には、動的に確保されたメモリへのポインタが含まれるので、この後、 gfs_stat_free(3) を使ってそのメモリを解放する必要があります。
.SH "RETURN VALUES"
.PP
\fBGFARM_ERR_NO_ERROR\fR
.RS 4
正常終了を示します。
.RE
.PP
\fBGFARM_ERR_NO_MEMORY\fR
.RS 4
メモリ不足のため処理を中止しました。
.RE
.PP
\fBGFARM_ERR_AUTHENTICATION\fR
.RS 4
gfmd(8) に対するユーザー認証が失敗しました。
.RE
.PP
\fBGFARM_ERR_PERMISSION_DENIED\fR
.RS 4
指定されたパスへアクセスする権限が、ありません。
.RE
.PP
\fBGFARM_ERR_NO_SUCH_OBJECT\fR
.RS 4
指定されたパス名が存在しません。
.RE
.PP
\fBGFARM_ERR_NOT_A_DIRECTORY\fR
.RS 4
指定したパス名の親ディレクトリが、実際にはディレクトリでなかったことを 示します。
.RE
.PP
その他
.RS 4
上記以外のエラーが生じたことを示します。
.RE
.SH "SEE ALSO"
.PP
\fBgfs_stat_free\fR(3)
