.TH gfs_pio_flush 3 "1 May 2002"

.SH NAME

gfs_pio_flush \- 書き込みをフラッシュする。

.SH SYNOPSIS

.B "#include <gfarm/gfarm.h>"
.LP
.B "char *"
.br
.BI "gfs_pio_flush(GFS_File " gf );

.SH DESCRIPTION

書き込み用にオープンしているファイル
.I gf
の、書き込みバッファに溜まっているデータを実際にディスクに書き込みます。

.SH "RETURN VALUES"

.TP
.SB NULL
.br
正常終了を示します。
.TP
.SB GFARM_ERR_NO_MEMORY
.br
メモリ不足のため処理を中止しました。
.TP
その他
.br
上記以外のエラーが生じたことを示します。

.SH "SEE ALSO"
.BR gfs_pio_create (3),
.BR gfs_pio_open (3),
.BR gfs_pio_write (3)

