# $Id$

top_objdir = ../../..
top_srcdir = $(top_objdir)
srcdir = .

include $(top_srcdir)/makes/var.mk
include $(srcdir)/../Makefile.inc

MAN = \
	GFARM_STRINGLIST_ELEm.3 \
	GFARM_STRINGLIST_STRARRAY.3 \
	gfarm_hostlist_read.3 \
	gfarm_import_fragment_config_read.3 \
	gfarm_import_fragment_size_alloc.3 \
	gfarm_initialize.3 \
	gfarm_stringlist_add.3 \
	gfarm_stringlist_cat.3 \
	gfarm_stringlist_elem.3 \
	gfarm_stringlist_free.3 \
	gfarm_stringlist_free_deeply.3 \
	gfarm_stringlist_init.3 \
	gfarm_stringlist_length.3 \
	gfarm_strings_free_deeply.3 \
	gfarm_terminate.3 \
	gfarm_url_hosts_schedule.3 \
	gfs_chmod.3 \
	gfs_chown.3 \
	gfs_closedir.3 \
	gfs_mkdir.3 \
	gfs_opendir.3 \
	gfs_pio_close.3 \
	gfs_pio_create.3 \
	gfs_pio_eof.3 \
	gfs_pio_error.3 \
	gfs_pio_flush.3 \
	gfs_pio_getc.3 \
	gfs_pio_getline.3 \
	gfs_pio_open.3 \
	gfs_pio_putc.3 \
	gfs_pio_putline.3 \
	gfs_pio_puts.3 \
	gfs_pio_read.3 \
	gfs_pio_seek.3 \
	gfs_pio_set_local.3 \
	gfs_pio_set_view_index.3 \
	gfs_pio_set_view_local.3 \
	gfs_pio_ungetc.3 \
	gfs_pio_write.3 \
	gfs_readdir.3 \
	gfs_rename.3 \
	gfs_rmdir.3 \
	gfs_stat.3 \
	gfs_stat_free.3 \
	gfs_unlink.3

include $(top_srcdir)/makes/man.mk
