top_builddir = ../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

datadir=$(default_datadir)/gfarm/gfservice

DATA =	$(srcdir)/get_auth_type \
	$(srcdir)/get_host \
	$(srcdir)/gfjournal_m \
	$(srcdir)/grid_proxy_init \
	$(srcdir)/kill_gfmd \
	$(srcdir)/reboot_host

include $(top_srcdir)/makes/data.mk
