top_builddir = ../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

datadir=$(default_datadir)/gfarm/gfservice/systest/gfarm_v2

DATA =	$(srcdir)/get_host \
	$(srcdir)/gfjournal_m \
	$(srcdir)/kill_gfmd \
	$(srcdir)/reboot_host \
	$(srcdir)/compare_spool_file \
	$(srcdir)/config_gfarm_update_r \
	$(srcdir)/read_and_register \
	$(srcdir)/get_gfsd_hostid_by_name \
	$(srcdir)/check_hostids_defined

include $(top_srcdir)/makes/data.mk
