name: GitHub CI

on:
  push:
  pull_request:

jobs:

  coderrect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git libssl-dev libpq-dev libibverbs.dev \
              libsasl2-dev

      - name: Build
        run: |
          gcc --version
          ./configure --enable-xmlattr --with-infiniband \
              --disable-check-python-mod
          make -j$(nproc)

      - name: correct scan
        uses: coderrect-inc/coderrect-github-action@main
