top_builddir = ../..
top_srcdir = $(top_builddir)
srcdir = .

include $(top_srcdir)/makes/var.mk

SUBDIRS = \
	gfperf-lib \
	gfperf-metadata	\
	gfperf-copy \
	gfperf-replica \
	gfperf-tree \
	gfperf-autoreplica \
	gfperf-read \
	gfperf-write \
	gfperf-parallel-read \
	gfperf-parallel-write \
	gfperf-parallel-replica \
	gfperf-parallel-autoreplica \
	gfperf-rb \
	gfperf-wrapper \
	gfstress

include $(top_srcdir)/makes/subdir.mk
